<?php echo $this->partial('manage/hero.phtml', ['one' => $this->one]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.UPLOAD'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-upload-file" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reset-uploader="#upload-zone">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#upload-zone-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="upload-zone-container">
                    <div class="block-content block-content-full">
                        <div id="upload-zone" style="width: 100%; min-height: 100px;" class=""></div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.MEDIA_GALLERY'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-upload-file" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reset-uploader="#media-gallery">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#media-gallery-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="media-gallery-container">
                    <div class="block-content block-content-full">

                        <!-- Advanced Gallery -->
                        <div id="gallery" class="row gutters-tiny items-push js-gallery push"></div>
                        <!-- END Advanced Gallery -->

                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
<!-- END Page Content -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-media-form" tabindex="-1" role="dialog" aria-labelledby="modal-media-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="" class="block-title"><?php echo $this->translate('FORM.EDIT_MEDIA'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('manage/media_form.phtml', [ 'mediaForm' => $this->mediaForm ] ) ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-media-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->

<!-- Gallery Image Template -->
<div id="gallery-template" class="hide">
    <div class="col-md-6 col-lg-4 col-xl-3 animated fadeIn">
        <div class="options-container fx-item-zoom-in">

            <img class="img-fluid options-item" src="" alt="" title="" id="" data-extension="" />

            <div class="options-overlay bg-black-75">
                <div class="options-overlay-content">

                    <h3 class="h4 font-w400 text-white mb-1 caption-title"><?php echo $this->translate('TEXT.SET_TITLE'); ?></h3>
                    <h4 class="h6 font-w400 text-white-75 mb-3 description"><?php echo $this->translate('TEXT.SET_DESCRIPTION'); ?></h4>

                    <button type="button" class="btn btn-sm btn-primary img-lightbox">
                        <i class="fa fa-search-plus mr-1"></i> <?php echo $this->translate('BUTTON.VIEW'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-secondary img-edit">
                        <i class="fa fa-pencil-alt mr-1"></i> <?php echo $this->translate('BUTTON.EDIT'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-alt-secondary img-copy" data-title="<?php echo $this->translate('TEXT.COPIED'); ?>" data-clipboard-text="">
                        <i class="fa fa-copy mr-1"></i> <?php echo $this->translate('BUTTON.COPY_LINK'); ?>
                    </button>

                </div>
            </div>

        </div>
    </div>
</div>
<!-- END Gallery Image Template -->
