<!-- Media Form -->
<form id="media-form" name="<?php echo $this->mediaForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->mediaForm->media_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-media"><?php echo $this->translate('TAB.MEDIA'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-fileinfo"><?php echo $this->translate('TAB.FILE_INFO'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-media"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-media">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-media" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.MEDIA'); ?></h4>

                <div class="form-group">
                    <label for="caption_title"><?php echo $this->mediaForm->caption_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->mediaForm->caption_title->getDescription(); ?>"></i>
                    <?php echo $this->mediaForm->caption_title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="description"><?php echo $this->mediaForm->description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->mediaForm->description->getDescription(); ?>"></i>
                    <?php echo $this->mediaForm->description; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="tags"><?php echo $this->mediaForm->tags->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->mediaForm->tags->getDescription(); ?>"></i>
                    <?php echo $this->mediaForm->tags; ?>
                    <div class="message-container"></div>
                </div>

                <hr />
                <p><strong><?php echo $this->translate('LABEL.PUBLIC_URL'); ?>: </strong><span class="public_url"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-fileinfo" role="tabpanel">

                <p><strong><?php echo $this->translate('LABEL.TYPE_STORAGE'); ?>: </strong><span class="type_storage"></span></p>
                <p><strong><?php echo $this->translate('LABEL.BUCKET'); ?>: </strong><span class="bucket"></span></p>
                <p><strong><?php echo $this->translate('LABEL.PREFIX_PATH'); ?>: </strong><span class="prefix_path"></span></p>
                <p><strong><?php echo $this->translate('LABEL.MIME_TYPE'); ?>: </strong><span class="mime_type"></span></p>
                <p><strong><?php echo $this->translate('LABEL.FILENAME'); ?>: </strong><span class="filename"></span></p>
                <p><strong><?php echo $this->translate('LABEL.SIZE'); ?>: </strong><span class="size"></span></p>
                <p><strong><?php echo $this->translate('LABEL.HEIGHT'); ?>: </strong><span class="height"></span></p>
                <p><strong><?php echo $this->translate('LABEL.WIDTH'); ?>: </strong><span class="width"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-media" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.UPLOAD_IP'); ?>: </strong><span class="upload_ip"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-media" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->mediaForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_media"><?php echo $this->mediaForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->mediaForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->mediaForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_media"><?php echo $this->mediaForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->mediaForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Media Form -->
