<!-- Hero -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo36@2x.jpg');">
    <div class="hero bg-black-75 overflow-hidden">
        <div class="hero-inner">
            <div class="content content-full text-center">
                <div class="mb-5 invisible" data-toggle="appear" data-class="animated fadeInDown">
                    <img class="rounded" src="<?php echo $this->template->assets_folder; ?>/media/images/tiger.png" width="100" />
                </div>
                <h1 class="display-4 font-w600 mb-3 text-white invisible" data-toggle="appear" data-class="animated fadeInDown">
                    <span class="font-w300">Welcome to </span> TIGER <span class="font-w300">Platform <?php echo $this->template->version; ?></span>
                </h1>
                <h2 class="h3 font-w400 text-white-50 mb-5 invisible" data-toggle="appear" data-class="animated fadeInDown" data-timeout="300">
                    Build your next super-awesome idea on the one platform that takes you from zero to orbit in one click.
                </h2>
                <span class="m-2 d-inline-block invisible" data-toggle="appear" data-class="animated fadeInUp" data-timeout="600">
                    <a class="btn btn-success px-4 py-2" data-toggle="click-ripple" href="/">
                        <i class="fa fa-fw fa-arrow-down mr-1"></i> Features
                    </a>
                </span>
                <span class="m-2 d-inline-block invisible" data-toggle="appear" data-class="animated fadeInUp" data-timeout="600">
                    <a class="btn btn-primary px-4 py-2" data-toggle="click-ripple" href="https://demo.webtigers.com:8081/admin">
                        <i class="fa fa-fw fa-rocket mr-1"></i> Live Preview
                    </a>
                </span>
            </div>
        </div>
        <div class="hero-meta">
            <div class="animated slideInDown infinite">
                <i class="fa fa-angle-down text-white-50 fa-2x"></i>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- TIGER AWS Edition -->
<div id="one-vue-edition" class="bg-white">
    <div class="content content-full">
        <div class="py-5 text-center">
            <h2 class="h1 mb-2">
                TIGER AWS Edition
            </h2>
            <h3 class="font-w400 text-muted mb-5">
                Launch a TIGER instance. Everything you need to start building your ideas is already done.
            </h3>
            <div class="row justify-content-center">
                <!-- What is Tiger -->
                <div class="col-sm-6 col-xl-5 invisible" data-toggle="appear">
                    <a href="/" class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <img class="rounded" src="<?php echo $this->template->assets_folder; ?>/media/images/tiger.png" width="80" />
                            </div>
                            <h4 class="mb-2">Instant PHP Development Platform for AWS</h4>
                            <p class="font-size-sm text-muted text-left">
                                TIGER is made for Developers. Startups. Agencies. Enterprises. Anyone who needs an instant
                                website for a client or wants to jumpstart their web application development effort. TIGER
                                is the "application in a box" that scales with you and your ideas.
                            </p>
                        </div>
                    </a>
                </div>
                <!-- END What is Tiger -->
                <!-- What is Tiger -->
                <div class="col-sm-6 col-xl-5 invisible" data-toggle="appear">
                    <a href="/" class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <img class="rounded" src="<?php echo $this->template->assets_folder; ?>/media/images/tiger.png" width="80" />
                            </div>
                            <h4 class="mb-2">Manage your clients with a Website-in-a-box.</h4>
                            <p class="font-size-sm text-muted text-left">
                                Launch instance. Get website. It's all there. Already configured. Already up and running.
                                Use the pre-installed themes or drop in one of your own. TIGER's full-featured, easy-to-use
                                CMS means you are off and running instantly.
                            </p>
                        </div>
                    </a>
                </div>
                <!-- END What is Tiger -->
            </div>
        </div>
    </div>
</div>
<!-- END TIGER AWS Edition -->

<!-- Featrues -->
<div id="one-versions" class="bg-light">
    <div class="content content-full">
        <div class="py-5 text-center">
            <h2 class="h1 mb-2">
                TIGER <?php echo $this->template->version; ?> Features
            </h2>
            <h3 class="font-w400 text-muted mb-5">
                Inside the box you will find everything you need to jumpstart your new ideas.
            </h3>
            <div class="row row-deck">
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- Get Started Version -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fa fa-4x fa-burn text-modern"></i>
                            </div>
                            <h4 class="mb-2">Full LAMP Stack</h4>
                            <p class="font-size-sm text-muted text-left">
                                A production ready version of Amazon Linux 2, Apache 2.4, PHP 7.2, and MariaDB 10.2. No pre-configuration needed. It just works.
                            </p>
                        </div>
                    </div>
                    <!-- END Get Started Version -->
                </div>
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- PHP Version -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fab fa-4x fa-php text-amethyst"></i>
                            </div>
                            <h4 class="mb-2">Modularized PHP Framework</h4>
                            <p class="font-size-sm text-muted text-left">
                                TIGER uses a newly updated and community supported Zend Framework 1 that works flawlessly
                                with PHP 7.x. Drop-in your module's code and it just works.
                            </p>
                        </div>
                    </div>
                    <!-- END PHP Version -->
                </div>
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- HTML Version -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fab fa-4x fa-html5 text-city"></i>
                            </div>
                            <h4 class="mb-2">Complete HTML Templates</h4>
                            <p class="font-size-sm text-muted text-left">
                                Tiger gives you a beautiful state-of-the art HTML Website and Admin themes that are ready to go.
                                Just start dropping in your components. Done.
                            </p>
                        </div>
                    </div>
                    <!-- END HTML Version -->
                </div>
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- Laravel Starter Kit -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fas fa-4x fa-desktop text-modern"></i>
                            </div>
                            <h4 class="mb-2">Full CMS</h4>
                            <p class="font-size-sm text-muted text-left">
                                TIGER comes with a fully-functional built-in enterprise-class content management system
                                and full-featured blogging engine.
                            </p>
                        </div>
                    </div>
                    <!-- END Laravel Starter Kit -->
                </div>

                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- Get Started Version -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fa fa-4x fa-users text-city"></i>
                            </div>
                            <h4 class="mb-2">Enterprise User Module</h4>
                            <p class="font-size-sm text-muted text-left">
                                A full-featured, enterprise-class user signup and management system is already installed and working.
                            </p>
                        </div>
                    </div>
                    <!-- END Get Started Version -->
                </div>
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- PHP Version -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fa fa-4x fa-lock text-black-50"></i>
                            </div>
                            <h4 class="mb-2">Access Control Permissions</h4>
                            <p class="font-size-sm text-muted text-left">
                                A full-featured ACL (access control list). Set roles, permissions and resources to
                                secure for any area of your application.
                            </p>
                        </div>
                    </div>
                    <!-- END PHP Version -->
                </div>
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- HTML Version -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fa fa-4x fa-globe-europe text-primary"></i>
                            </div>
                            <h4 class="mb-2">Localize and Translate</h4>
                            <p class="font-size-sm text-muted text-left">
                                Database-driven translations give you instant localization and internationalization.
                            </p>
                        </div>
                    </div>
                    <!-- END HTML Version -->
                </div>
                <div class="col-sm-6 col-xl-3 invisible" data-toggle="appear">
                    <!-- Laravel Starter Kit -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="py-4">
                                <i class="fas fa-4x fa-desktop text-city"></i>
                            </div>
                            <h4 class="mb-2">Well Documented</h4>
                            <p class="font-size-sm text-muted text-left">
                                TIGER is exceptionally well documented. Even our core code files are fully commented
                                and fully editable.
                            </p>
                        </div>
                    </div>
                    <!-- END Laravel Starter Kit -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Features -->

<!-- Pricing Hero Content -->
<div class="bg-primary-dark">
    <div class="content content-full overflow-hidden">
        <div class="mt-7 mb-5 text-center">
            <h1 class="h2 text-white mb-2 invisible" data-toggle="appear" data-class="animated fadeInDown">
                Super easy. Super affordable.
            </h1>
            <h2 class="h4 font-w400 text-white-75 invisible" data-toggle="appear" data-class="animated fadeInDown">
                Because it's an AWS instance, the low cost is just billed to your existing AWS account.<br/>
                Discounts accumulate and are applied automagically.
            </h2>
        </div>
    </div>
</div>
<!-- END Pricing Hero Content -->
<!-- Pricing -->
<div class="content overflow-hidden">
    <div class="row">
        <div class="col-md-6 col-xl-3 invisible" data-toggle="appear" data-offset="50" data-class="animated fadeInUp">
            <!-- Developer Plan -->
            <a class="block block-link-shadow block-themed text-center" href="javascript:void(0)">
                <div class="block-header">
                    <h3 class="block-title">
                        <i class="fa fa-user mr-1"></i> Developer
                    </h3>
                </div>
                <div class="block-content bg-body-light">
                    <div class="py-2">
                        <p class="h1 font-w700 mb-2">$8</p>
                        <p class="h6 text-muted">per month / instance</p>
                    </div>
                </div>
                <div class="block-content">
                    <div class="font-size-sm py-2">
                        <p>
                            <strong>1</strong> Instances
                        </p>
                        <p>
                            <strong>Single</strong> Project / App
                        </p>
                        <p>
                            <strong>Single</strong> Client
                        </p>
                        <p>
                            <strong>Any Size</strong> AWS Image
                        </p>
                        <p>
                            <strong>Email</strong> Support
                        </p>
                    </div>
                </div>
                <div class="block-content block-content-full bg-body-light">
                    <span class="btn btn-primary px-4">Sign Up</span>
                </div>
            </a>
            <!-- END Developer Plan -->
        </div>
        <div class="col-md-6 col-xl-3 invisible" data-toggle="appear" data-offset="50" data-timeout="200" data-class="animated fadeInUp">
            <!-- Startup Plan -->
            <a class="block block-link-shadow text-center" href="javascript:void(0)">
                <div class="block-header">
                    <h3 class="block-title">Startup</h3>
                </div>
                <div class="block-content bg-body-light">
                    <div class="py-2">
                        <p class="h1 font-w700 mb-2">$7</p>
                        <p class="h6 text-muted">per month / instance</p>
                    </div>
                </div>
                <div class="block-content">
                    <div class="font-size-sm py-2">
                        <p>
                            <strong>10+</strong> Instances
                        </p>
                        <p>
                            <strong>Multiple</strong> Projects / Apps
                        </p>
                        <p>
                            <strong>Multiple</strong> Clients
                        </p>
                        <p>
                            <strong>Any Size</strong> AWS Images
                        </p>
                        <p>
                            <strong>Email</strong> Support
                        </p>
                    </div>
                </div>
                <div class="block-content block-content-full bg-body-light">
                    <span class="btn btn-secondary px-4">Sign Up</span>
                </div>
            </a>
            <!-- END Startup Plan -->
        </div>
        <div class="col-md-6 col-xl-3 invisible" data-toggle="appear" data-offset="50" data-timeout="400" data-class="animated fadeInUp">
            <!-- Business Plan -->
            <a class="block block-link-shadow block-themed block-fx-shadow text-center" href="javascript:void(0)">
                <div class="block-header">
                    <h3 class="block-title">
                        <i class="fa fa-users mr-1"></i> Agency
                    </h3>
                </div>
                <div class="block-content bg-body-light">
                    <div class="py-2">
                        <p class="h1 font-w700 mb-2">$6</p>
                        <p class="h6 text-muted">per month / instance</p>
                    </div>
                </div>
                <div class="block-content">
                    <div class="font-size-sm py-2">
                        <p>
                            <strong>25+</strong> Instances
                        </p>
                        <p>
                            <strong>Multiple</strong> Projects / Apps
                        </p>
                        <p>
                            <strong>Multiple</strong> Clients
                        </p>
                        <p>
                            <strong>Any Size</strong> AWS Images
                        </p>
                        <p>
                            <strong>Email</strong> Support
                        </p>
                    </div>
                </div>
                <div class="block-content block-content-full bg-body-light">
                    <span class="btn btn-primary px-4">Sign Up</span>
                </div>
            </a>
            <!-- END Business Plan -->
        </div>
        <div class="col-md-6 col-xl-3 invisible" data-toggle="appear" data-offset="50" data-timeout="600" data-class="animated fadeInUp">
            <!-- VIP Plan -->
            <a class="block block-link-shadow text-center" href="javascript:void(0)">
                <div class="block-header">
                    <h3 class="block-title">Enterprise</h3>
                </div>
                <div class="block-content bg-body-light">
                    <div class="py-2">
                        <p class="h1 font-w700 mb-2">$4</p>
                        <p class="h6 text-muted">per month / instance</p>
                    </div>
                </div>
                <div class="block-content">
                    <div class="font-size-sm py-2">
                        <p>
                            <strong>50+</strong> Instances
                        </p>
                        <p>
                            <strong>Multiple</strong> Projects / Apps
                        </p>
                        <p>
                            <strong>Multiple</strong> Clients
                        </p>
                        <p>
                            <strong>Any Size</strong> AWS Images
                        </p>
                        <p>
                            <strong>Email</strong> Support
                        </p>
                    </div>
                </div>
                <div class="block-content block-content-full bg-body-light">
                    <span class="btn btn-secondary px-4">Sign Up</span>
                </div>
            </a>
            <!-- END VIP Plan -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xl-12 invisible" data-toggle="appear" data-offset="50" data-class="animated fadeInUp">
            <p class="h6 font-w400 text-body-color-dark text-center invisible" data-toggle="appear" data-class="animated fadeInDown">
                * Above prices are in addition to the size cost of the AWS instance launched with TIGER installed.
            </p>
        </div>
    </div>
</div>
<!-- END Pricing -->
<!-- Upgrade -->
<div class="bg-body-dark">
    <div class="content content-full">
        <div class="my-5 text-center">
            <h3 class="h4 mb-4 invisible" data-toggle="appear">Imagine the next great thing. Then build it.</h3>
            <a class="btn btn-rounded btn-success px-4 py-2 invisible" data-toggle="appear" data-class="animated bounceIn" href="/">Start Building Today</a>
        </div>
    </div>
</div>
<!-- END Upgrade -->

<!-- Hero Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo25@2x.jpg');">
    <div class="bg-black-50">
        <div class="content content-full overflow-hidden">
            <div class="mt-7 mb-5 text-center">
                <h1 class="h2 text-white mb-2 invisible" data-toggle="appear" data-class="animated fadeInDown">
                    Why developers are choosing TIGER. Why you should too.
                </h1>
                <h2 class="h4 font-w400 text-white-75 invisible" data-toggle="appear" data-class="animated fadeInDown">
                    Check out how TIGER can save you valuable time, money, and resources ...
                </h2>
            </div>
        </div>
    </div>
</div>
<!-- END Hero Content -->
<!-- Use Cases -->
<div class="bg-white">
    <div class="content content-full">
        <div class="row justify-content-center">
            <div class="col-lg-10">

                <!-- Circle Mini Features -->
                <!-- div class="row items-push text-center py-5">
                    <div class="col-4 col-lg-2 invisible" data-toggle="appear" data-offset="-100" data-class="animated bounceIn">
                        <div class="item item-circle bg-white border mb-2 mx-auto">
                            <i class="si si-vector text-default"></i>
                        </div>
                        <div class="font-w600">Design</div>
                    </div>
                    <div class="col-4 col-lg-2 invisible" data-toggle="appear" data-offset="-100" data-class="animated bounceIn" data-timeout="150">
                        <div class="item item-circle bg-white border mb-2 mx-auto">
                            <i class="si si-badge text-flat"></i>
                        </div>
                        <div class="font-w600">Quality</div>
                    </div>
                    <div class="col-4 col-lg-2 invisible" data-toggle="appear" data-offset="-100" data-class="animated bounceIn" data-timeout="300">
                        <div class="item item-circle bg-white border mb-2 mx-auto">
                            <i class="si si-chemistry text-smooth"></i>
                        </div>
                        <div class="font-w600">Creativity</div>
                    </div>
                    <div class="col-4 col-lg-2 invisible" data-toggle="appear" data-offset="-100" data-class="animated bounceIn" data-timeout="450">
                        <div class="item item-circle bg-white border mb-2 mx-auto">
                            <i class="si si-heart text-city"></i>
                        </div>
                        <div class="font-w600">Passion</div>
                    </div>
                    <div class="col-4 col-lg-2 invisible" data-toggle="appear" data-offset="-100" data-class="animated bounceIn" data-timeout="600">
                        <div class="item item-circle bg-white border mb-2 mx-auto">
                            <i class="si si-clock text-modern"></i>
                        </div>
                        <div class="font-w600">Time</div>
                    </div>
                    <div class="col-4 col-lg-2 invisible" data-toggle="appear" data-offset="-100" data-class="animated bounceIn" data-timeout="750">
                        <div class="item item-circle bg-white border mb-2 mx-auto">
                            <i class="si si-drop text-warning"></i>
                        </div>
                        <div class="font-w600">Colors</div>
                    </div>
                </div -->
                <!-- END Circle Mini Features -->

                <!-- Feature List -->
                <div class="row items-push py-5">
                    <div class="col-md-6">
                        <h3 class="h5 text-uppercase mb-2">
                            <i class="fa fa-check text-primary mr-2"></i> Instant Website / CMS / Blog
                        </h3>
                        <p>
                            TIGER is super easy to use. Launch a TIGER instance in AWS and your setup work is done. There's
                            literally nothing to configure. Your new website, blog, with a complete CMS is already configured
                            and running the moment the instance launches.
                        </p>
                    </div>
                    <div class="col-md-6">
                        <h3 class="h5 text-uppercase mb-2">
                            <i class="fa fa-check text-primary mr-2"></i> Self-contained for your Clients
                        </h3>
                        <p>
                            Your client needs a website with some custom components. You have it handled with TIGER.
                            Your client's server instance is self-contained and not shared with your other clients.
                            If traffic skyrockets or something breaks, no worries. It won't affect your other clients or
                            bring down your whole business.
                        </p>
                    </div>
                    <div class="col-md-6">
                        <h3 class="h5 text-uppercase mb-2">
                            <i class="fa fa-check text-primary mr-2"></i> Jumpstart Your Next BIG Enterprise-class Idea
                        </h3>
                        <p>
                            Your next big app idea is going to need to have business entities, users, translation,
                            access control, front-ends, API's, a database, caching, and be hugely scalable. No problem.
                            Tiger has it handled. Right out of the box you have an enterprise-class build of of a PHP 7
                            application and full LAMP stack. Get rockin' ...
                        </p>
                    </div>
                    <div class="col-md-6">
                        <h3 class="h5 text-uppercase mb-2">
                            <i class="fa fa-check text-primary mr-2"></i> Classic ZendFramework 1 and PHP 7
                        </h3>
                        <p>The original is still the best. Newly updated and community supported, ZF1 is still the easiest
                           PHP framework to use. WebTIGERS has taken all of the guess work out of configuring ZF1 with
                           tons of great documentation both outside of and within the TIGER code. No PHP framework has been
                           more enterprise-used and security-tested over the years than Zend.
                        </p>
                    </div>
                    <div class="col-md-6">
                        <h3 class="h5 text-uppercase mb-2">
                            <i class="fa fa-check text-primary mr-2"></i> Way Affordable
                        </h3>
                        <p>
                            How much time, money and energy would it cost you to get up and running with all of Tiger's
                            exceptional features and interoperability, including full documentation for your teams? Weeks?
                            Months? With Tiger you are up and running for $8 bucks. Even with the server running for a
                            whole year, you are still less than the cost of a couple of hours for a senior developer.
                        </p>
                    </div>
                    <div class="col-md-6">
                        <h3 class="h5 text-uppercase mb-2">
                            <i class="fa fa-check text-primary mr-2"></i> Scalable. Optimized. Featured. Documented.
                        </h3>
                        <p>
                            It's all in there. It's all documented. Tiger comes with all of the most popular UI components
                            and features a developer could want for just about any size or type of project. Spin up a Tiger
                            instance today and take Tiger for a trial run, just for fun. Your next website and app is going
                            to look and function beautifully running on a Tiger!
                        </p>
                    </div>
                </div>
                <!-- END Feature List -->
            </div>
        </div>
    </div>
</div>
<!-- END Use Cases -->

<hr />

<!-- Themed UI -->
<div id="one-remastered" class="bg-white">
    <div class="content content-full">
        <div class="py-5 text-center">
            <h2 class="h1 mb-2">
                Rockstar Modern UI from PixelCave
            </h2>
            <h3 class="font-w400 text-muted mb-5">
                TIGER incorporates OneUI, a full-featured, carefully crafted admin template using the latest tech. <br/>
                Use as much or as little tech as you like. TIGER already works out of the box.
            </h3>
            <div class="row row-deck">
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Bootstrap 4 -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-amethyst-lighter mx-auto my-4">
                                <i class="fa fa-2x fa-fire text-amethyst"></i>
                            </div>
                            <h4 class="mb-2">Bootstrap 4</h4>
                            <p class="font-size-sm text-muted text-left">
                                The latest Bootstrap version now powers OneUI framework. Flexbox support and tons of
                                new features are ready for you to use.
                            </p>
                        </div>
                    </div>
                    <!-- END Bootstrap 4 -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Sass -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-danger-light mx-auto my-4">
                                <i class="fab fa-2x fa-sass text-danger"></i>
                            </div>
                            <h4 class="mb-2">Sass</h4>
                            <p class="font-size-sm text-muted text-left">
                                OneUI was built with Sass, overriding and extending Bootstrap in an intelligent way to
                                ensure a perfect and modular workflow.
                            </p>
                        </div>
                    </div>
                    <!-- END Sass -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- ES6 -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-warning-light mx-auto my-4">
                                <span class="font-w700 text-warning">ES6</span>
                            </div>
                            <h4 class="mb-2">ECMAScript 6</h4>
                            <p class="font-size-sm text-muted text-left">
                                OneUI was built with ES6, the new major JavaScript release which enables us writing
                                cleaner and better code.
                            </p>
                        </div>
                    </div>
                    <!-- END ES6 -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- FontAwesome 5 -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-flat-lighter mx-auto my-4">
                                <i class="fab fa-2x fa-font-awesome text-flat"></i>
                            </div>
                            <h4 class="mb-2">FontAwesome 5</h4>
                            <p class="font-size-sm text-muted text-left">
                                OneUI comes packed with the latest Font Awesome version, bringing you over 1300 freshly
                                made icons for your projects.
                            </p>
                        </div>
                    </div>
                    <!-- END FontAwesome 5 -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Gulp -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-city-lighter mx-auto my-4">
                                <i class="fab fa-2x fa-gulp text-city"></i>
                            </div>
                            <h4 class="mb-2">Gulp 4</h4>
                            <p class="font-size-sm text-muted text-left">
                                We created smart development tasks to help you focus on your projects. Just install the
                                npm dependencies and use them out of the box.
                            </p>
                        </div>
                    </div>
                    <!-- END Gulp -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- webpack -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-default-lighter mx-auto my-4">
                                <i class="fa fa-2x fa-boxes text-default"></i>
                            </div>
                            <h4 class="mb-2">webpack + Babel</h4>
                            <p class="font-size-sm text-muted text-left">
                                Babel makes your JavaScript code compatible with older browsers and webpack bundles your
                                JavaScript files together.
                            </p>
                        </div>
                    </div>
                    <!-- END webpack -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Browsersync -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-modern-lighter mx-auto my-4">
                                <i class="fab fa-2x fa-chrome text-modern"></i>
                            </div>
                            <h4 class="mb-2">Browsersync</h4>
                            <p class="font-size-sm text-muted text-left">
                                It will serve and sync your project across different browsers and also refresh them each
                                time your save your files.
                            </p>
                        </div>
                    </div>
                    <!-- END Browsersync -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Autoprefixer -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-smooth-lighter mx-auto my-4">
                                <i class="fab fa-2x fa-autoprefixer text-smooth"></i>
                            </div>
                            <h4 class="mb-2">Autoprefixer</h4>
                            <p class="font-size-sm text-muted text-left">
                                Peace of mind when working with Sass. Use the latest CSS syntax and Autoprefixer will
                                auto add any required prefixes for older browsers.
                            </p>
                        </div>
                    </div>
                    <!-- END Autoprefixer -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Modular Approach -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-gray-light mx-auto my-4">
                                <i class="fa fa-2x fa-truck-loading text-dark"></i>
                            </div>
                            <h4 class="mb-2">Modular Approach</h4>
                            <p class="font-size-sm text-muted text-left">
                                You can add your JavaScript or Sass overrides/customizations without altering the
                                original files, making the update process an easy one.
                            </p>
                        </div>
                    </div>
                    <!-- END Modular Approach -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- Improved Design -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-info-light mx-auto my-4">
                                <i class="fa fa-2x fa-brush text-info"></i>
                            </div>
                            <h4 class="mb-2">Improved Design</h4>
                            <p class="font-size-sm text-muted text-left">
                                Small touches and improvements were introduced throughout the template. From colors to
                                layout and fom custom elements to plugins.
                            </p>
                        </div>
                    </div>
                    <!-- END Improved Design -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- New Features -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-success-light mx-auto my-4">
                                <i class="fa fa-2x fa-smile-wink text-success"></i>
                            </div>
                            <h4 class="mb-2">New Features</h4>
                            <p class="font-size-sm text-muted text-left">
                                Dark header, light sidebar, flexbox based layout, page overlay, header search and even
                                more features are now available.
                            </p>
                        </div>
                    </div>
                    <!-- END New Features -->
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3 invisible" data-toggle="appear">
                    <!-- New Features -->
                    <div class="block block-rounded block-fx-pop">
                        <div class="block-content block-content-full">
                            <div class="item item-rounded bg-warning-light mx-auto my-4">
                                <i class="fa fa-2x fa-star text-warning"></i>
                            </div>
                            <h4 class="mb-2">OneUI is included Free!</h4>
                            <p class="font-size-sm text-muted text-left">
                                OneUI is included free with TIGER for you to use as part of your website or Saas offering.
                                No need to buy additional admin themes.
                            </p>
                        </div>
                    </div>
                    <!-- END New Features -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Themed UI -->

<!-- Call To Action -->
<div id="one-call-to-action" class="bg-white">
    <div class="content content-full">
        <div class="py-5 py-md-8 text-center">
            <h2 class="mb-2 invisible" data-toggle="appear" data-class="animated fadeInDown">
                Crafted with <i class="fa fa-fw fa-heart text-danger"></i> by <a class="link-fx text-danger" href="https://1.envato.market/ydb">pixelcave</a>
            </h2>
        </div>
    </div>
</div>
<!-- END Call To Action -->

<!-- Footer -->
<footer id="page-footer" class="bg-light">
    <div class="content py-5">
        <div class="row font-size-sm">
            <div class="col-sm-6 order-sm-2 py-1 text-center text-sm-right">
                &nbsp;
            </div>
            <div class="col-sm-6 order-sm-1 py-1 text-center text-sm-left">
                 &copy; WebTIGERS <span data-toggle="year-copy"></span>
            </div>
        </div>
    </div>
</footer>
<!-- END Footer -->
