<nav class="navbar navbar-expand-lg menu_one dark_menu sticky-nav">
    <div class="container">
        <a class="navbar-brand header_logo" href="/assets/docy/index.html">
            <img class="first_logo sticky_logo main_logo" src="/assets/docy/img/logo.png" srcset="/assets/docy/img/logo-2x.png 2x" alt="logo">
            <img class="white_logo" src="/assets/docy/img/logo-w.png" srcset="/assets/docy/img/logo-w2x.png 2x" alt="logo">
        </a>
        <div class="search-input">
            <ion-icon class="search-icon" name="search-outline"></ion-icon>
            <input type="text" placeholder="Search..." value="" class="">
        </div>
        <div class="mobile-dark-mode d-lg-none">
            <label for="something" class="tab-btn tab-btns">
                <ion-icon class="light-mode" name="contrast"></ion-icon>
            </label>
            <label for="something" class="tab-btn">
                <ion-icon class="dark-mode" name="contrast-outline"></ion-icon>
            </label>
        </div>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_toggle">
                            <span class="hamburger">
                                <span></span>
                                <span></span>
                                <span></span>
                            </span>
                            <span class="hamburger-cross">
                                <span></span>
                                <span></span>
                            </span>
                        </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav menu ml-auto">
                <li class="nav-item dropdown submenu">
                    <a href="/assets/docy/index.html" class="nav-link dropdown-toggle">Home</a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon" aria-hidden="false" data-toggle="dropdown"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="/assets/docy/index.html" class="nav-link">Creative Helpdesk</a></li>
                        <li class="nav-item"><a href="/assets/docy/index-multi.html" class="nav-link">Multi Helpdesk</a></li>
                        <li class="nav-item"><a href="/assets/docy/index-classic.html" class="nav-link">Classic Helpdesk</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu mega_menu tab-demo active">
                    <a href="/assets/docy/#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Docs</a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon" aria-hidden="true" data-toggle="dropdown"></i>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="row">
                                <div class="col-lg-5 tabHeader">
                                    <ul class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                        <li class="nav-item active">
                                            <a class="nav-link" id="v-pills-doc-tab" data-toggle="pill" href="/assets/docy/#v-pills-doc" role="tab" aria-controls="v-pills-doc" aria-selected="true">Doc Archives</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="v-pills-code-tab" data-toggle="pill" href="/assets/docy/#v-pills-code" role="tab" aria-controls="v-pills-code" aria-selected="false">Elements</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="v-pills-layout-tab" data-toggle="pill" href="/assets/docy/#v-pills-layout" role="tab" aria-controls="v-pills-layout" aria-selected="false">Layouts</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="v-pills-tour-tab" data-toggle="pill" href="/assets/docy/#v-pills-tour" role="tab" aria-controls="v-pills-tour" aria-selected="false">Reference</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="v-pills-content-tab" data-toggle="pill" href="/assets/docy/#v-pills-content" role="tab" aria-controls="v-pills-content" aria-selected="false">Content</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="v-pills-pages-tab" data-toggle="pill" href="/assets/docy/#v-pills-pages" role="tab" aria-controls="v-pills-pages" aria-selected="false">Other Pages</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-7">
                                    <div class="tab-content tabContent" id="v-pills-tabContent">
                                        <div class="tab-pane fade active show" id="v-pills-doc" role="tabpanel" aria-labelledby="v-pills-doc-tab">
                                            <div class="d-flex">
                                                <ul class="list-unstyled tab_list">
                                                    <li> <a href="/assets/docy/doc-main.html"> Doc Topics </a> </li>
                                                    <li> <a class="active" href="/assets/docy/archive-doc-single.html"> Single Product </a> </li>
                                                    <li> <a href="/assets/docy/archive-doc-multi.html"> Multi Products </a> </li>
                                                </ul>
                                            </div>
                                            <div class="text">
                                                <a href="/assets/docy/doc-main.html">
                                                    <p>More Categories</p>
                                                </a>
                                                <a href="/assets/docy/doc-main.html">
                                                    <p>All docs</p>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="v-pills-code" role="tabpanel" aria-labelledby="v-pills-code-tab">
                                            <div class="d-flex">
                                                <ul class="list-unstyled tab_list">
                                                    <li><a href="/assets/docy/doc-element-tab.html">Tabs</a></li>
                                                    <li><a href="/assets/docy/doc-element-accordion.html">Accordion</a></li>
                                                    <li><a href="/assets/docy/doc-element-notice.html">Notice</a></li>
                                                    <li><a href="/assets/docy/doc-content-tables.html">Tables</a></li>
                                                </ul>
                                                <ul class="list-unstyled tab_list">
                                                    <li><a href="/assets/docy/doc-element-hotspots.html">Image Hotspots</a></li>
                                                    <li><a href="/assets/docy/doc-element-code.html">Source Code</a></li>
                                                    <li><a href="/assets/docy/doc-element-lightbox.html">Image Lightbox</a></li>
                                                    <li><a href="/assets/docy/doc-ref-cheatsheet.html">Cheatsheet</a></li>
                                                </ul>
                                            </div>
                                            <div class="text">
                                                <a href="/assets/docy/#">
                                                    <p>More Categories</p>
                                                </a>
                                                <a href="/assets/docy/doc-main.html">
                                                    <p>All docs</p>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="v-pills-layout" role="tabpanel" aria-labelledby="v-pills-layout-tab">
                                            <div class="d-flex">
                                                <ul class="list-unstyled tab_list">
                                                    <li><a href="/assets/docy/doc-element-hotspots.html">Left Sidebar</a></li>
                                                    <li><a href="/assets/docy/doc-content-video.html">Full-width</a></li>
                                                    <li><a href="/assets/docy/doc-layout-banner-gradient.html">Gradient Banner</a></li>
                                                    <li><a href="/assets/docy/doc-layout-banner-empty.html">Without Banner</a></li>
                                                </ul>
                                            </div>
                                            <div class="text">
                                                <a href="/assets/docy/#">
                                                    <p>More Categories</p>
                                                </a>
                                                <a href="/assets/docy/#">
                                                    <p>All docs</p>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="v-pills-tour" role="tabpanel" aria-labelledby="v-pills-tour-tab">
                                            <div class="d-flex">
                                                <ul class="list-unstyled tab_list w_100">
                                                    <li><a href="/assets/docy/doc-ref-cheatsheet.html">Cheatsheet</a></li>
                                                    <li><a href="/assets/docy/doc-ref-footnote.html">Footnotes</a></li>
                                                    <li><a href="/assets/docy/doc-tour.html">Interface Tour</a></li>
                                                    <li><a href="/assets/docy/doc-ref-can-use.html">Can I Use</a></li>
                                                    <li><a href="/assets/docy/doc-content-tooltip.html">Tooltips & Direction</a></li>
                                                    <li><a href="/assets/docy/doc-ref-shortcuts.html">Keyboard Shortcuts</a></li>
                                                </ul>
                                            </div>
                                            <div class="text">
                                                <a href="/assets/docy/#">
                                                    <p>More Categories</p>
                                                </a>
                                                <a href="/assets/docy/#">
                                                    <p>All docs</p>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="v-pills-content" role="tabpanel" aria-labelledby="v-pills-content-tab">
                                            <div class="d-flex">
                                                <ul class="list-unstyled tab_list">
                                                    <li><a href="/assets/docy/doc-content-image.html">Image</a></li>
                                                    <li><a class="active" href="/assets/docy/doc-content-tables.html">Tables</a></li>
                                                    <li><a href="/assets/docy/doc-content-video.html">Video</a></li>
                                                    <li><a href="/assets/docy/typography.html">Typography</a></li>
                                                    <li><a href="/assets/docy/doc-content-tooltip.html">Tooltips & Direction</a></li>
                                                </ul>
                                            </div>
                                            <div class="text">
                                                <a href="/assets/docy/#">
                                                    <p>More Categories</p>
                                                </a>
                                                <a href="/assets/docy/#">
                                                    <p>All docs</p>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="v-pills-pages" role="tabpanel" aria-labelledby="v-pills-pages-tab">
                                            <div class="d-flex">
                                                <ul class="list-unstyled tab_list">
                                                    <li> <a href="/assets/docy/onepage.html">Onepage</a> </li>
                                                    <li> <a href="/assets/docy/doc-main.html">Doc Topics</a></li>
                                                    <li> <a href="/assets/docy/doc-tour.html">Cheatsheet</a> </li>
                                                    <li> <a href="/assets/docy/doc-changelog.html">Changelog</a> </li>
                                                </ul>
                                            </div>
                                            <div class="text">
                                                <a href="/assets/docy/#">
                                                    <p>More Categories</p>
                                                </a>
                                                <a href="/assets/docy/doc-main.html">
                                                    <p>All docs</p>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu">
                    <a class="nav-link dropdown-toggle" href="/assets/docy/#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Pages
                    </a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon" aria-hidden="false" data-toggle="dropdown"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="/assets/docy/onepage.html" class="nav-link">Onepage Doc</a></li>
                        <li class="nav-item"><a href="/assets/docy/contact.html" class="nav-link">Contact</a></li>
                        <li class="nav-item"><a href="/assets/docy/forums.html" class="nav-link">Forum</a></li>
                        <li class="nav-item"><a href="/assets/docy/typography.html" class="nav-link">Typography</a></li>
                        <li class="nav-item"><a href="/assets/docy/404-error.html" class="nav-link">404 Error</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu">
                    <a class="nav-link dropdown-toggle" href="/assets/docy/forums.html" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Forum
                    </a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon" aria-hidden="false"
                       data-toggle="dropdown"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="/assets/docy/forums.html" class="nav-link">Forums Root</a></li>
                        <li class="nav-item active"><a href="/assets/docy/forum-topics.html" class="nav-link">Forum Topics</a></li>
                        <li class="nav-item"><a href="/assets/docy/forum-single.html" class="nav-link">Topic Details</a></li>
                        <li class="nav-item"><a href="/assets/docy/forum-profile.html" class="nav-link">User Profile</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu">
                    <a class="nav-link dropdown-toggle" href="/assets/docy/#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Blog
                    </a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon" aria-hidden="false" data-toggle="dropdown"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="/assets/docy/blog-grid.html" class="nav-link">Blog Grid</a></li>
                        <li class="nav-item"><a href="/assets/docy/blog-grid-two.html" class="nav-link">Blog Grid Two</a></li>
                        <li class="nav-item"><a href="/assets/docy/blog-list.html" class="nav-link">Blog List</a></li>
                        <li class="nav-item"><a href="/assets/docy/blog-single.html" class="nav-link">Blog Details</a></li>
                    </ul>
                </li>
            </ul>
            <div class="right-nav">
                <a class="nav_btn tp_btn" href="/assets/docy/https://is.gd/nDvqm2" target="_blank">Get Docy</a>
                <a class="px-2 ml-3" href="/assets/docy/#" title="Subscribe to the newsletter">
                    <ion-icon name="mail"></ion-icon>
                </a>
                <a class="px-2" href="/assets/docy/#" title="RSS feed">
                    <ion-icon name="logo-rss"></ion-icon>
                </a>
                <div class="px-2 js-darkmode-btn" title="Toggle dark mode">
                    <label for="something" class="tab-btn tab-btns">
                        <ion-icon class="light-mode" name="contrast"></ion-icon>
                    </label>
                    <input type="checkbox" name="something" id="something" class="dark_mode_switcher">
                    <label for="something" class="tab-btn">
                        <ion-icon class="dark-mode" name="contrast-outline"></ion-icon>
                    </label>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="breadcrumb_area_three">
    <div class="container">
        <div class="breadcrumb_text">
            <h2> Check out our <span>Guide</span></h2>
            <p>Docy is here to help. Discover our office locations and different ways to contact us so that we can provide you with the support you need.</p>
        </div>
    </div>
</div>

<section class="doc_categories_guide_area sec_pad">
    <img class="shap wow fadeInUp" src="/assets/docy/img/home_one/dow_bg_two.png" alt="">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <div class="categories_guide_item wow fadeInUp">
                    <img src="/assets/docy/img/home_two/folder.png" alt="">
                    <div class="doc_tag_title">
                        <h4>Getting Started</h4>
                    </div>
                    <ul class="list-unstyled tag_list">
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Setup home page layout</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>BBpress sidebar layout styles</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Knowledgebase page setup</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Creating home page blocks</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do i add FAQ post</a></li>
                    </ul>
                    <a href="/assets/docy/#" class="doc_border_btn">More<i class="arrow_right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="categories_guide_item wow fadeInUp" data-wow-delay="0.2s">
                    <img src="/assets/docy/img/home_two/info.png" alt="">
                    <div class="doc_tag_title">
                        <h4>Integrations</h4>
                    </div>
                    <ul class="list-unstyled tag_list">
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How To Install Manual Theme</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Theme license information</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do i create tree structure menu</a>
                        </li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do I login forum section</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do I login forum section</a></li>
                    </ul>
                    <a href="/assets/docy/#" class="doc_border_btn">More<i class="arrow_right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="categories_guide_item wow fadeInUp" data-wow-delay="0.4s">
                    <img src="/assets/docy/img/home_two/weather.png" alt="">
                    <div class="doc_tag_title">
                        <h4>Cloud Server</h4>
                    </div>
                    <ul class="list-unstyled tag_list">
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Mailbox and User Settings</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Preparing your server for installation</a>
                        </li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Managing Docs in Docy</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do i add FAQ post</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Creating home page blocks</a></li>
                    </ul>
                    <a href="/assets/docy/#" class="doc_border_btn">More<i class="arrow_right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="categories_guide_item wow fadeInUp">
                    <img src="/assets/docy/img/home_two/settings.png" alt="">
                    <div class="doc_tag_title">
                        <h4>User Settings</h4>
                    </div>
                    <ul class="list-unstyled tag_list">
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Do I need to know coding</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Managing Docs in Docy</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Working with Conversations</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Copying Email to Docy</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Knowledgebase page setup</a></li>
                    </ul>
                    <a href="/assets/docy/#" class="doc_border_btn">More<i class="arrow_right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="categories_guide_item wow fadeInUp" data-wow-delay="0.4s">
                    <img src="/assets/docy/img/home_two/memo.png" alt="">
                    <div class="doc_tag_title">
                        <h4>Reporting</h4>
                    </div>
                    <ul class="list-unstyled tag_list">
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Setup home page layout</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>BBpress sidebar layout styles</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Knowledgebase page setup</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Creating home page blocks</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do i add FAQ post</a></li>
                    </ul>
                    <a href="/assets/docy/#" class="doc_border_btn">More<i class="arrow_right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="categories_guide_item wow fadeInUp" data-wow-delay="0.6s">
                    <img src="/assets/docy/img/home_two/share.png" alt="">
                    <div class="doc_tag_title">
                        <h4>Solar System</h4>
                    </div>
                    <ul class="list-unstyled tag_list">
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do I contact Customer Care?</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How to enable labs features</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Knowledgebase page setup</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>How do I login forum section</a></li>
                        <li><a href="/assets/docy/#"><i class="icon_document_alt"></i>Mailbox and User Settings</a></li>
                    </ul>
                    <a href="/assets/docy/#" class="doc_border_btn">More<i class="arrow_right"></i></a>
                </div>
            </div>
        </div>
        <div class="text-center">
            <a href="/assets/docy/#" class="doc_border_btn all_doc_btn wow fadeinUp">View All Docs<i class="arrow_right"></i></a>
        </div>
    </div>
</section>

<section class="recommended_topic_area">
    <div class="container">
        <div class="recommended_topic_inner">
            <img class="doc_shap_one" src="/assets/docy/img/new/shap.png" alt="">
            <div class="doc_round one" data-parallax='{"x": -80, "y": -100, "rotateY":0}'></div>
            <div class="doc_round two" data-parallax='{"x": -10, "y": 70, "rotateY":0}'></div>
            <div class="doc_title text-center">
                <h2 class="wow fadeInUp" data-wow-delay="0.2s">Recommended Topics</h2>
                <p class="wow fadeInUp" data-wow-delay="0.4s">Loaded with awesome features like Documentation,
                    Knowledgebase,<br> Forum & more!</p>
            </div>
            <div class="row">
                <div class="col-lg-3 col-6">
                    <div class="recommended_item wow fadeInUp" data-wow-delay="0.2s">
                        <img src="/assets/docy/img/new/smile.png" alt="">
                        <a href="/assets/docy/#">
                            <h3>Getting Started</h3>
                        </a>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#">Welcome to Ghost</a></li>
                            <li><a href="/assets/docy/#">Writing posts with Ghost</a></li>
                            <li><a href="/assets/docy/#">Publishing options</a></li>
                            <li><a href="/assets/docy/#">Managing admin settings</a></li>
                            <li><a href="/assets/docy/#">Organising your content</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="recommended_item wow fadeInUp" data-wow-delay="0.3s">
                        <img src="/assets/docy/img/new/house.png" alt="">
                        <a href="/assets/docy/#">
                            <h3>Advanced Usage</h3>
                        </a>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#">Getting started</a></li>
                            <li><a href="/assets/docy/#">Become a Pro</a></li>
                            <li><a href="/assets/docy/#">Admin & Billing</a></li>
                            <li><a href="/assets/docy/#">Mobile App</a></li>
                            <li><a href="/assets/docy/#">Guides</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="recommended_item wow fadeInUp" data-wow-delay="0.4s">
                        <img src="/assets/docy/img/new/doc.png" alt="">
                        <a href="/assets/docy/#">
                            <h3>Knowledge Base</h3>
                        </a>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#">Organising content in Ghost</a></li>
                            <li><a href="/assets/docy/#">Using the editor</a></li>
                            <li><a href="/assets/docy/#">General publication settings</a></li>
                            <li><a href="/assets/docy/#">Publishing Options</a></li>
                            <li><a href="/assets/docy/#">Knowledge Base</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <div class="recommended_item wow fadeInUp" data-wow-delay="0.5s">
                        <img src="/assets/docy/img/new/bag.png" alt="">
                        <a href="/assets/docy/#">
                            <h3>User Settings</h3>
                        </a>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#">How do I reset my password</a></li>
                            <li><a href="/assets/docy/#">Managing your team</a></li>
                            <li><a href="/assets/docy/#">Can I add my social accounts</a></li>
                            <li><a href="/assets/docy/#">Imports and exports</a></li>
                            <li><a href="/assets/docy/#">Design Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="text-center wow fadeInUp" data-wow-delay="0.2s">
                <a href="/assets/docy/#" class="question_text">Want to know more or have a<br> Question?
                </a>
            </div>
        </div>
    </div>
</section>

<footer class="doc_footer_area">
    <div class="doc_footer_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="f_widget doc_about_widget wow fadeInUp" data-wow-delay="0.2s">
                        <a href="/assets/docy/#">
                            <img src="/assets/docy/img/logo.png" srcset="/assets/docy/img/logo-2x.png 2x" alt="">
                        </a>
                        <p>I’m available for commissions and collaborations, and i’m excited to hear from you
                            about
                            new projects.!!</p>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#"><i class="social_facebook"></i></a></li>
                            <li><a href="/assets/docy/#"><i class="social_twitter"></i></a></li>
                            <li><a href="/assets/docy/#"><i class="social_vimeo"></i></a></li>
                            <li><a href="/assets/docy/#"><i class="social_linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6">
                    <div class="f_widget doc_service_list_widget pl-30 wow fadeInUp" data-wow-delay="0.3s">
                        <h3 class="f_title_two">Solutions</h3>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#"><img src="/assets/docy/img/new/smile2.png" alt="">Help Docs</a></li>
                            <li><a href="/assets/docy/#"><img src="/assets/docy/img/new/doc2.png" alt="">Docbuzz</a></li>
                            <li><a href="/assets/docy/#"><img src="/assets/docy/img/new/house2.png" alt="">User Frontend</a></li>
                            <li><a href="/assets/docy/#"><img src="/assets/docy/img/new/bag2.png" alt="">Lightbox</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="f_widget doc_service_list_widget pl-100 wow fadeInUp" data-wow-delay="0.4s">
                        <h3 class="f_title_two">Support</h3>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#">Help Desk</a></li>
                            <li><a href="/assets/docy/#">Knowledge Base</a></li>
                            <li><a href="/assets/docy/#">Live Chat</a></li>
                            <li><a href="/assets/docy/#">Integrations</a></li>
                            <li><a href="/assets/docy/#">Reports</a></li>
                            <li><a href="/assets/docy/#">Messages</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="f_widget doc_service_list_widget pl-70 wow fadeInUp" data-wow-delay="0.5s">
                        <h3 class="f_title_two">Company</h3>
                        <ul class="list-unstyled">
                            <li><a href="/assets/docy/#">About Us</a></li>
                            <li><a href="/assets/docy/#">Testimonials</a></li>
                            <li><a href="/assets/docy/#">Affiliates</a></li>
                            <li><a href="/assets/docy/#">Partners</a></li>
                            <li><a href="/assets/docy/#">Careers</a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="doc_footer_bottom">
        <div class="container d-flex justify-content-between">
            <ul class="doc_footer_menu list-unstyled wow fadeInUp" data-wow-delay="0.2s">
                <li><a href="/assets/docy/#">Blog</a></li>
                <li><a href="/assets/docy/#">Latest Projects</a></li>

            </ul>
            <p class="wow fadeInUp" data-wow-delay="0.3s">© 2021 All Rights Reserved Design by
                <span>Spider-themes</span>
            </p>
        </div>
    </div>
</footer>
