<?php echo $this->partial( 'docnav.phtml' ); ?>

<div class="mobile_main_menu dark_menu sticky-nav ">
    <div class="container">
        <div class="mobile_menu_left">
            <button type="button" class="navbar-toggler mobile_menu_btn">
                    <span class="menu_toggle ">
                        <span class="hamburger">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </span>
            </button>
            <a class="navbar-brand header_logo" href="index.html">
                <img class="sticky_logo main_logo" src="/assets/docy/img/logo.png" srcset="/assets/docy/img/logo-2x.png 2x" alt="logo">
                <img class="white_logo" src="/assets/docy/img/logo-w.png" srcset="/assets/docy/img/logo-w2x.png 2x" alt="logo">
            </a>
        </div>
        <div class="mobile_menu_right">
            <div class="right-nav">
                <a class="nav_btn tp_btn" href="https://is.gd/nDvqm2" target="_blank">Get Docy</a>
                <a class="px-2 ml-3" href="#" title="Subscribe to the newsletter">
                    <ion-icon name="mail"></ion-icon>
                </a>
                <a class="px-2" href="#" title="RSS feed">
                    <ion-icon name="logo-rss"></ion-icon>
                </a>
                <div class="px-2 js-darkmode-btn btn" title="Toggle dark mode">
                    <label for="something2" class="tab-btn tab-btns">
                        <ion-icon class="light-mode" name="contrast"></ion-icon>
                    </label>
                    <input type="checkbox" name="something2" id="something2" class="dark_mode_switcher">
                    <label for="something2" class="tab-btn">
                        <ion-icon class="dark-mode" name="contrast-outline"></ion-icon>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="click_capture"></div>
<div class="side_menu">
    <div class="mobile_menu_header">
        <div class="close_nav">
            <i class="arrow_left"></i>
            <i class="icon_close"></i>
        </div>
        <div class="mobile_logo">
            <a class="navbar-brand header_logo" href="index.html">
                <img class="sticky_logo main_logo" src="/assets/docy/img/logo.png" srcset="/assets/docy/img/logo-2x.png 2x" alt="logo">
                <img class="white_logo" src="/assets/docy/img/logo-w.png" srcset="/assets/docy/img/logo-w2x.png 2x" alt="logo">
            </a>
        </div>
    </div>
    <div class="mobile_nav_wrapper">
        <nav class="mobile_nav_top">
            <ul class="navbar-nav menu ml-auto">
                <li class="nav-item dropdown submenu">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item dropdown submenu active">
                    <a href="#" class="nav-link">Docs</a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="doc-content-video.html" class="nav-link">Doc Archives</a></li>
                        <li class="nav-item"><a href="doc-main.html" class="nav-link">DocTopics</a></li>
                        <li class="nav-item dropdown submenu">
                            <a href="#" class="nav-link">Elements</a>
                            <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="doc-element-tab.html" class="nav-link">Tabs</a></li>
                                <li class="nav-item"><a href="doc-element-accordion.html" class="nav-link">Accordion</a></li>
                                <li class="nav-item"><a href="doc-element-notice.html" class="nav-link">Notices</a></li>
                                <li class="nav-item"><a href="doc-content-tables.html" class="nav-link">Tables</a></li>
                                <li class="nav-item"><a href="doc-content-tooltip.html" class="nav-link">Tooltips & Direction</a></li>
                                <li class="nav-item"><a href="doc-element-hotspots.html" class="nav-link">Image Hotspots</a></li>
                                <li class="nav-item"><a href="doc-element-lightbox.html" class="nav-link">Lightbox</a></li>
                                <li class="nav-item"><a href="doc-changelog.html" class="nav-link">Changelog</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a href="#" class="nav-link">Layouts</a>
                            <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="doc-element-hotspots.html" class="nav-link">Left Sidebar</a></li>
                                <li class="nav-item"><a href="doc-content-video.html" class="nav-link">Full-width</a></li>
                                <li class="nav-item"><a href="doc-layout-banner-gradient.html" class="nav-link">Gradient Banner</a></li>
                                <li class="nav-item"><a href="doc-layout-banner-empty.html" class="nav-link">Without Banner</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu">
                    <a href="#" class="nav-link">Pages</a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="onepage.html" class="nav-link">Onepage Doc</a></li>
                        <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                        <li class="nav-item"><a href="onepage.html" class="nav-link">Onepage Doc</a></li>
                        <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                        <li class="nav-item"><a href="typography.html" class="nav-link">Typography</a></li>
                        <li class="nav-item"><a href="404-error.html" class="nav-link">404 Error</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu">
                    <a href="#" class="nav-link">Forum</a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="forums.html" class="nav-link">Forums Root</a></li>
                        <li class="nav-item"><a href="forum-topics.html" class="nav-link">Forum Topics</a></li>
                        <li class="nav-item"><a href="forum-single.html" class="nav-link">Topic Details</a></li>
                        <li class="nav-item"><a href="forum-profile.html" class="nav-link">User Profile</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown submenu">
                    <a class="nav-link" href="#"> Blog </a>
                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="blog-grid.html" class="nav-link">Blog Grid</a></li>
                        <li class="nav-item"><a href="blog-grid-two.html" class="nav-link">Blog Grid Two</a></li>
                        <li class="nav-item"><a href="blog-list.html" class="nav-link">Blog List</a></li>
                        <li class="nav-item"><a href="blog-single.html" class="nav-link">Blog Details</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div class="mobile_nav_bottom">
            <aside class="doc_left_sidebarlist">
                <h2>Docy Documentation</h2>
                <div class="scroll">
                    <ul class="list-unstyled nav-sidebar">
                        <li class="nav-item">
                            <a href="doc-main.html" class="nav-link"><img src="/assets/docy/img/side-nav/home.png" alt="">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a href="doc-element-tab.html" class="nav-link"><img src="/assets/docy/img/side-nav/briefcase.png" alt="briefcase">Elements</a>
                            <span class="icon"><i class="arrow_carrot-down"></i></span>
                            <ul class="list-unstyled dropdown_nav">
                                <li><a href="doc-element-tab.html">Tabs</a></li>
                                <li><a href="doc-element-accordion.html">Accordion</a></li>
                                <li><a href="doc-element-notice.html">Notices</a></li>
                                <li><a href="doc-content-tables.html">Table</a></li>
                                <li><a href="doc-element-lightbox.html">Image Lightbox</a></li>
                                <li><a href="doc-element-hotspots.html">Image Hotspots</a></li>
                                <li><a class="active" href="doc-element-code.html">Source Code</a></li>
                                <li><a href="doc-content-tooltip.html">Tooltip</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="doc-content-video.html" class="nav-link"><img src="/assets/docy/img/side-nav/layout.png" alt="">Layouts</a>
                            <span class="icon"><i class="arrow_carrot-down"></i></span>
                            <ul class="list-unstyled dropdown_nav">
                                <li><a href="doc-content-video.html">Full-width</a></li>
                                <li><a href="doc-element-hotspots.html">Left Sidebar</a></li>
                                <li><a href="doc-layout-banner-gradient.html">Gradient Banner</a></li>
                                <li><a href="doc-layout-banner-empty.html">Without Banner</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="doc-ref-cheatsheet.html" class="nav-link"><img src="/assets/docy/img/side-nav/chat1.png" alt="">Reference</a>
                            <span class="icon"><i class="arrow_carrot-down"></i></span>
                            <ul class="list-unstyled dropdown_nav">
                                <li><a href="doc-ref-cheatsheet.html">Cheatsheet</a></li>
                                <li><a href="doc-ref-footnote.html">Footnotes</a></li>
                                <li><a href="doc-tour.html">Interface Tour</a></li>
                                <li><a href="doc-ref-can-use.html">Can I Use</a></li>
                                <li><a href="doc-content-tooltip.html">Tooltips & Direction</a></li>
                                <li><a href="doc-ref-shortcuts.html">Keyboard Shortcuts</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="doc-content-image.html" class="nav-link"><img src="/assets/docy/img/side-nav/document.png" alt="">Content</a>
                            <span class="icon"><i class="arrow_carrot-down"></i></span>
                            <ul class="list-unstyled dropdown_nav">
                                <li><a href="doc-content-image.html">Image</a></li>
                                <li><a class="active" href="doc-content-tables.html">Tables</a></li>
                                <li><a href="doc-content-tooltip.html">Tooltips & Direction</a></li>
                                <li><a href="doc-element-code.html">Code</a></li>
                                <li><a href="doc-content-video.html">Video</a></li>
                                <li><a href="typography.html">Typography</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="doc-changelog.html" class="nav-link"><img src="/assets/docy/img/side-nav/clock.png" alt="">Change Log</a>
                        </li>
                    </ul>
                    <ul class="list-unstyled nav-sidebar coding_nav">
                        <li class="nav-item">
                            <a href="#" class="nav-link"><img src="/assets/docy/img/side-nav/account.png" alt="">Account</a>
                        </li>
                        <li class="nav-item">
                            <a href="onepage.html" class="nav-link"><img src="/assets/docy/img/side-nav/layout.png" alt="">Onepage Doc</a>
                        </li>
                    </ul>
                    <ul class="list-unstyled nav-sidebar bottom_nav">
                        <li class="nav-item">
                            <a href="#" class="nav-link"><img src="/assets/docy/img/side-nav/united-states.png" alt="">United States</a>
                        </li>
                        <li class="nav-item">
                            <a href="signup.html" class="nav-link"><img src="/assets/docy/img/side-nav/edit.png" alt="">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a href="signin.html" class="nav-link"><img src="/assets/docy/img/side-nav/users.png" alt="">Sign In <i class="arrow_right"></i></a>
                        </li>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</div>

<!--================Forum Breadcrumb Area =================-->
<section class="doc_banner_area search-banner-light">
    <ul class="list-unstyled banner_shap_img">
        <li><img src="/assets/docy/img/forum/breadcrumb/forum-illustration.png" alt=""></li>
        <li><img src="/assets/docy/img/forum/breadcrumb/forum-illustration-2.png" alt=""></li>
    </ul>
    <div class="container">
        <div class="doc_banner_content">
            <form action="#" class="header_search_form">
                <div class="header_search_form_info">
                    <div class="form-group">
                        <div class="input-wrapper">
                            <i class="icon_search"></i>
                            <input type='search' id="searchbox" autocomplete="off" name="search"
                                   placeholder="Search for Topics...." />
                            <div class="header_search_form_panel">
                                <ul class="list-unstyled">
                                    <li>Help Desk
                                        <ul class="list-unstyled search_item">
                                            <li><span>Configuration</span><a href="#">How to edit host and
                                                    port?</a></li>
                                            <li><span>Configuration</span><a href="#">The dev Property</a></li>
                                        </ul>
                                    </li>
                                    <li>Support
                                        <ul class="list-unstyled search_item">
                                            <li><span>Pages</span><a href="#">The asyncData Method</a></li>
                                        </ul>
                                    </li>
                                    <li>Documentation
                                        <ul class="list-unstyled search_item">
                                            <li><span>Getting Started</span><a href="#">The asyncData Method</a>
                                            </li>
                                            <li><span>Getting Started</span><a href="#">The asyncData Method</a>
                                            </li>
                                            <li><span>Getting Started</span><a href="#">The asyncData Method</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header_search_keyword">
                    <span class="header-search-form__keywords-label">Popular Searches:</span>
                    <ul class="list-unstyled">
                        <li class="wow fadeInUp" data-wow-delay="0.2s"><a href="#">Docy Documentation</a>,</li>
                        <li class="wow fadeInUp" data-wow-delay="0.3s"><a href="#">Tabs Widget</a>,</li>
                        <li class="wow fadeInUp" data-wow-delay="0.4s"><a href="#">Process Tab</a></li>
                    </ul>
                </div>
            </form>
        </div>
    </div>
</section>
<section class="page_breadcrumb">
    <div class="container custom_container">
        <div class="row">
            <div class="col-sm-7">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Docs</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Docy WordPress Theme</li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-5">
                <a href="#" class="date"><i class="icon_clock_alt"></i>Updated on March 03, 2020</a>
            </div>
        </div>
    </div>
</section>
<!--================End Forum Breadcrumb Area =================-->

<!--================ Begin Topic Area ===============-->
<?php echo $this->partial( 'doctopic.phtml' ); ?>
<!--================ End Topic Area =================-->

<!--================ Begin Footer =============-->
<?php echo $this->partial( 'docfooter.phtml' ); ?>
<!--================ End Footer ===============-->
