<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

        <title><?php echo $this->one->title; ?></title>

        <meta name="description" content="<?php echo $this->one->description; ?>">
        <meta name="author" content="<?php echo $this->one->author; ?>">
        <meta name="robots" content="<?php echo $this->one->robots; ?>">

        <!-- Open Graph Meta -->
        <meta property="og:title" content="<?php echo $this->one->title; ?>">
        <meta property="og:site_name" content="<?php echo $this->one->name; ?>">
        <meta property="og:description" content="<?php echo $this->one->description; ?>">
        <meta property="og:type" content="website">
        <meta property="og:url" content="<?php echo $this->one->og_url_site; ?>">
        <meta property="og:image" content="<?php echo $this->one->og_url_image; ?>">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="<?php echo $this->one->assets_folder; ?>/media/favicons/favicon.png">
        <link rel="icon" type="image/png" sizes="192x192" href="<?php echo $this->one->assets_folder; ?>/media/favicons/favicon-192x192.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->one->assets_folder; ?>/media/favicons/apple-touch-icon-180x180.png">
        <!-- END Icons -->

        <!-- Stylesheets -->

        <!-- Fonts and OneUI framework -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,600,700%7COpen+Sans:300,400,400italic,600,700">
        <link rel="stylesheet" id="css-main" href="<?php echo $this->one->assets_folder; ?>/css/oneui.min.css">

        <!-- You can include a specific file from css/themes/ folder to alter the default color theme of the template. eg: -->
        <!-- <link rel="stylesheet" id="css-theme" href="assets/css/themes/amethyst.min.css"> -->
        <?php if ($this->one->theme) { ?>
            <link rel="stylesheet" id="css-theme" href="<?php echo $this->one->assets_folder; ?>/css/themes/<?php echo $one->theme; ?>.min.css">
        <?php } ?>
        <!-- END Stylesheets -->
    </head>
    <body>

        <?php echo $this->layout()->content; ?>

        <!--
        OneUI JS Core

        Vital libraries and plugins used in all pages. You can choose to not include this file if you would like
        to handle those dependencies through webpack. Please check out assets/_es6/main/bootstrap.js for more info.

        If you like, you could also include them separately directly from the assets/js/core folder in the following
        order. That can come in handy if you would like to include a few of them (eg jQuery) from a CDN.

        assets/js/core/jquery.min.js
        assets/js/core/bootstrap.bundle.min.js
        assets/js/core/simplebar.min.js
        assets/js/core/jquery-scrollLock.min.js
        assets/js/core/jquery.appear.min.js
        assets/js/core/js.cookie.min.js
        -->
        <script src="<?php echo $this->one->assets_folder; ?>/js/oneui.core.min.js"></script>

        <!--
        OneUI JS

        Custom functionality including Blocks/Layout API as well as other vital and optional helpers
        webpack is putting everything together at assets/_es6/main/app.js
        -->
        <script src="<?php echo $this->one->assets_folder; ?>/js/oneui.app.min.js"></script>

    </body>
</html>
