<!-- User Form -->
<form id="avatar-form" name="<?php echo $this->avatarForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <div id="change-message" class="hide">
        <div class="alert alert-info"><i class="fa fa-info-circle"></i> &nbsp;<?php echo $this->translate('MESSAGE.AVATAR_CHANGED'); ?></div>
    </div>

    <div class="block">
        <h4><?php echo $this->translate('AVATAR.SELECT_AVATAR'); ?></h4>

        <p><?php echo $this->translate('AVATAR.TEXT_1'); ?></p>

        <div class="row row-deck">
            <div class="col-lg-12">
                <div class="block">

                    <div id="upload-zone-container">
                        <div class="block-content block-content-full">
                            <div id="upload-zone" style="width: 100%; min-height: 100px;" class="">
                                <div class="dz-message"><?php echo $this->translate('AVATAR.DROP_FILES_HERE'); ?></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="row row-deck">
            <div class="col-lg-12">
                <div class="block">

                    <div id="media-gallery-container">
                        <div class="block-content block-content-full">

                            <!-- Advanced Gallery -->
                            <div id="gallery" class="row gutters-tiny items-push js-gallery push">
                                <div class="col-md-6 col-lg-4 col-xl-3 avatar-container default">
                                    <div class="animated fadeIn">
                                        <div class="options-container fx-item-zoom-in">
                                            <img class="img-fluid options-item" src="/assets/oneui/media/avatars/avatar10.jpg" alt="" title="" id="1b1bad96-beb6-11eb-9954-160bcf4d03cd" data-extension="png">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- END Advanced Gallery -->

                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

</form>
<!-- END Avatar Form -->
