<!-- Page Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo34@2x.jpg');">
    <div class="hero-static bg-black-50">
        <div class="content">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <!-- Unlock Block -->
                    <div class="block block-themed mb-0">
                        <div class="block-header bg-danger">
                            <h3 class="block-title"><?php echo $this->translate('LOCK.ACCOUNT_LOCKED') ?></h3>
                            <div class="block-options">
                                <a class="btn-block-option" href="/login" data-toggle="tooltip" data-placement="left" title="<?php echo $this->translate('LOCK.SIGNIN_DIFFERENT_ACCOUNT') ?>">
                                    <i class="fa fa-sign-in-alt"></i>
                                </a>
                            </div>
                        </div>
                        <div class="block-content">
                            <div class="p-sm-3 px-lg-4 py-lg-5 text-center">
                                <img class="img-avatar img-avatar96" src="<?php echo $this->template->assets_folder; ?>/media/avatars/avatar10.jpg" alt="">
                                <p class="font-w600 my-2">
                                    <?php echo $this->loginForm->getElement('username')->getValue(); ?>
                                </p>

                                <!-- Unlock Form -->
                                <form id="page-login-form" name="<?php echo $this->loginForm->getName(); ?>" novalidate="novalidate">
                                    <div class="form-message"></div>
                                    <div class="form-group hide">
                                        <?php echo $this->loginForm->username; ?>
                                    </div>
                                    <div class="form-group">
                                        <?php echo $this->loginForm->password; ?>
                                    </div>
                                    <div class="form-group row justify-content-center">
                                        <div class="col-md-6 col-xl-5">
                                            <button id="login-button" type="button" class="btn btn-block btn-primary">
                                                <i class="fa fa-fw fa-lock-open mr-1"></i> <?php echo $this->translate('LOCK.LOGIN') ?>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                                <!-- END Unlock Form -->
                            </div>
                        </div>
                    </div>
                    <!-- END Unlock Block -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-white text-center">
            <strong><?php echo $this->template->name . ' ' . $this->template->version; ?></strong> &copy; <span data-toggle="year-copy"></span>
        </div>
    </div>
</div>
<!-- END Page Content -->
