<?php echo $this->partial('account/hero.phtml', ['template' => $this->template]); ?>

<!-- Page Content -->
<div class="content content-boxed">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>

    <div class="block">

        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-user"><?php echo $this->translate('TAB.USER_PROFILE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-password"><?php echo $this->translate('TAB.PASSWORD'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-user-address"><?php echo $this->translate('TAB.USER_ADDRESSES'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-user-contact"><?php echo $this->translate('TAB.USER_CONTACTS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-org"><?php echo $this->translate('TAB.ORG'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-org-address"><?php echo $this->translate('TAB.ORG_ADDRESSES'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-org-contact"><?php echo $this->translate('TAB.ORG_CONTACTS'); ?></a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-user" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.USER_PROFILE'); ?></h4>
                <form id="user-form-profile" name="<?php echo $this->userForm->getName(); ?>" onsubmit="return false;">
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted"><?php echo $this->translate('TEXT.USER_PROFILE'); ?></p>
                            <div class="text-center">
                                <?php $this->template->get_avatar(); ?>
                            </div>
                            <div class="text-center">
                                <button id="select-avatar" type="button" class="btn btn-alt-light">Select Avatar</button>
                            </div>
                        </div>
                        <div class="col-lg-8 col-xl-5">
                            <div class="hide">
                                <?php echo $this->userForm->user_id; ?>
                                <?php echo $this->userForm->avatar_url; ?>
                            </div>
                            <div class="form-group">
                                <label for="username"><?php echo $this->userForm->username->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->username->getDescription(); ?>"></i>
                                <?php echo $this->userForm->username; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="email"><?php echo $this->userForm->email->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->email->getDescription(); ?>"></i>
                                <?php echo $this->userForm->email; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="user_display_name"><?php echo $this->userForm->user_display_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->user_display_name->getDescription(); ?>"></i>
                                <?php echo $this->userForm->user_display_name; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="type_title"><?php echo $this->userForm->type_title->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->type_title->getDescription(); ?>"></i>
                                <?php echo $this->userForm->type_title; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="first_name"><?php echo $this->userForm->first_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->first_name->getDescription(); ?>"></i>
                                <?php echo $this->userForm->first_name; ?>
                                <div class="message-container"></div>
                            </div>
                            <!-- Unhide if you need to collect a middle name. -->
                            <div class="form-group hide">
                                <label for="middle_name"><?php echo $this->userForm->middle_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->middle_name->getDescription(); ?>"></i>
                                <?php echo $this->userForm->middle_name; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="last_name"><?php echo $this->userForm->last_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->last_name->getDescription(); ?>"></i>
                                <?php echo $this->userForm->last_name; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="type_suffix"><?php echo $this->userForm->type_suffix->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->type_suffix->getDescription(); ?>"></i>
                                <?php echo $this->userForm->type_suffix; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="company_title"><?php echo $this->userForm->company_title->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->company_title->getDescription(); ?>"></i>
                                <?php echo $this->userForm->company_title; ?>
                                <div class="message-container"></div>
                            </div>

                            <div class="form-group">
                                <button id="save-user-button" type="button" class="btn btn-alt-success float-right">
                                    <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                    <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                </button>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-password" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.CHANGE_PASSWORD'); ?></h4>
                <form id="user-form-password" name="<?php echo $this->userForm->getName(); ?>" onsubmit="return false;">
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted">
                                <?php echo $this->translate('TEXT.PASSWORD'); ?>
                            </p>
                        </div>
                        <div class="col-lg-8 col-xl-5">
                            <div class="form-group">
                                <label for="current_password"><?php echo $this->userForm->current_password->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->userForm->current_password->getDescription(); ?>"></i>
                                <?php echo $this->userForm->current_password; ?>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <label for="password"><?php echo $this->translate('LABEL.NEW_PASSWORD'); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                   title="<?php echo $this->translate('DESCRIPTION.USER_PASSWORD'); ?>"></i>
                                <?php $this->userForm->password->setAttrib('placeholder',''); ?>
                                <?php echo $this->userForm->password; ?>
                                <div class="password-html" style="overflow: hidden; height: 0px;">
                                    <?php echo $this->userForm->password->getDescription(); ?>
                                </div>
                                <div class="message-container"></div>
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                    <button id="save-password-button" type="button" class="btn btn-alt-success">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-user-address" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.USER_ADDRESSES'); ?></h4>
                <form id="user-form-address" name="<?php echo $this->addressForm->getName(); ?>" onsubmit="return false;">
                    <div class="hide">
                        <?php $this->addressForm->entity->setValue('user'); ?>
                        <?php echo $this->addressForm->entity; ?>
                    </div>
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted"><?php echo $this->translate( 'TEXT.USER_ADDRESS' ); ?></p>
                        </div>
                        <div class="col-lg-8 col-xl-5">

                            <div class="form-group">
                                <label for="address_id"><?php echo $this->addressForm->address_id->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->addressForm->address_id->getDescription(); ?>"></i>
                                <?php echo $this->addressForm->address_id; ?>
                                <div class="message-container"></div>
                            </div>

                            <hr />

                            <div class="overlay-container">

                                <h4><?php echo $this->translate('TITLE.ADDRESS'); ?></h4>

                                <div class="row">
                                    <div class="col-md-8">

                                        <div class="form-group">
                                            <label for="type_address"><?php echo $this->addressForm->type_address->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->type_address->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->type_address; ?>
                                            <div class="message-container"></div>
                                        </div>

                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">

                                            <div class="custom-control custom-switch">
                                                <?php $this->addressForm->primary->setAttrib('id', 'user_primary_address'); ?>
                                                <?php echo $this->addressForm->primary; ?>
                                                <label class="custom-control-label font-w400 primary-address" for="user_primary_address"><?php echo $this->addressForm->primary->getLabel(); ?></label>
                                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                                   title="<?php echo $this->addressForm->primary->getDescription(); ?>"></i>
                                            </div>
                                            <div class="message-container"></div>
                                        </div>

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="address"><?php echo $this->addressForm->address->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->address->getDescription(); ?>"></i>
                                    <div class="overflow-auto">
                                        <?php echo $this->addressForm->address; ?>
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 address-lookup-spinner hide"></i>
                                    </div>
                                    <div class="message-container"></div>
                                    <div id="select-address-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="address2"><?php echo $this->addressForm->address2->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->address2->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->address2; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="city"><?php echo $this->addressForm->city->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->city->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->city; ?>
                                    <div class="message-container"></div>
                                </div>
                                <!-- Un-hide if you need county info -->
                                <div class="form-group hide">
                                    <label for="county"><?php echo $this->addressForm->county->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->county->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->county; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="state"><?php echo $this->addressForm->state->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->state->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->state; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="postal_code"><?php echo $this->addressForm->postal_code->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->postal_code->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->postal_code; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="country"><?php echo $this->addressForm->country->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->country->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->country; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="lat"><?php echo $this->addressForm->lat->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->lat->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->lat; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="lng"><?php echo $this->addressForm->lng->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->lng->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->lng; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group text-right overflow-auto">
                                    <button id="save-user-address-button" type="button" class="btn btn-alt-success float-right">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                    </button>
                                    <button id="remove-user-address-button" type="button" class="btn btn-alt-danger float-left">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-trash mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.REMOVE' ); ?>
                                    </button>
                                </div>

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-user-contact" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.USER_CONTACTS'); ?></h4>
                <form id="user-form-contact" name="<?php echo $this->contactForm->getName(); ?>" onsubmit="return false;">
                    <div class="hide">
                        <?php $this->contactForm->entity->setValue('user'); ?>
                        <?php echo $this->contactForm->entity; ?>
                    </div>
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted"><?php echo $this->translate( 'TEXT.USER_CONTACTS' ); ?></p>
                        </div>
                        <div class="col-lg-8 col-xl-5">

                            <div class="form-group">
                                <label for="contact_id"><?php echo $this->contactForm->contact_id->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->contactForm->contact_id->getDescription(); ?>"></i>
                                <?php echo $this->contactForm->contact_id; ?>
                                <div class="message-container"></div>
                            </div>

                            <hr />

                            <div class="overlay-container">

                                <h4><?php echo $this->translate('TITLE.ADDRESS'); ?></h4>

                                <div class="form-group">
                                    <div class="custom-control custom-switch">
                                        <?php $this->contactForm->primary->setAttrib('id', 'user_primary_contact'); ?>
                                        <?php echo $this->contactForm->primary; ?>
                                        <label class="custom-control-label font-w400 primary-address" for="user_primary_contact"><?php echo $this->contactForm->primary->getLabel(); ?></label>
                                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                           title="<?php echo $this->contactForm->primary->getDescription(); ?>"></i>
                                    </div>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group">
                                    <label for="type_contact"><?php echo $this->contactForm->type_contact->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->contactForm->type_contact->getDescription(); ?>"></i>
                                    <?php echo $this->contactForm->type_contact; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group">
                                    <label for="contact_value"><?php echo $this->contactForm->contact_value->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->contactForm->contact_value->getDescription(); ?>"></i>
                                    <?php echo $this->contactForm->contact_value; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group text-right overflow-auto">
                                    <button id="save-user-contact-button" type="button" class="btn btn-alt-success float-right">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                    </button>
                                    <button id="remove-user-contact-button" type="button" class="btn btn-alt-danger float-left">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-trash mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.REMOVE' ); ?>
                                    </button>
                                </div>

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-org" role="tabpanel">

                <h4><?php echo $this->translate('TITLE.ORG'); ?></h4>

                <form id="org-form" name="<?php echo $this->orgForm->getName(); ?>" onsubmit="return false;">
                    <div class="hide">
                        <?php echo $this->orgForm->org_id; ?>
                        <?php echo $this->orgForm->parent_org_id; ?>
                    </div>
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted"><?php echo $this->translate( 'TEXT.ORG_PROFILE' ); ?></p>
                        </div>
                        <div class="col-lg-8 col-xl-5">

                            <div class="default-org message-container hide">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate( 'MESSAGE.DEFAULT_ORG' ); ?></div>
                            </div>

                            <div class="org-admin message-container hide">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate( 'MESSAGE.NOT_ORG_ADMIN' ); ?></div>
                            </div>

                            <div class="org-overlay overlay-container">

                                <div class="form-group">
                                    <label for="orgname"><?php echo $this->orgForm->orgname->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->orgname->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->orgname; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="org_display_name"><?php echo $this->orgForm->org_display_name->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->org_display_name->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->org_display_name; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="org_description"><?php echo $this->orgForm->org_description->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->org_description->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->org_description; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="company_name"><?php echo $this->orgForm->company_name->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->company_name->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->company_name; ?>
                                    <div class="message-container"></div>
                                </div>

                                <hr />

                                <div class="form-group">
                                    <label for="domain"><?php echo $this->orgForm->domain->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->domain->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->domain; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="type_org"><?php echo $this->orgForm->type_org->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->type_org->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->type_org; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="type_business"><?php echo $this->orgForm->type_business->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->type_business->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->type_business; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="referral_code"><?php echo $this->orgForm->referral_code->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->orgForm->referral_code->getDescription(); ?>"></i>
                                    <?php echo $this->orgForm->referral_code; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group overflow-auto">
                                    <button id="save-org-button" type="button" class="btn btn-alt-success float-right">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                    </button>
                                </div>

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-org-address" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.ORG_ADDRESSES'); ?></h4>
                <form id="org-form-address" name="<?php echo $this->addressForm->getName(); ?>" onsubmit="return false;">
                    <div class="hide">
                        <?php $this->addressForm->entity->setValue('org'); ?>
                        <?php echo $this->addressForm->entity; ?>
                    </div>
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted"><?php echo $this->translate( 'TEXT.ORG_ADDRESS' ); ?></p>
                        </div>
                        <div class="col-lg-8 col-xl-5">

                            <div class="default-org message-container hide">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate( 'MESSAGE.DEFAULT_ORG' ); ?></div>
                            </div>

                            <div class="org-admin message-container hide">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate( 'MESSAGE.NOT_ORG_ADMIN' ); ?></div>
                            </div>

                            <div class="org-overlay overlay-container">

                                <div class="form-group">
                                    <label for="address_id"><?php echo $this->addressForm->address_id->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->address_id->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->address_id; ?>
                                    <div class="message-container"></div>
                                </div>

                                <hr />

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                            <div class="overlay-container">

                                <h4><?php echo $this->translate('TITLE.ADDRESS'); ?></h4>

                                <div class="row">
                                    <div class="col-md-8">

                                        <div class="form-group">
                                            <label for="type_address"><?php echo $this->addressForm->type_address->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->type_address->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->type_address; ?>
                                            <div class="message-container"></div>
                                        </div>

                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">

                                            <div class="custom-control custom-switch">
                                                <?php $this->addressForm->primary->setAttrib('id', 'org_primary_address'); ?>
                                                <?php echo $this->addressForm->primary; ?>
                                                <label class="custom-control-label font-w400 primary-address" for="org_primary_address"><?php echo $this->addressForm->primary->getLabel(); ?></label>
                                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                                   title="<?php echo $this->addressForm->primary->getDescription(); ?>"></i>
                                            </div>
                                            <div class="message-container"></div>
                                        </div>

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="address"><?php echo $this->addressForm->address->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->address->getDescription(); ?>"></i>
                                    <div class="overflow-auto">
                                        <?php echo $this->addressForm->address; ?>
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 address-lookup-spinner hide"></i>
                                    </div>
                                    <div class="message-container"></div>
                                    <div id="select-address-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="address2"><?php echo $this->addressForm->address2->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->address2->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->address2; ?>
                                    <div class="message-container"></div>
                                </div>
                                <div class="form-group">
                                    <label for="city"><?php echo $this->addressForm->city->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->city->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->city; ?>
                                    <div class="message-container"></div>
                                </div>
                                <!-- Un-hide if you need county info -->
                                <div class="form-group hide">
                                    <label for="county"><?php echo $this->addressForm->county->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->county->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->county; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="state"><?php echo $this->addressForm->state->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->state->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->state; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="postal_code"><?php echo $this->addressForm->postal_code->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->postal_code->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->postal_code; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="country"><?php echo $this->addressForm->country->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->country->getDescription(); ?>"></i>
                                    <?php echo $this->addressForm->country; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="lat"><?php echo $this->addressForm->lat->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->lat->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->lat; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="lng"><?php echo $this->addressForm->lng->getLabel(); ?></label>
                                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                               title="<?php echo $this->addressForm->lng->getDescription(); ?>"></i>
                                            <?php echo $this->addressForm->lng; ?>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group text-right overflow-auto">
                                    <button id="save-org-address-button" type="button" class="btn btn-alt-success float-right">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                    </button>
                                    <button id="remove-org-address-button" type="button" class="btn btn-alt-danger float-left">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-trash mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.REMOVE' ); ?>
                                    </button>
                                </div>

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-org-contact" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.ORG_CONTACTS'); ?></h4>
                <form id="org-form-contact" name="<?php echo $this->contactForm->getName(); ?>" onsubmit="return false;">
                    <div class="hide">
                        <?php $this->contactForm->entity->setValue('org'); ?>
                        <?php echo $this->contactForm->entity; ?>
                    </div>
                    <div class="row push">
                        <div class="col-lg-4">
                            <p class="font-size-sm text-muted"><?php echo $this->translate( 'TEXT.ORG_CONTACTS' ); ?></p>
                        </div>
                        <div class="col-lg-8 col-xl-5">

                            <div class="default-org message-container hide">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate( 'MESSAGE.DEFAULT_ORG' ); ?></div>
                            </div>

                            <div class="org-admin message-container hide">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate( 'MESSAGE.NOT_ORG_ADMIN' ); ?></div>
                            </div>

                            <div class="org-overlay overlay-container">

                                <div class="form-group">
                                    <label for="contact_id"><?php echo $this->contactForm->contact_id->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->contactForm->contact_id->getDescription(); ?>"></i>
                                    <?php echo $this->contactForm->contact_id; ?>
                                    <div class="message-container"></div>
                                </div>

                                <hr />

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                            <div class="overlay-container">

                                <h4><?php echo $this->translate('TITLE.ADDRESS'); ?></h4>

                                <div class="form-group">
                                    <div class="custom-control custom-switch">
                                        <?php $this->contactForm->primary->setAttrib('id', 'org_primary_contact'); ?>
                                        <?php echo $this->contactForm->primary; ?>
                                        <label class="custom-control-label font-w400 primary-address" for="org_primary_contact"><?php echo $this->contactForm->primary->getLabel(); ?></label>
                                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                           title="<?php echo $this->contactForm->primary->getDescription(); ?>"></i>
                                    </div>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group">
                                    <label for="type_contact"><?php echo $this->contactForm->type_contact->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->contactForm->type_contact->getDescription(); ?>"></i>
                                    <?php echo $this->contactForm->type_contact; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group">
                                    <label for="contact_value"><?php echo $this->contactForm->contact_value->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->contactForm->contact_value->getDescription(); ?>"></i>
                                    <?php echo $this->contactForm->contact_value; ?>
                                    <div class="message-container"></div>
                                </div>

                                <div class="form-group text-right overflow-auto">
                                    <button id="save-user-contact-button" type="button" class="btn btn-alt-success float-right">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-check mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.UPDATE' ); ?>
                                    </button>
                                    <button id="remove-user-contact-button" type="button" class="btn btn-alt-danger float-left">
                                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                        <i class="fa fa-fw fa-trash mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.REMOVE' ); ?>
                                    </button>
                                </div>

                                <!-- Overlay allows us to shut off the form until an address is selected. -->
                                <div class="overlay"></div>

                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>

</div>
<!-- END Page Content -->

<!-- Avatar form -->
<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-avatar-form" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="modal-avatar-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="width:600px;">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 class="block-title"><?php echo $this->translate('FORM.MANAGE_AVATAR'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('account/avatar_form.phtml', [ 'avatarForm' => $this->avatarForm ] ); ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
<!-- END Avatar form -->

<!-- Gallery Image Template -->
<div id="gallery-template" class="hide">
    <div class="col-md-6 col-lg-4 col-xl-3 avatar-container">
        <div class="animated fadeIn">
            <div class="options-container fx-item-zoom-in">
                <img class="img-fluid options-item" src="" alt="" title="" id="" data-extension="" />
            </div>
            <button type="button" class="btn btn-sm btn-danger avatar-remove"><i class="fas fa-trash-alt"></i> &nbsp;<?php echo $this->translate('BUTTON.REMOVE'); ?></button>
        </div>
    </div>
</div>
<!-- END Gallery Image Template -->
