<!-- Page Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo34@2x.jpg');">
    <div class="hero-static bg-black-50">
        <div class="content">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <!-- Reminder Block -->
                    <div class="block block-themed mb-0">
                        <div class="block-header bg-danger">
                            <h3 class="block-title"><?php echo $this->translate('RECOVER.PASSWORD') ?></h3>
                            <div class="block-options">
                                <a class="btn-block-option" href="/login" data-toggle="tooltip" data-placement="left" title="<?php echo $this->translate('RECOVER.LOGIN') ?>">
                                    <i class="fa fa-sign-in-alt"></i>
                                </a>
                            </div>
                        </div>
                        <div class="block-content">
                            <div class="p-sm-3 px-lg-4 py-lg-5">
                                <h1 class="mb-2"><?php echo $this->translate('RECOVER.TIGER') ?></h1>
                                <p><?php echo $this->translate('RECOVER.TEXT') ?></p>

                                <!-- Reminder Form -->
                                <form id="page-login-form" name="<?php echo $this->loginForm->getName(); ?>" novalidate="novalidate" onsubmit="return false;">
                                    <?php $message = '';
                                    if ( isset( $this->response ) ) {
                                        $message = $this->response->html[0];
                                    } ?>
                                    <div class="form-message"><?php echo $message; ?></div>
                                    <div class="form-group">
                                        <?php echo $this->loginForm->username; ?>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-6 col-xl-5">
                                            <button id="recover-button" type="button" class="btn btn-block btn-primary">
                                                <i class="fa fa-fw fa-envelope mr-1"></i> <?php echo $this->translate('RECOVER.SEND_MAIL') ?>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                                <!-- END Reminder Form -->

                            </div>
                        </div>
                    </div>
                    <!-- END Reminder Block -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-white text-center">
            <strong><?php echo $this->template->name . ' ' . $this->template->version; ?></strong> &copy; <span data-toggle="year-copy"></span>
        </div>
    </div>
</div>
<!-- END Page Content -->
