<!-- Page Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo34@2x.jpg');">
    <div class="hero-static bg-black-50">
        <div class="content">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <!-- Sign Up Block -->
                    <div class="block block-themed block-fx-shadow-dark mb-0">
                        <div class="block-header bg-success">
                            <h3 class="block-title"><?php echo $this->translate('SIGNUP.CREATE_ACCOUNT') ?></h3>
                            <div class="block-options">
                                <a class="btn-block-option font-size-sm" href="" data-toggle="modal" data-target="#modal-terms">
                                    <?php echo $this->translate('SIGNUP.VIEW_TERMS') ?> <i class="fa fa-sign-in-alt"></i>
                                </a>
                            </div>
                        </div>
                        <div class="block-content">
                            <div class="p-sm-3 px-lg-4 py-lg-5">
                                <h1 class="mb-2"><?php echo $this->translate('SIGNUP.HEADING') ?></h1>
                                <p><?php echo $this->translate('SIGNUP.INSTRUCTIONS') ?></p>

                                <!-- Sign Up Form -->
                                <form id="page-signup-form" name="<?php echo $this->signupForm->getName(); ?>" class="" novalidate="novalidate" onsubmit="return false;">
                                    <div class="row"><div class="col-md-12 form-message"></div></div>
                                    <div class="py-3">
                                        <div class="form-group">
                                            <?php echo $this->signupForm->first_name; ?>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->signupForm->last_name; ?>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->signupForm->company_name; ?>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->signupForm->username; ?>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->signupForm->email; ?>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->signupForm->password; ?>
                                            <div class="password-html" style="overflow: hidden; height: 0px;">
                                                <?php echo $this->signupForm->password->getDescription(); ?>
                                            </div>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->signupForm->type_hearabout; ?>
                                            <div class="message-container"></div>
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox">
                                                <?php echo $this->signupForm->terms; ?>
                                                <label class="custom-control-label font-w400" for="terms"><?php echo $this->signupForm->terms->getLabel(); ?></label>
                                            </div>
                                            <div class="message-container"></div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-6 col-xl-5">
                                            <button id="signup-button" type="button" class="btn btn-block btn-success">
                                                <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                                <i class="fa fa-fw fa-plus mr-1 icon"></i> <?php echo $this->translate( 'BUTTON.SIGNUP' ); ?>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                                <!-- END Sign Up Form -->
                            </div>
                        </div>
                    </div>
                    <!-- END Sign Up Block -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-white text-center">
            <strong><?php echo $this->template->name . ' ' . $this->template->version; ?></strong> &copy; <span data-toggle="year-copy"></span>
        </div>
    </div>
</div>
<!-- END Page Content -->

<!-- Modals -->
<div class="modal fade" id="modal-terms" tabindex="-1" role="dialog" aria-labelledby="modal-block-fadein" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <!-- Modal Content Blocks -->
                <!-- Modal Header -->
                <div class="block-header bg-primary-dark">
                    <h3 class="block-title"><?php echo $this->translate('HEADER.TERMS'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- END Modal Header -->
                <!-- Model Body -->
                <div class="block-content font-size-sm">
                    <p><?php echo $this->translate('TERMS.1'); ?></p>
                    <p><?php echo $this->translate('TERMS.3'); ?></p>
                    <p><?php echo $this->translate('TERMS.4'); ?></p>
                </div>
                <!-- END Modal Body -->
                <!-- Modal Footer -->
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-light" data-dismiss="modal">Close</button>
                    <!-- button type="button" class="btn btn-sm btn-primary" data-dismiss="modal"><i class="fa fa-check mr-1"></i>Ok</button -->
                </div>
                <!-- END Modal Footer -->
                <!-- END Modal Content Blocks -->
            </div>
        </div>
    </div>
</div>
<!-- END Modals -->