<!-- Page Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo34@2x.jpg');">
    <div class="hero-static bg-black-50">
        <div class="content">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <!-- Unlock Block -->
                    <div class="block block-themed mb-0">
                        <div class="block-header bg-danger">
                            <h3 class="block-title"><?php echo $this->translate('HEADER.VERIFY') ?></h3>
                        </div>
                        <div class="block-content">
                            <div class="p-sm-3 px-lg-4 py-lg-5 text-center">
                                <?php if ( $this->response->result === 1 ): ?>
                                    <p class="font-w600 my-2"><i class="fa fa-check-circle green font-size-h1"></i></p>
                                    <div class="font-w600 my-2"><?php echo $this->response->html[0]; ?></div>
                                    <p><?php echo $this->translate('MESSAGE.VERIFY.SUCCESS_TEXT'); ?></p>
                                    <div class="form-group row justify-content-center">
                                        <div class="col-md-6 col-xl-5">
                                            <a href="/manage" class="btn btn-block btn-primary">
                                                <i class="fa fa-paper-plane mr-1"></i> <?php echo $this->translate('BUTTON.VIEW_DASHBOARD') ?>
                                            </a>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <p class="font-w600 my-2"><i class="fa fa-ban red font-size-h1"></i></p>
                                    <div class="message-container"><?php echo $this->response->html[0]; ?> </div>
                                    <p><?php echo $this->translate('MESSAGE.VERIFY.INVALID_TEXT_1'); ?></p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <!-- END Unlock Block -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-white text-center">
            <strong><?php echo $this->template->name . ' ' . $this->template->version; ?></strong> &copy; <span data-toggle="year-copy"></span>
        </div>
    </div>
</div>
<!-- END Page Content -->

