<!-- Page Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo34@2x.jpg');">
    <div class="hero-static bg-black-50">
        <div class="content">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <!-- Unlock Block -->
                    <div class="block block-themed mb-0">
                        <div class="block-header bg-danger">
                            <h3 class="block-title"><?php echo $this->translate('WELCOME.HEADER') ?></h3>
                        </div>
                        <div class="block-content">
                            <div class="p-sm-3 px-lg-4 py-lg-5 text-center">

                                <h2><?php echo $this->translate('WELCOME'); ?></h2>
                                <p><?php echo $this->translate('WELCOME.INSTRUCTIONS'); ?></p>
                                <p class="font-w600 my-2">
                                    <?php echo $this->user->email; ?>
                                </p>

                                <form id="page-resend-form" name="<?php echo $this->resendForm->getName(); ?>" class="" novalidate="novalidate">
                                    <div class="row"><div class="col-md-12 form-message"></div></div>
                                    <div class="form-group row justify-content-center">
                                        <div class="my-3 col-md-6 col-xl-5">
                                            <?php echo $this->resendForm->user_id; ?>
                                            <button id="resend-button" type="button" class="btn btn-block btn-secondary">
                                                <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                                                <i class="fa fa-fw fa-paper-plane mr-1 icon"></i>
                                                <?php echo $this->translate( 'BUTTON_RESEND' ); ?>
                                            </button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                    <!-- END Unlock Block -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-white text-center">
            <strong><?php echo $this->template->name . ' ' . $this->template->version; ?></strong> &copy; <span data-toggle="year-copy"></span>
        </div>
    </div>
</div>
<!-- END Page Content -->

