<!-- Translation Form -->
<form id="doc-form" name="<?php echo $this->docForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->docForm->doc_id; ?> <?php //exit('<pre>'.print_r($this->docForm,true));?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-doc"><?php echo $this->translate('TAB.DOC'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-doc"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-role">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-doc" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.DOC'); ?></h4>
                <?php echo $this->docForm->doc_id; ?>
                <div class="form-group">
                    <label for="title"><?php echo $this->docForm->title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->docForm->title->getDescription(); ?>"></i>
                    <?php echo $this->docForm->title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="parent_id"><?php echo $this->docForm->parent_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->docForm->parent_id->getDescription(); ?>"></i>
                    <?php echo $this->docForm->parent_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="desc"><?php echo $this->docForm->description->getLabel(); ?></label>
                    <t class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->docForm->description->getDescription(); ?>"></t>
                    <?php echo $this->docForm->description; ?>
                    <div class="message-container"></div>
                </div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-doc" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>
                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>

            <div class="tab-pane fade" id="btabs-animated-fade-settings-role" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->docForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_doc"><?php echo $this->docForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->docForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->docForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_doc"><?php echo $this->docForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->docForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Translation Form -->
