<!doctype html>
<html dir="ltr" lang="<?php echo LOCALE; ?>">
<head>

    <!-- Head Meta -->
    <?php echo $this->headMeta(); ?>

    <!-- Stylesheets -->
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>

    <!-- Document Title -->
    <title><?php echo $this->template->title; ?></title>

</head>

<body data-spy="scroll" data-target="#navbar-example3" data-offset="86" class="doc full-width-doc">

    <?php if ( isset( $this->showPreloader) ): ?>
    <div id="preloader">
        <div id="ctn-preloader" class="ctn-preloader">
            <div class="round_spinner">
                <div class="spinner"></div>
                <div class="text">
                    <img src="/assets/docy/img/spinner_logo.png" alt="">
                    <h4><span>Doc</span>y</h4>
                </div>
            </div>
            <h2 class="head">Did You Know?</h2>
            <p></p>
        </div>
    </div>
    <?php endif; ?>

    <div class="body_wrapper">

        <?php echo Tiger_Template::get('docs-nav'); ?>

        <div class="mobile_main_menu dark_menu sticky-nav ">
            <div class="container">
                <div class="mobile_menu_left">
                    <button type="button" class="navbar-toggler mobile_menu_btn">
                    <span class="menu_toggle ">
                        <span class="hamburger">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </span>
                    </button>
                    <a class="navbar-brand header_logo" href="index.html">
                        <img class="sticky_logo main_logo" src="/assets/docy/img/logo.png" srcset="/assets/docy/img/logo-2x.png 2x" alt="logo">
                        <img class="white_logo" src="/assets/docy/img/logo-w.png" srcset="/assets/docy/img/logo-w2x.png 2x" alt="logo">
                    </a>
                </div>
                <div class="mobile_menu_right">
                    <div class="right-nav">
                        <a class="nav_btn tp_btn" href="#" target="_blank">Get Tiger</a>
                        <a class="px-2 ml-3" href="#" title="Subscribe to the newsletter">
                            <ion-icon name="mail"></ion-icon>
                        </a>
                        <a class="px-2" href="#" title="RSS feed">
                            <ion-icon name="logo-rss"></ion-icon>
                        </a>
                        <div class="px-2 js-darkmode-btn btn" title="Toggle dark mode">
                            <label for="something2" class="tab-btn tab-btns">
                                <ion-icon class="light-mode" name="contrast"></ion-icon>
                            </label>
                            <input type="checkbox" name="something2" id="something2" class="dark_mode_switcher">
                            <label for="something2" class="tab-btn">
                                <ion-icon class="dark-mode" name="contrast-outline"></ion-icon>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="click_capture"></div>

        <div class="side_menu">
            <div class="mobile_menu_header">
                <div class="close_nav">
                    <i class="arrow_left"></i>
                    <i class="icon_close"></i>
                </div>
                <div class="mobile_logo">
                    <a class="navbar-brand header_logo" href="index.html">
                        <img class="sticky_logo main_logo" src="/assets/docy/img/logo.png" srcset="/assets/docy/img/logo-2x.png 2x" alt="logo">
                        <img class="white_logo" src="/assets/docy/img/logo-w.png" srcset="/assets/docy/img/logo-w2x.png 2x" alt="logo">
                    </a>
                </div>
            </div>
            <div class="mobile_nav_wrapper">
                <!-- nav class="mobile_nav_top">
                    <ul class="navbar-nav menu ml-auto">
                        <li class="nav-item dropdown submenu">
                            <a href="#" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item dropdown submenu active">
                            <a href="#" class="nav-link">Docs</a>
                            <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="doc-content-video.html" class="nav-link">Doc Archives</a></li>
                                <li class="nav-item"><a href="doc-main.html" class="nav-link">DocTopics</a></li>
                                <li class="nav-item dropdown submenu">
                                    <a href="#" class="nav-link">Elements</a>
                                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item"><a href="doc-element-tab.html" class="nav-link">Tabs</a></li>
                                        <li class="nav-item"><a href="doc-element-accordion.html" class="nav-link">Accordion</a></li>
                                        <li class="nav-item"><a href="doc-element-notice.html" class="nav-link">Notices</a></li>
                                        <li class="nav-item"><a href="doc-content-tables.html" class="nav-link">Tables</a></li>
                                        <li class="nav-item"><a href="doc-content-tooltip.html" class="nav-link">Tooltips & Direction</a></li>
                                        <li class="nav-item"><a href="doc-element-hotspots.html" class="nav-link">Image Hotspots</a></li>
                                        <li class="nav-item"><a href="doc-element-lightbox.html" class="nav-link">Lightbox</a></li>
                                        <li class="nav-item"><a href="doc-changelog.html" class="nav-link">Changelog</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown submenu">
                                    <a href="#" class="nav-link">Layouts</a>
                                    <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item"><a href="doc-element-hotspots.html" class="nav-link">Left Sidebar</a></li>
                                        <li class="nav-item"><a href="doc-content-video.html" class="nav-link">Full-width</a></li>
                                        <li class="nav-item"><a href="doc-layout-banner-gradient.html" class="nav-link">Gradient Banner</a></li>
                                        <li class="nav-item"><a href="doc-layout-banner-empty.html" class="nav-link">Without Banner</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a href="#" class="nav-link">Pages</a>
                            <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="onepage.html" class="nav-link">Onepage Doc</a></li>
                                <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                                <li class="nav-item"><a href="onepage.html" class="nav-link">Onepage Doc</a></li>
                                <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
                                <li class="nav-item"><a href="typography.html" class="nav-link">Typography</a></li>
                                <li class="nav-item"><a href="404-error.html" class="nav-link">404 Error</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a href="#" class="nav-link">Forum</a>
                            <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="forums.html" class="nav-link">Forums Root</a></li>
                                <li class="nav-item"><a href="forum-topics.html" class="nav-link">Forum Topics</a></li>
                                <li class="nav-item"><a href="forum-single.html" class="nav-link">Topic Details</a></li>
                                <li class="nav-item"><a href="forum-profile.html" class="nav-link">User Profile</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link" href="#"> Blog </a>
                            <i class="arrow_carrot-down_alt2 mobile_dropdown_icon"></i>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="blog-grid.html" class="nav-link">Blog Grid</a></li>
                                <li class="nav-item"><a href="blog-grid-two.html" class="nav-link">Blog Grid Two</a></li>
                                <li class="nav-item"><a href="blog-list.html" class="nav-link">Blog List</a></li>
                                <li class="nav-item"><a href="blog-single.html" class="nav-link">Blog Details</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav -->
                <div class="mobile_nav_bottom">

                    <?php echo Tiger_Template::get('docs-menu'); ?>

                </div>
            </div>
        </div>

        <!--================Header Area =================-->
        <section class="doc_banner_area search-banner-light">
            <ul class="list-unstyled banner_shap_img">
                <li><img src="/assets/docy/img/forum/breadcrumb/forum-illustration.png" alt=""></li>
                <li><img src="/assets/docy/img/forum/breadcrumb/forum-illustration-2.png" alt=""></li>
            </ul>
            <div class="container">
                <div class="doc_banner_content">
                    <!-- form action="#" class="header_search_form">
                        <div class="header_search_form_info">
                            <div class="form-group">
                                <div class="input-wrapper">
                                    <i class="icon_search"></i>
                                    <input type='search' id="searchbox" autocomplete="off" name="search"
                                           placeholder="Search for Topics...." />
                                    <div class="header_search_form_panel">
                                        <ul class="list-unstyled">
                                            <li>Help Desk
                                                <ul class="list-unstyled search_item">
                                                    <li><span>Configuration</span><a href="#">How to edit host and
                                                            port?</a></li>
                                                    <li><span>Configuration</span><a href="#">The dev Property</a></li>
                                                </ul>
                                            </li>
                                            <li>Support
                                                <ul class="list-unstyled search_item">
                                                    <li><span>Pages</span><a href="#">The asyncData Method</a></li>
                                                </ul>
                                            </li>
                                            <li>Documentation
                                                <ul class="list-unstyled search_item">
                                                    <li><span>Getting Started</span><a href="#">The asyncData Method</a>
                                                    </li>
                                                    <li><span>Getting Started</span><a href="#">The asyncData Method</a>
                                                    </li>
                                                    <li><span>Getting Started</span><a href="#">The asyncData Method</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="header_search_keyword">
                            <span class="header-search-form__keywords-label">Popular Searches:</span>
                            <ul class="list-unstyled">
                                <li class="wow fadeInUp" data-wow-delay="0.2s"><a href="#">Docy Documentation</a>,</li>
                                <li class="wow fadeInUp" data-wow-delay="0.3s"><a href="#">Tabs Widget</a>,</li>
                                <li class="wow fadeInUp" data-wow-delay="0.4s"><a href="#">Process Tab</a></li>
                            </ul>
                        </div>
                    </form -->
                </div>
            </div>
        </section>
        <!--================End Header Area =================-->

        <!--================Forum Breadcrumb Area =================-->
        <section class="page_breadcrumb">
            <div class="container custom_container">
                <div class="row">
                    <div class="col-sm-7">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Docs</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Docy WordPress Theme</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-sm-5">
                        <a href="#" class="date"><i class="icon_clock_alt"></i><?php echo $this->translate('BREADCRUMB.LAST_UPDATED_ON') . ' ' . date('d-M-Y', strtotime( $this->template->update_date ) ); ?></a>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Forum Breadcrumb Area =================-->

        <section class="doc_documentation_area" id="sticky_doc">
            <div class="overlay_bg"></div>
            <div class="container-fluid pl-60 pr-60">
                <div class="row">

                    <div class="col-lg-2 col-md-2 doc_mobile_menu display_none">
                        <?php echo Tiger_Template::get('docs-menu'); ?>
                    </div>

                    <div class="col-lg-8 col-md-8 doc-middle-content">

                        <div id="post" class="documentation_info">

                            <article class="shortcode_text">

                                <?php echo $this->layout()->content; ?>
                                <?php # echo $this->partial( 'docarticle.phtml' ); ?>

                                <footer>
                                    <?php if ( isset( $this->showFeedback) ): ?>
                                        <div class="border_bottom"></div>
                                        <div class="row feedback_link">
                                            <div class="col-lg-6">
                                                <h6><i class="icon_mail_alt"></i>Still stuck? <a href="#" data-toggle="modal" data-target="#exampleModal3">How can we help?</a></h6>
                                            </div>
                                            <div class="col-lg-6">
                                                <p>Was this page helpful? <a href="#" class="h_btn">Yes</a><a href="#" class="h_btn red">No</a></p>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </footer>

                            </article>

                        </div><!-- #post -->

                        <?php if ( isset( $this->showTopics) ): ?>
                            <div class="row topic_item_tabs inner_tab_list">
                                <div class="col-lg-6">
                                    <div class="topic_list_item">
                                        <h4>Related articles</h4>
                                        <ul class="navbar-nav">
                                            <li><a href="#"><i class="icon_document_alt"></i>Accordions Widget</a></li>
                                            <li><a href="#"><i class="icon_document_alt"></i>Notice / Message Widget</a>
                                            </li>
                                            <li><a href="#"><i class="icon_document_alt"></i>Cheatsheet</a></li>
                                            <li><a href="#"><i class="icon_document_alt"></i>Image Hotspots Widget</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="topic_list_item">
                                        <h4>Recently viewed articles</h4>
                                        <ul class="navbar-nav">
                                            <li><a href="#"><i class="icon_document_alt"></i>Tabs Widget</a></li>
                                            <li><a href="#"><i class="icon_document_alt"></i>Notice / Message Widget</a>
                                            </li>
                                            <li><a href="#"><i class="icon_document_alt"></i>Cheatsheet</a></li>
                                            <li><a href="#"><i class="icon_document_alt"></i>Image Hotspots Widget</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>

                        <?php if ( isset( $this->showComments) ): ?>
                            <div class="comment_inner">
                                <h2 class="c_head">3 Comment</h2>
                                <ul class="comment_box list-unstyled">
                                    <li class="post_comment">
                                        <div class="media comment_author">
                                            <img class="img_rounded" src="/assets/docy/img/blog-single/comment_01.jpg" alt="">
                                            <div class="media-body">
                                                <div class="comment_info">
                                                    <h3>Issac Wise</h3>
                                                    <div class="comment_date">July 3, 2020 at 2:14 pm</div>
                                                </div>
                                                <p>Wouldn’t it be better practice to use get_the_title(..) in this case?
                                                    directly accessing the post object’s data member would bypass
                                                    applying filters and enforcing protected and private settings,
                                                    unless that’s explicitly desired.</p>
                                                <a href="#" class="comment_reply">Reply <i class="arrow_right"></i></a>
                                            </div>
                                        </div>
                                        <ul class="list-unstyled reply_comment">
                                            <li>
                                                <div class="media comment_author">
                                                    <img class="img_rounded" src="/assets/docy/img/blog-single/comment_02.jpg"
                                                         alt="">
                                                    <div class="media-body">
                                                        <div class="comment_info">
                                                            <h3>Hans Down</h3>
                                                            <div class="comment_date">44 mins ago</div>
                                                        </div>
                                                        <p>Thenks Demo User for Wouldn’t it be better practice to use
                                                            get_the_title.</p>
                                                        <a href="#" class="comment_reply">Reply <i
                                                                    class="arrow_right"></i></a>
                                                    </div>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="media comment_author">
                                                    <img class="img_rounded" src="/assets/docy/img/blog-single/comment_03.jpg"
                                                         alt="">
                                                    <div class="media-body">
                                                        <div class="comment_info">
                                                            <h3>Hans Down</h3>
                                                            <div class="comment_date">44 mins ago</div>
                                                        </div>
                                                        <p>Dropped a clanger up the kyver easy peasy vagabond victoria
                                                            sponge Charles tinkety tonk old fruit argy.!</p>
                                                        <a href="#" class="comment_reply">Reply <i
                                                                    class="arrow_right"></i></a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="post_comment">
                                        <div class="media comment_author">
                                            <img class="img_rounded" src="/assets/docy/img/blog-single/comment_01.jpg" alt="">
                                            <div class="media-body">
                                                <div class="comment_info">
                                                    <h3>Chauffina Carr</h3>
                                                    <div class="comment_date">04 mins ago</div>
                                                </div>
                                                <p>Wouldn’t it be better practice to use get_the_title(..) in this case?
                                                    directly accessing the post object’s data member would bypass
                                                    applying filters and enforcing protected and private settings,
                                                    unless that’s explicitly desired.</p>
                                                <a href="#" class="comment_reply">Reply <i class="arrow_right"></i></a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        <?php endif; ?>

                        <?php if ( isset( $this->showCommentForm) ): ?>
                            <div class="blog_comment_box topic_comment">
                                <h2 class="c_head">Leave a Reply</h2>
                                <p>Your email address will not be published. Required fields are marked *</p>
                                <form class="get_quote_form row" action="#" method="post">
                                    <div class="col-md-6 form-group">
                                        <input type="text" class="form-control" id="name" required>
                                        <label class="floating-label">Full Name *</label>
                                    </div>
                                    <div class="col-md-6 form-group">
                                        <input type="email" class="form-control" id="email" required>
                                        <label class="floating-label">Email *</label>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <input type="text" class="form-control" id="web" required>
                                        <label class="floating-label">Website (Optional)</label>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <textarea class="form-control message" required></textarea>
                                        <label class="floating-label">Comment type...</label>
                                    </div>
                                    <div class="col-md-12 form-group check_input">
                                        <input type="checkbox" id="fruit1" name="fruit-1" value="Apple">
                                        <label for="fruit1">Save my name, email, and website in this browser for the
                                            next time I comment.</label>
                                    </div>
                                    <div class="col-md-12 form-group"><button class="btn action_btn thm_btn"
                                                                              type="submit">Post
                                            Comment</button></div>
                                </form>
                            </div>
                        <?php endif; ?>

                    </div><!-- .doc-middle-content -->

                    <div class="col-lg-2 col-md-2 doc_right_mobile_menu">
                        <div class="open_icon" id="right">
                            <i class="arrow_carrot-left"></i>
                            <i class="arrow_carrot-right"></i>
                        </div>
                        <div class="doc_rightsidebar scroll">
                            <div class="pageSideSection">
                                <select id="mySelect" name="os">
                                    <option value="english" data-content="<i class='fab fa-windows'></i> English">English</option>
                                    <!-- option value="ios" data-content="<i class='fab fa-apple'></i> Ios">Ios</option -->
                                    <!-- option value="linux" data-content="<i class='fab fa-linux'></i> Linux">Linux</option -->
                                </select>
                                <div id="font-switcher" class="d-flex justify-content-between align-items-center">
                                    <div id="rvfs-controllers" class="fontsize-controllers group"></div>
                                    <a href="javascript:window.print()" class="print"><i class="icon_printer"></i></a>
                                </div>
                                <div class="table-of-content">
                                    <h6><i class="icon_ul"></i> CONTENTS</h6>
                                    <nav class="list-unstyled doc_menu" id="navbar-example3">
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div><!-- .doc_right_mobile_menu -->

                </div><!-- .row -->
            </div>

        </section>

        <?php echo Tiger_Template::get('docs-article-footer'); ?>

    </div>

    <!-- Back to top button -->
    <a id="back-to-top" title="Back to Top"></a>

    <!-- TIGER Page Metadata -->
    <div id="metadata" class="hide"
         data-locale="<?php echo LOCALE; ?>"
         data-application-env="<?php echo APPLICATION_ENV; ?>"
         data-base-url="<?php echo $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME']; ?>"
    ></div>

    <!-- Footer JavaScripts -->
    <?php echo $this->inlineScript(); ?>

</body>

</html>
