<!doctype html>
<html dir="ltr" lang="<?php echo LOCALE; ?>">
    <head>

        <!-- Head Meta -->
        <?php echo $this->headMeta(); ?>

        <!-- Stylesheets -->
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <!-- Document Title -->
        <title><?php echo $this->template->title; ?></title>

    </head>

    <body data-spy="scroll" data-target="#navbar-example3" data-offset="86" data-scroll-animation="true">

    <div id="preloader">
        <div id="ctn-preloader" class="ctn-preloader" style="display: none;">
            <div class="round_spinner">
                <div class="spinner"></div>
                <div class="text">
                    <img src="/assets/docy/img/spinner_logo.png" alt="">
                    <h4><span>Doc</span>y</h4>
                </div>
            </div>
            <h2 class="head">Did You Know?</h2>
            <p></p>
        </div>
    </div>
    <div class="body_wrapper">

        <?php echo $this->layout()->content; ?>

    </div>

    <!-- Back to top button -->
    <a id="back-to-top" title="Back to Top"></a>

    <!-- TIGER Page Metadata -->
    <div id="metadata" class="hide"
         data-locale="<?php echo LOCALE; ?>"
         data-application-env="<?php echo APPLICATION_ENV; ?>"
         data-base-url="<?php echo $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME']; ?>"
    ></div>

    <!-- Footer JavaScripts -->
    <?php echo $this->inlineScript(); ?>

    </body>

</html>
