<?php echo $this->partial('admin/hero.phtml', ['template' => $this->template]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>

    <!-- Configs -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.BACKUP_CONTROLS'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-backup" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#backupDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#backupDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="backupDT-container">
                    <div class="block-content block-content-full">
                        <table id="backupDT" style="width: 100%;"
                               class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
<!-- END Page Content -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-backup-form" tabindex="-1" role="dialog" aria-labelledby="modal-backup-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-config-header" class="block-title"><?php echo $this->translate('FORM.ADD_BACKUP'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <form name="backup-form">
                        <div id="form-message"></div>
                        <div class="form-group">
                            <label for="filename"><?php echo $this->translate('LABEL.OPTIONAL_FILE_NAME'); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->translate('LABEL.OPTIONAL_FILE_NAME_DESCRIPTION'); ?>"></i>
                            <input id="filename" name="filename" type="text" class="form-control" value="" />
                            <div class="message-container"></div>
                        </div>
                    </form>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-backup-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.BACKUP_NOW'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-backup-confirm-delete" tabindex="-1" role="dialog" aria-labelledby="modal-backup-confirm-delete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-config-header" class="block-title"><?php echo $this->translate('FORM.CONFIRM_DELETE_BACKUP'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <div id="form-delete-message"></div>
                    <H4><?php echo $this->translate('MESSAGE.CONFIRM_DELETE_BACKUP'); ?></H4>
                    <h5 id="delete-filename"></h5>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CANCEL'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-danger" id="delete-backup-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.CONFIRM'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-backup-confirm-restore" tabindex="-1" role="dialog" aria-labelledby="modal-backup-confirm-restore" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-config-header" class="block-title"><?php echo $this->translate('FORM.CONFIRM_RESTORE_BACKUP'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <div id="form-delete-message"></div>
                    <H4><?php echo $this->translate('MESSAGE.CONFIRM_RESTORE_BACKUP'); ?></H4>
                    <h5 id="restore-filename"></h5>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CANCEL'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-danger" id="restore-backup-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.CONFIRM'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
