<?php echo $this->partial('admin/hero.phtml', ['template' => $this->template]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>

    <!-- Configs -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.CACHE_CONTROLS'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-config" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#configsDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#configsDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="configsDT-container">
                    <div class="block-content block-content-full">
                        <div>
                            <form>

                                <div class="form-group">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" name="useCache" id="useCache"
                                               value="1" class="custom-control-input no-validate"
                                               <?php echo ( $this->useCache ) ? 'checked' : ''; ?>
                                        />
                                        <label class="custom-control-label font-w400" for="useCache"><?php echo $this->translate('LABEL.USE_CACHE'); ?></label>
                                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                           title="<?php echo $this->translate('DESCRIPTION.USE_CACHE'); ?>"></i>
                                    </div>
                                    <div class="message-container" style="height: auto; opacity: 1;"></div>
                                </div>

                                <hr />

                                <?php $disabled = ( ! $this->useCache ) ? 'disabled' : ''; ?>

                                <div class="form-group custom-control">
                                    <button type="button" id="clear-cache" class="btn btn-alt-primary <?php echo $disabled; ?>"
                                        <?php echo $disabled; ?>
                                    ><?php echo $this->translate('BUTTON.CLEAR_CACHE'); ?></button>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                       title="<?php echo $this->translate('DESCRIPTION.CLEAR_CACHE'); ?>"></i>
                                </div>

                                <hr />

                                <div class="form-group">
                                    <label for="cache-servers"><?php echo $this->translate('LABEL.CACHE_SERVERS'); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                       title="<?php echo $this->translate('DESCRIPTION.CACHE_SERVERS'); ?>"></i>
                                    <textarea class="form-control form-control-alt w-25" id="cache-servers" readonly
                                              name="cache-servers" rows="6" placeholder=""><?php echo $this->cacheServers; ?></textarea>
                                    <div class="message-container" style="height: auto; opacity: 1;"></div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
<!-- END Page Content -->
