<?php echo $this->partial('admin/hero.phtml', ['one' => $this->one]); ?>

<!-- Page Content -->
<div class="content content-narrow">
    <!-- Info -->
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success d-flex align-items-center" role="alert">
                <div class="flex-00-auto">
                    <i class="fa fa-fw fa-check"></i>
                </div>
                <div class="flex-fill ml-3">
                    <p class="mb-0"><?php echo $this->translate('CORE.CACHE_CLEARED'); ?></p>
                </div>
            </div>
        </div>
    </div>
    <!-- END Info -->
</div>
<!-- END Page Content -->
