<?php echo $this->partial('admin/hero.phtml', ['one' => $this->one]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>

    <!-- Configs -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.CONFIGURATION'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-config" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#configsDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#configsDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="configsDT-container">
                    <div class="block-content block-content-full">
                        <table id="configsDT" style="width: 100%;"
                               class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="font-size-sm"><?php echo $this->translate('FOOTNOTE.CONFIG_CACHE_CHANGE'); ?></div>
        </div>
    </div>
    <!-- END Configs -->

</div>

<div class="content content-narrow">

    <!-- Static Configs -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">
                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.STATIC_CONFIGURATION'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#staticConfigsDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#staticConfigsDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="staticConfigsDT-container">
                    <div class="block-content block-content-full">
                        <table id="staticConfigsDT" style="width: 100%;"
                               class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Static Configs -->

</div>
<!-- END Page Content -->
