<?php echo $this->partial('admin/hero.phtml', ['one' => $this->one]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <!-- Users -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.CONFIGURATION'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-tiger-reload-configs="">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#config-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="config-container">
                    <div class="block-content block-content-full">

                        <?php echo $this->partial( 'admin/config_tabs.phtml' ); ?>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Users -->

</div>
<!-- END Page Content -->
