<div class="row"><div class="col-md-12 form-message"></div></div>

<!-- Block Tabs Animated Fade -->
<div class="block">
    <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="#btabs-animated-fade-core-general"><?php echo $this->translate('TAB.GENERAL'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#btabs-animated-fade-core-smtp"><?php echo $this->translate('TAB.SMTP'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#btabs-animated-fade-core-s3"><?php echo $this->translate('TAB.S3'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#btabs-animated-fade-core-system-info"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
        </li>
        <li class="nav-item ml-auto">
            <a class="nav-link" href="#btabs-animated-fade-core-config">
                <i class="si si-settings"></i>
            </a>
        </li>
    </ul>
    <div class="block-content tab-content overflow-hidden">


        <div class="tab-pane fade show active" id="btabs-animated-fade-core-general" role="tabpanel">
            <h4><?php echo $this->translate('TITLE.GENERAL'); ?></h4>

            <p>Allows you to set general application configuration parameters.</p>

        </div>


        <div class="tab-pane fade" id="btabs-animated-fade-core-smtp" role="tabpanel">
            <h4><?php echo $this->translate('TITLE.SMTP'); ?></h4>

            <p>Allows you to set SMTP for emailing from within Tiger.</p>

        </div>


        <div class="tab-pane fade" id="btabs-animated-fade-core-s3" role="tabpanel">
            <h4><?php echo $this->translate('TITLE.S3'); ?></h4>

            <p>Allows you to set S3 Credentials.</p>

        </div>


        <div class="tab-pane fade" id="btabs-animated-fade-core-system-info" role="tabpanel">
            <h4><?php echo $this->translate('TITLE.SYSTEM_INFO'); ?></h4>

            <p>Shows Server Vars and other Server Info.</p>


        </div>


        <div class="tab-pane fade" id="btabs-animated-fade-core-config" role="tabpanel">
            <h4><?php echo $this->translate('TITLE.CONFIGURATION'); ?></h4>

            <p>Allows you to create ad-hoc configuration entries. Use with caution.</p>

        </div>

    </div>
</div>
<!-- END Block Tabs Animated Fade -->
