<?php echo $this->partial('admin/hero.phtml', ['template' => $this->template]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>

    <!-- Configs -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.PACKAGE_CONTROLS'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-package" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#packageDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#packageDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option" id="sync-packages">
                            <i class="si si-reload"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="packageDT-container">
                    <div class="block-content block-content-full">
                        <table id="packageDT" style="width: 100%;" class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
<!-- END Page Content -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-package-form" tabindex="-1" role="dialog" aria-labelledby="modal-package-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-package-header" class="block-title"><?php echo $this->translate('FORM.ADD_PACKAGE'); ?></h3>
                    <h3 id="edit-package-header" class="block-title hide"><?php echo $this->translate('FORM.EDIT_PACKAGE'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('admin/package_form.phtml', [ 'packageForm' => $this->packageForm ] ) ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-package-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE_PACKAGE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-package-confirm-delete" tabindex="-1" role="dialog" aria-labelledby="modal-package-confirm-delete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-package-header" class="block-title"><?php echo $this->translate('FORM.CONFIRM_DELETE_PACKAGE'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <div id="form-delete-message"></div>
                    <H4><?php echo $this->translate('MESSAGE.CONFIRM_DELETE_PACKAGE'); ?></H4>
                    <h5 id="delete-name"></h5>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CANCEL'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-danger" id="delete-package-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.CONFIRM'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-package-confirm-sync" tabindex="-1" role="dialog" aria-labelledby="modal-package-confirm-sync" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-package-header" class="block-title"><?php echo $this->translate('MESSAGE.CONFIRM_PACKAGE_SYNC'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <div id="sync-error-message"></div>
                    <p><?php echo $this->translate('MESSAGE.CONFIRM_PACKAGE_SYNC_TEXT_1'); ?></p>
                    <p><?php echo $this->translate('MESSAGE.CONFIRM_PACKAGE_SYNC_TEXT_2'); ?></p>
                    <p><?php echo $this->translate('MESSAGE.CONFIRM_PACKAGE_SYNC_TEXT_3'); ?></p>
                    <div class="text-center bold mb-3 font-size-h1" style="color:#aaa"><i id="sync-spinner" class="fa fa-fw fa-circle-notch"></i></div>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CANCEL'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-primary" id="sync-package-confirm">
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.CONFIRM'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
