<!-- Config Form -->
<form id="package-form" name="<?php echo $this->packageForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->packageForm->package_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul id="package-tabs" class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-package"><?php echo $this->translate('TAB.PACKAGE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-package"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-package" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.PACKAGE'); ?></h4>

                <div class="form-group">
                    <label for="name"><?php echo $this->packageForm->name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->packageForm->name->getDescription(); ?>"></i>
                    <?php echo $this->packageForm->name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="target_version"><?php echo $this->packageForm->target_version->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->packageForm->target_version->getDescription(); ?>"></i>
                    <?php echo $this->packageForm->target_version; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="repo_type"><?php echo $this->packageForm->repo_type->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->packageForm->repo_type->getDescription(); ?>"></i>
                    <?php echo $this->packageForm->repo_type; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="repo_url"><?php echo $this->packageForm->repo_url->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->packageForm->repo_url->getDescription(); ?>"></i>
                    <?php echo $this->packageForm->repo_url; ?>
                    <div class="message-container"></div>
                </div>

                <div id="package-details" class="hide">

                    <div class="form-group">

                        <label><strong><?php echo $this->translate('LABEL.PACKAGE_DESCRIPTION'); ?>:</strong></label>
                        <p><span class="package_description"></span></p>
                        <p><strong><?php echo $this->translate('LABEL.PACKAGE_TYPE'); ?>: </strong><span class="package_type"></span></p>
                        <p><strong><?php echo $this->translate('LABEL.PACKAGE_VERSION'); ?>: </strong><span class="package_version"></span></p>
                        <p><strong><?php echo $this->translate('LABEL.PACKAGE_LATEST'); ?>: </strong><span class="package_latest"></span></p>
                        <p><strong><?php echo $this->translate('LABEL.PACKAGE_ACTIVE'); ?>: </strong><span class="package_active"></span></p>

                    </div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-package" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Config Form -->
