<!-- Config Form -->

    <div class="row">
        <div class="col-md-12">
            <h2><?php echo $this->translate('HEADER.SETUP_WELCOME'); ?></h2>
            <h4><?php echo $this->translate('HEADER.SETUP_INITIAL'); ?></h4>
            <p><?php echo $this->translate('HEADER.SETUP_OVERVIEW'); ?></p>
        </div>
    </div>

    <div class="row"><div id="form-setup-message" class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <!-- div class="block" -->
    <div class="tiger-form-wizard block">

        <ul class="nav nav-tabs nav-tabs-block nav-justified" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-admin-user"><?php echo $this->translate('TAB.ADMIN_USER'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-database"><?php echo $this->translate('TAB.DATABASE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-encryption"><?php echo $this->translate('TAB.ENCRYPTION'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-smtp"><?php echo $this->translate('TAB.SMTP'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-register"><?php echo $this->translate('TAB.REGISTER'); ?></a>
            </li>
        </ul>

        <!-- Wizard Progress Bar -->
        <div class="progress" data-wizard="progress" style="height: 8px;">
            <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style="" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <!-- END Wizard Progress Bar -->

        <form id="setup-form" name="<?php echo $this->setupForm->getName(); ?>" class="" novalidate="novalidate">

            <div class="block-content tab-content overflow-hidden">

                <div class="tab-pane fade show active" id="btabs-animated-fade-admin-user" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.ADMIN_USER'); ?></h4>

                    <p><?php echo $this->translate('ADMIN_USER_TEXT'); ?></p>

                    <div class="row">
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="admin_first_name"><?php echo $this->setupForm->admin_first_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                   title="<?php echo $this->setupForm->admin_first_name->getDescription(); ?>"></i>
                                <?php echo $this->setupForm->admin_first_name; ?>
                                <div class="message-container"></div>
                            </div>

                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="admin_last_name"><?php echo $this->setupForm->admin_last_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                   title="<?php echo $this->setupForm->admin_last_name->getDescription(); ?>"></i>
                                <?php echo $this->setupForm->admin_last_name; ?>
                                <div class="message-container"></div>
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="admin_email"><?php echo $this->setupForm->admin_email->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->admin_email->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->admin_email; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="admin_username"><?php echo $this->setupForm->admin_username->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->admin_username->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->admin_username; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="admin_password"><?php echo $this->setupForm->admin_password->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->translate('DESCRIPTION.USER_PASSWORD'); ?>"></i>
                        <?php echo $this->setupForm->admin_password; ?>
                        <div class="password-html" style="overflow: hidden; height: 0px;">
                            <?php echo $this->setupForm->admin_password->getDescription(); ?>
                        </div>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-database" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.DATABASE'); ?></h4>

                    <p><?php echo $this->translate('DATABASE_TEXT'); ?></p>

                    <div class="form-group">
                        <label for="db_username"><?php echo $this->setupForm->db_username->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->db_username->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->db_username; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="db_password"><?php echo $this->setupForm->db_password->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->db_password->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->db_password; ?>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-encryption" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.ENCRYPTION'); ?></h4>

                    <p><?php echo $this->translate('ENCRYPTION_TEXT'); ?></p>

                    <div class="form-group">
                        <label for="encryption_key"><?php echo $this->setupForm->encryption_key->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->encryption_key->getDescription(); ?>"></i>
                        <div class="input-group">
                            <?php echo $this->setupForm->encryption_key; ?>
                            <div class="input-group-append">
                                <button type="button" class="btn btn-alt-light generate">Generate</button>
                            </div>
                        </div>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="encryption_iv"><?php echo $this->setupForm->encryption_iv->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->encryption_iv->getDescription(); ?>"></i>
                        <div class="input-group">
                            <?php echo $this->setupForm->encryption_iv; ?>
                            <div class="input-group-append">
                                <button type="button" class="btn btn-alt-light generate">Generate</button>
                            </div>
                        </div>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-smtp" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SMTP'); ?></h4>

                    <p><?php echo $this->translate('SMTP_TEXT'); ?></p>

                    <div class="form-group">
                        <label for="smtp_host"><?php echo $this->setupForm->smtp_host->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->smtp_host->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->smtp_host; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="smtp_username"><?php echo $this->setupForm->smtp_username->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->smtp_username->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->smtp_username; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="smtp_password"><?php echo $this->setupForm->smtp_password->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->smtp_password->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->smtp_password; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="smtp_auth"><?php echo $this->setupForm->smtp_auth->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->smtp_auth->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->smtp_auth; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="smtp_ssl"><?php echo $this->setupForm->smtp_ssl->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->smtp_ssl->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->smtp_ssl; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="smtp_port"><?php echo $this->setupForm->smtp_port->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->smtp_port->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->smtp_port; ?>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-register" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.REGISTER'); ?></h4>

                    <p><?php echo $this->translate('REGISTER_TEXT'); ?></p>

                    <div class="row">
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="first_name"><?php echo $this->setupForm->first_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                   title="<?php echo $this->setupForm->first_name->getDescription(); ?>"></i>
                                <?php echo $this->setupForm->first_name; ?>
                                <div class="message-container"></div>
                            </div>

                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="last_name"><?php echo $this->setupForm->last_name->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                                   title="<?php echo $this->setupForm->last_name->getDescription(); ?>"></i>
                                <?php echo $this->setupForm->last_name; ?>
                                <div class="message-container"></div>
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="company_name"><?php echo $this->setupForm->company_name->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->company_name->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->company_name; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="email"><?php echo $this->setupForm->email->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->email->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->email; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="country"><?php echo $this->setupForm->country->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->country->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->country; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="type_profession"><?php echo $this->setupForm->type_profession->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->type_profession->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->type_profession; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="type_hearabout"><?php echo $this->setupForm->type_hearabout->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->setupForm->type_hearabout->getDescription(); ?>"></i>
                        <?php echo $this->setupForm->type_hearabout; ?>
                        <div class="message-container"></div>
                    </div>

                </div>

            </div>

        </form>
        <!-- END Config Form -->

    </div>
    <!-- END Block Tabs Animated Fade -->



