<?php require 'head_start.php'; ?>
<?php require 'head_end.php'; ?>
<?php require 'page_start.php'; ?>

<?php echo $this->layout()->content; ?>

<?php require 'page_end.php'; ?>
<?php require 'footer_start.php'; ?>

<!-- Page JS Plugins -->
<?php $this->one->get_js('js/plugins/chart.js/Chart.bundle.min.js'); ?>

<!-- Page JS Code -->
<?php $this->one->get_js('js/pages/be_pages_dashboard.min.js'); ?>

<?php require 'footer_end.php'; ?>




