<?php

Zend_View_Helper_Navigation_HelperAbstract::setDefaultAcl( Zend_Registry::get( 'Zend_Acl' ) );
Zend_View_Helper_Navigation_HelperAbstract::setDefaultRole( Zend_Auth::getInstance()->getIdentity()->role );

$iterator = new RecursiveIteratorIterator( new RecursiveCachingIterator( $this->container ), RecursiveIteratorIterator::SELF_FIRST);

$menu = '';

foreach ( $iterator as $page ) {

    /** Check to see if we're authorized by the ACL to view this page. */
    if ( $this->navigation()->accept( $page ) ) {

        if ( $page->getTitle() !== '' ) {

            $menu .=
                '<li class="nav-main-heading">' . $this->translate( $page->getTitle() ) . '</li>';

        }

        elseif ( $page->getHref() !== '' ) {

            $menu .=
                '<li class="nav-main-item">' .
                    '<a class="nav-main-link" href="' . $page->getHref() . '">';
                        ( $page->get('icon') === '' ) ?: $menu .= '<i class="' . $page->get('icon') . '"></i>';
                        $menu .='<span class="nav-main-link-name">' . $this->translate( $page->getLabel() ) . '</span>' .
                    '</a>';

        }

        if ( $page->hasChildren() ) {
            $menu .= '<ul class="nav-main-submenu">';
        }
        else {
            $menu .= '</li>';
        }

        if ( ! $page->hasChildren() && ! $iterator->hasNext() ) {
            // Close sub menu - last child
            $menu .= '</ul></li>';
        }

    }

}

echo $menu;
