
<nav id="sidebar" aria-label="Main Navigation">
    <!-- Side Header -->
    <div class="content-header bg-white-5">
        <!-- Logo -->
        <?php echo $this->template->admin_logo; ?>
        <!-- END Logo -->
    </div>
    <!-- END Side Header -->

    <!-- Side Navigation -->
    <div class="content-side content-side-full">

        <?php
            //exit('------<pre>'.print_r($this, true) . '</pre>');
        ?>
        <ul class="nav-main">
            <?php
            try {
                // Typically Manage or Admin menu //
                $menu = $this->navigation()->findById($this->template->menu);
                echo $this->navigation()->menu()->renderPartial($menu, ['menu.phtml', 'core']);
            }
            catch ( Exception | Error $e ){
                pr( $e->getMessage() );
            }
            ?>
        </ul>
    </div>
    <!-- END Side Navigation -->
</nav>
<!-- END Sidebar -->
