<?php
/**
 * head_end.php
 *
 * Author: pixelcave
 *
 * (continue) The first block of code used in every page of the template
 *
 * The reason we separated head_start.php and head_end.php is for enabling
 * us to include between them extra plugin CSS files needed only in specific pages
 *
 */
?>
    <!-- Head Meta -->
    <?php echo $this->headMeta(); ?>
    <!-- END Head Meta -->

    <!-- Links -->
    <?php echo $this->headLink(); ?>
    <!-- END Links -->

    <!-- Head Styles -->
    <?php echo $this->headStyle(); ?>
    <!-- END Head Styles -->

    <!-- Head Scripts -->
    <?php echo $this->headScript(); ?>
    <!-- END Head Scripts -->

</head>
<body>
