<?php echo $this->partial( 'head_start.phtml', ['one' => $this->one] ); ?>
<?php echo $this->partial( 'head_end.phtml', ['one' => $this->one] ); ?>
<?php echo $this->partial( 'page_start.phtml', ['one' => $this->one] ); ?>

<?php echo $this->layout()->content; ?>

<?php $this->partial( 'page_end.phtml', ['one' => $this->one] ); ?>
<?php $this->partial( 'footer_start.phtml', ['one' => $this->one] ); ?>

<!-- Page JS Plugins -->
<?php echo $this->inlineScript(); ?>

<!--
    TIGER Globals

    It's generally considered bad form putting vars in the global scope, but some things are helpful.
-->
<script>let LOCALE = '<?php echo LOCALE; ?>';</script>

<?php $this->partial( 'footer_end.phtml', ['one' => $this->one] ); ?>
