<?php echo $this->partial( 'head_start.phtml', ['one' => $this->one] ); ?>
<?php echo $this->partial( 'head_end.phtml', ['one' => $this->one] ); ?>
<?php echo $this->partial( 'page_start.phtml', ['one' => $this->one] ); ?>

<?php echo $this->layout()->content; ?>

<?php $this->partial( 'page_end.phtml', ['one' => $this->one] ); ?>
<?php $this->partial( 'footer_start.phtml', ['one' => $this->one] ); ?>

<!-- Page JS Plugins -->
<?php echo $this->inlineScript(); ?>

<!-- TIGER Metadata -->
<script>let LOCALE = '<?php echo LOCALE; ?>';</script>
<div id="metadata" class="hide"
     data-locale="<?php echo LOCALE; ?>"
     data-application-env="<?php echo APPLICATION_ENV; ?>"
     data-base-url="<?php echo $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME']; ?>"
></div>

<?php $this->partial( 'footer_end.phtml', ['one' => $this->one] ); ?>
