<?php
/**
 * page_end.php
 *
 * Author: pixelcave
 *
 * The end section of each page used in every page of the template
 *
 */
?>
    </main>
    <!-- END Main Container -->

    <?php if ( isset($this->template->inc_footer) && $this->template->inc_footer ): ?>
        <?php echo $this->partial( 'inc_footer.phtml', [ 'template' => $this->template ] ); ?>
    <?php endif; ?>

</div>
<!-- END Page Container -->
