<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('<?php echo $this->template->assets_folder; ?>/media/photos/photo3@2x.jpg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear"><?php echo $this->template->page_title; ?></h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250"><?php echo $this->translate('WELCOME'); ?> <?php echo ucfirst( $this->template->user->role ); ?></h2>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <?php if ( APPLICATION_ENV !== 'production' ): ?>
                    <h4 style="color:#FFF;">ENV: <?php echo ucfirst(APPLICATION_ENV ); ?></h4>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->