<!-- Resource Form -->
<form id="message-form" name="<?php echo $this->messageForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->messageForm->message_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-message"><?php echo $this->translate('TAB.MESSAGE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-message-dates"><?php echo $this->translate('TAB.MESSAGE_DATES'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-message-send-list"><?php echo $this->translate('TAB.MESSAGE_SEND_LIST'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-message"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-message">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-message" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.MESSAGE'); ?></h4>

                <div class="form-group">
                    <label for="target"><?php echo $this->messageForm->target->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->target->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->target; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="format"><?php echo $this->messageForm->format->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->format->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->format; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="icon_class"><?php echo $this->messageForm->icon_class->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->icon_class->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->icon_class; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->messageForm->dismissible; ?>
                        <label class="custom-control-label font-w400" for="dismissible"><?php echo $this->messageForm->dismissible->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->dismissible->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="link"><?php echo $this->messageForm->link->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->link->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->link; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->messageForm->link_new; ?>
                        <label class="custom-control-label font-w400" for="link_new_message"><?php echo $this->messageForm->link_new->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->link_new->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

                <hr />

                <div class="form-group">
                    <label for="title"><?php echo $this->messageForm->title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->title->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="message"><?php echo $this->messageForm->message->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->message->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->message; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_status"><?php echo $this->messageForm->type_status->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->type_status->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->type_status; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="locale-message"><?php echo $this->messageForm->locale->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->locale->getDescription(); ?>"></i>
                    <?php echo $this->messageForm->locale; ?>
                    <div class="message-container"></div>
                </div>

                <div>
                    <h4><?php echo $this->translate('HEADER.MESSAGE_PREVIEW'); ?></h4>
                    <div id="message-preview" class=""></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-message-dates" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.MESSAGE_DATES'); ?></h4>

                <div class="form-group">
                    <label for="start_date"><?php echo $this->messageForm->start_date->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->start_date->getDescription(); ?>"></i>
                    <div class="input-group">
                        <?php echo $this->messageForm->start_date; ?>
                        <div class="input-group-append">
                            <span class="input-group-text input-group-text-alt">
                                <i class="far fa-calendar-alt"></i>
                            </span>
                        </div>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="end_date"><?php echo $this->messageForm->end_date->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->messageForm->end_date->getDescription(); ?>"></i>
                    <div class="input-group">
                        <?php echo $this->messageForm->end_date; ?>
                        <div class="input-group-append">
                            <span class="input-group-text input-group-text-alt">
                                <i class="far fa-calendar-alt"></i>
                            </span>
                        </div>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-message-send-list" role="tabpanel">

                <div id="notification-wrapper" style="display: none;">

                    <h4><?php echo $this->translate('TITLE.MESSAGE_SEND_LIST'); ?></h4>

                    <div id="user-count-message" style="margin-bottom: 10px;"></div>

                    <div class="form-group">
                        <label for="send_users"><?php echo $this->messageForm->send_users->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->send_users->getDescription(); ?>"></i>
                        <?php echo $this->messageForm->send_users; ?>
                        <div class="message-container"></div>
                    </div>

                    <div class="form-group">
                        <label for="send_roles"><?php echo $this->messageForm->send_roles->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->send_roles->getDescription(); ?>"></i>
                        <?php echo $this->messageForm->send_roles; ?>
                        <div class="message-container"></div>
                    </div>

                    <div class="form-group">
                        <label for="send_orgs"><?php echo $this->messageForm->send_orgs->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->send_orgs->getDescription(); ?>"></i>
                        <?php echo $this->messageForm->send_orgs; ?>
                        <div class="message-container"></div>
                    </div>

                </div>

                <div id="alert-wrapper" style="display: none;">

                    <h4><?php echo $this->translate('TITLE.MESSAGE_ALERT_ROUTES'); ?></h4>

                    <div class="form-group">
                        <label for="route"><?php echo $this->messageForm->route->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->route->getDescription(); ?>"></i>
                        <?php echo $this->messageForm->route; ?>
                        <div class="message-container"></div>
                    </div>

                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-message" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-message" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->messageForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_message"><?php echo $this->messageForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->messageForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_message"><?php echo $this->messageForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->messageForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Resource Form -->
