<div class="hero">
    <div class="hero-inner text-center">
        <div class="bg-white">
            <div class="content content-full overflow-hidden">
                <div class="py-4">
                    <!-- Error Header -->
                    <h1 class="display-1 text-city invisible" data-toggle="appear" data-class="animated flipInX">403</h1>
                    <h2 class="h3 font-w300 text-muted invisible mb-5" data-toggle="appear" data-class="animated fadeInUp">We are sorry but the page you are looking for was not found..</h2>
                    <!-- END Error Header -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-muted">
            <!-- Error Footer -->
            <p class="mb-1">
                Would you like to let us know about it?
            </p>
            <a class="link-fx" href="javascript:void(0)">Report it</a> or <a class="link-fx" href="be_pages_error_all.php">Go Back to Dashboard</a>
            <!-- END Error Footer -->
        </div>
    </div>
</div>
