<!-- Resource Form -->
<form id="resource-form" name="<?php echo $this->resourceForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->resourceForm->resource_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-resource"><?php echo $this->translate('TAB.RESOURCE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-resource"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-resource">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-resource" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.RESOURCE'); ?></h4>

                <div class="form-group">
                    <label for="module_name"><?php echo $this->resourceForm->module_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->resourceForm->module_name->getDescription(); ?>"></i>
                    <?php echo $this->resourceForm->module_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="resource_name"><?php echo $this->resourceForm->resource_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->resourceForm->resource_name->getDescription(); ?>"></i>
                    <?php echo $this->resourceForm->resource_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="resource_description"><?php echo $this->resourceForm->resource_description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->resourceForm->resource_description->getDescription(); ?>"></i>
                    <?php echo $this->resourceForm->resource_description; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="resource"><?php echo $this->resourceForm->resource->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->resourceForm->resource->getDescription(); ?>"></i>
                    <?php echo $this->resourceForm->resource; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="privilege"><?php echo $this->resourceForm->privilege->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->resourceForm->privilege->getDescription(); ?>"></i>
                    <?php echo $this->resourceForm->privilege; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-resource" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-resource" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->resourceForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_resource"><?php echo $this->resourceForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->resourceForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->resourceForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_resource"><?php echo $this->resourceForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->resourceForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Resource Form -->
