<?php echo $this->partial('admin/hero.phtml', ['one' => $this->one]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <!-- Resources -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">
                <div class="block-header block-header-default">
                    <h3 class="block-title">Resources</h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-resource" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#resourcesDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-control="#resourcesDT-container">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="resourcesDT-container" class="block-content block-content-full">
                    <table id="resourcesDT" style="width: 100%;" class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                </div>

            </div>
        </div>
    </div>

    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">
                <div class="block-header block-header-default">
                    <h3 class="block-title">Static Resources</h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#resourcesDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div class="block-content block-content-full">
                    <table id="staticResourcesDT" style="width: 100%;" class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                </div>

            </div>
        </div>
    </div>
    <!-- END Resources -->

</div>
<!-- END Page Content -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-resources-form" tabindex="-1" role="dialog" aria-labelledby="modal-resources-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-resource-header" class="block-title"><?php echo $this->translate('FORM.ADD_RESOURCE'); ?></h3>
                    <h3 id="edit-resource-header" class="block-title hide"><?php echo $this->translate('FORM.EDIT_RESOURCE'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('admin/resource_form.phtml', [ 'resourceForm' => $this->resourceForm ] ) ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CANCEL'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
