<!-- Resource Form -->
<form id="resource-form" name="<?php echo $this->resourceForm->getName(); ?>" class="" novalidate="novalidate">
    <div class="row"><div class="col-md-12 form-message"></div></div>
    <div class="py-3">
        <div class="hide">
            <?php echo $this->resourceForm->resource_id; ?>
        </div>
        <div class="form-group">
            <label for="module_name"><?php echo $this->resourceForm->module_name->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->resourceForm->module_name->getDescription(); ?>"></i>
            <?php echo $this->resourceForm->module_name; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="resource_name"><?php echo $this->resourceForm->resource_name->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->resourceForm->resource_name->getDescription(); ?>"></i>
            <?php echo $this->resourceForm->resource_name; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="resource_description"><?php echo $this->resourceForm->resource_description->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->resourceForm->resource_description->getDescription(); ?>"></i>
            <?php echo $this->resourceForm->resource_description; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="resource"><?php echo $this->resourceForm->resource->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->resourceForm->resource->getDescription(); ?>"></i>
            <?php echo $this->resourceForm->resource; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="privilege"><?php echo $this->resourceForm->privilege->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->resourceForm->privilege->getDescription(); ?>"></i>
            <?php echo $this->resourceForm->privilege; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <div class="custom-control custom-switch">
                <?php echo $this->resourceForm->active; ?>
                <label class="custom-control-label font-w400" for="active_resource"><?php echo $this->resourceForm->active->getLabel(); ?></label>
                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
                   title="<?php echo $this->resourceForm->active->getDescription(); ?>"></i>
            </div>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <div class="custom-control custom-switch">
                <?php echo $this->resourceForm->deleted; ?>
                <label class="custom-control-label font-w400" for="deleted_resource"><?php echo $this->resourceForm->deleted->getLabel(); ?></label>
                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
                   title="<?php echo $this->resourceForm->deleted->getDescription(); ?>"></i>
            </div>
            <div class="message-container"></div>
        </div>
        <div class="boiler-plate hide">
            <hr />
            <p><strong>Update Date: </strong><span class="update_date"></span></p>
            <p><strong>Last Updated By: </strong><span class="update_user_id"></span></p>
            <p><strong>Create Date: </strong><span class="create_date"></span></p>
            <p><strong>Created By: </strong><span class="create_user_id"></span></p>
        </div>

    </div>
</form>
<!-- END Resource Form -->
