<!-- Role Form -->
<form id="role-form" name="<?php echo $this->roleForm->getName(); ?>" class="" novalidate="novalidate">
    <div class="row"><div class="col-md-12 form-message"></div></div>
    <div class="py-3">
        <div class="hide">
            <?php echo $this->roleForm->role_id; ?>
        </div>
        <div class="form-group">
            <label for="priority"><?php echo $this->roleForm->priority->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->roleForm->priority->getDescription(); ?>"></i>
            <?php echo $this->roleForm->priority; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="role_name"><?php echo $this->roleForm->role_name->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->roleForm->role_name->getDescription(); ?>"></i>
            <?php echo $this->roleForm->role_name; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="parent_role_name"><?php echo $this->roleForm->parent_role_name->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->roleForm->parent_role_name->getDescription(); ?>"></i>
            <?php echo $this->roleForm->parent_role_name; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <label for="role_description"><?php echo $this->roleForm->role_description->getLabel(); ?></label>
            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
               title="<?php echo $this->roleForm->role_description->getDescription(); ?>"></i>
            <?php echo $this->roleForm->role_description; ?>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <div class="custom-control custom-switch">
                <?php echo $this->roleForm->active; ?>
                <label class="custom-control-label font-w400" for="active_role"><?php echo $this->roleForm->active->getLabel(); ?></label>
                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
                   title="<?php echo $this->roleForm->active->getDescription(); ?>"></i>
            </div>
            <div class="message-container"></div>
        </div>
        <div class="form-group">
            <div class="custom-control custom-switch">
                <?php echo $this->roleForm->deleted; ?>
                <label class="custom-control-label font-w400" for="deleted_role"><?php echo $this->roleForm->deleted->getLabel(); ?></label>
                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="bottom"
                   title="<?php echo $this->roleForm->deleted->getDescription(); ?>"></i>
            </div>
            <div class="message-container"></div>
        </div>
        <div class="boiler-plate hide">
            <hr />
            <p><strong>Update Date: </strong><span class="update_date"></span></p>
            <p><strong>Last Updated By: </strong><span class="update_user_id"></span></p>
            <p><strong>Create Date: </strong><span class="create_date"></span></p>
            <p><strong>Created By: </strong><span class="create_user_id"></span></p>
        </div>

    </div>
</form>
<!-- END Role Form -->
