<!-- Role Form -->
<form id="role-form" name="<?php echo $this->roleForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->roleForm->role_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>


    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-role"><?php echo $this->translate('TAB.ROLE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-role"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-role">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-role" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.ROLE'); ?></h4>

                <div class="form-group">
                    <label for="priority"><?php echo $this->roleForm->priority->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->roleForm->priority->getDescription(); ?>"></i>
                    <?php echo $this->roleForm->priority; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="role_name"><?php echo $this->roleForm->role_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->roleForm->role_name->getDescription(); ?>"></i>
                    <?php echo $this->roleForm->role_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="parent_role_name"><?php echo $this->roleForm->parent_role_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->roleForm->parent_role_name->getDescription(); ?>"></i>
                    <?php echo $this->roleForm->parent_role_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="role_description"><?php echo $this->roleForm->role_description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->roleForm->role_description->getDescription(); ?>"></i>
                    <?php echo $this->roleForm->role_description; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-role" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-role" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->roleForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_role"><?php echo $this->roleForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->roleForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->roleForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_role"><?php echo $this->roleForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->roleForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Role Form -->
