<?php echo $this->partial('admin/hero.phtml', ['one' => $this->one]); ?>

<!-- Page Content -->
<div class="content content-narrow">
    <!-- Stats -->
    <div class="row">
        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Visitors</div>
                    <div class="font-size-h2 font-w400 text-dark">120,580</div>
                </div>
            </a>
        </div>
        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Sales</div>
                    <div class="font-size-h2 font-w400 text-dark">150</div>
                </div>
            </a>
        </div>
        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Earnings</div>
                    <div class="font-size-h2 font-w400 text-dark">$3,200</div>
                </div>
            </a>
        </div>
        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Avg Sale</div>
                    <div class="font-size-h2 font-w400 text-dark">$21</div>
                </div>
            </a>
        </div>
    </div>
    <!-- END Stats -->

    <!-- Orgs -->
    <div class="row row-deck">
        <!-- Orgs -->
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">
                <div class="block-header block-header-default">
                    <h3 class="block-title">Latest Customers</h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-toggle="block-option" data-action="state_toggle" data-action-mode="demo">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content block-content-full">
                    <table class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0">
                        <thead>
                        <tr class="text-uppercase">
                            <th class="font-w700" style="width: 80px;">ID</th>
                            <th class="d-none d-sm-table-cell font-w700 text-center" style="width: 100px;">Photo</th>
                            <th class="font-w700">Name</th>
                            <th class="d-none d-sm-table-cell font-w700 text-center" style="width: 80px;">Orders</th>
                            <th class="font-w700 text-center" style="width: 60px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'male', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('male'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">5</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'female', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('female'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">14</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'male', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('male'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">15</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'female', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('female'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">36</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'male', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('male'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">3</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'female', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('female'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">1</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="font-w600">#01368</span>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <?php $this->one->get_avatar(0, 'male', 32); ?>
                            </td>
                            <td class="font-w600">
                                <?php $this->one->get_name('male'); ?>
                            </td>
                            <td class="d-none d-sm-table-cell text-center">
                                <a class="link-fx font-w600" href="javascript:void(0)">12</a>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="left" title="Edit">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END Orgs -->
    </div>
    <!-- END Orgs -->
</div>
<!-- END Page Content -->
