<!-- Rule Form -->
<form id="rule-form" name="<?php echo $this->ruleForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->ruleForm->rule_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-rule"><?php echo $this->translate('TAB.RESOURCE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-rule"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-rule">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-rule" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.RULE'); ?></h4>

                <div class="form-group">
                    <label for="priority"><?php echo $this->ruleForm->priority->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->priority->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->priority; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="rule_name"><?php echo $this->ruleForm->rule_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->rule_name->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->rule_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="rule_description"><?php echo $this->ruleForm->rule_description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->rule_description->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->rule_description; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="permission"><?php echo $this->ruleForm->permission->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->permission->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->permission; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="resource"><?php echo $this->ruleForm->resource->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->resource->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->resource; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="privilege"><?php echo $this->ruleForm->privilege->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->privilege->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->privilege; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="assertion"><?php echo $this->ruleForm->assertion->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->assertion->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->assertion; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="role"><?php echo $this->ruleForm->role->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->ruleForm->role->getDescription(); ?>"></i>
                    <?php echo $this->ruleForm->role; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-rule" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-rule" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->ruleForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_rule"><?php echo $this->ruleForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->ruleForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->ruleForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_rule"><?php echo $this->ruleForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->ruleForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Rule Form -->
