<!-- Register Form -->
<form id="register-form" name="<?php echo $this->registerForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-register"><?php echo $this->translate('TAB.REGISTRATION'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-platform-register"><?php echo $this->translate('TAB.PLATFORM_DETAIL'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-register"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-register">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-register" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.REGISTER'); ?></h4>
                <p><?php echo $this->translate('TEXT.REGISTER'); ?></p>

                <div class="hide">
                    <?php echo $this->registerForm->register_id; ?>
                </div>
                <div class="form-group">
                    <label for="first_name"><?php echo $this->registerForm->first_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->first_name->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->first_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="last_name"><?php echo $this->registerForm->last_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->last_name->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->last_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="company_name"><?php echo $this->registerForm->company_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->company_name->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->company_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="email"><?php echo $this->registerForm->email->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->email->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->email; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="country"><?php echo $this->registerForm->country->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->country->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->country; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->registerForm->subscribe; ?>
                        <label class="custom-control-label font-w400" for="subscribe_register"><?php echo $this->registerForm->subscribe->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->registerForm->subscribe->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-platform-register" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.PLATFORM_DETAILS'); ?></h4>
                <p><?php echo $this->translate('TEXT.PLATFORM_DETAILS'); ?></p>

                <div class="form-group">
                    <label for="version"><?php echo $this->registerForm->version->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->version->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->version; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="platform"><?php echo $this->registerForm->platform->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->platform->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->platform; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="host"><?php echo $this->registerForm->host->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->host->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->host; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="framework"><?php echo $this->registerForm->framework->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->registerForm->framework->getDescription(); ?>"></i>
                    <?php echo $this->registerForm->framework; ?>
                    <div class="message-container"></div>
                </div>


            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-register" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-register" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->registerForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_register"><?php echo $this->registerForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->registerForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->registerForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_register"><?php echo $this->registerForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->registerForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Register Form -->
