<div class="shortcode_title">
    <a class="btn" href="#">Elements</a>
    <h1>Source Code</h1>
    <p>Welcome to Docy ! Get familiar with the Docy products and explore their features, guides, tips and tools.</p>
</div>

<h4 class="c_head load-order-2">HTML Code Blocks</h4>
<p>From a group of elements with one parent. Same as first one, but use this method if you are creating a popup from a list of elements in one container. Note that this method does not enable gallery mode, it just reduces the number of click event handlers; each item will be opened as a single popup. If you wish to enable gallery, add the <code>gallery:{enabled:true}</code> option.</p>
<div class="highlight">
    <pre>
        <code class="language-html" data-lang="html">For example, <span class="nt">&lt;code&gt;</span><span class="nt">&lt;</span>section<span class="ni">&gt;</span><span class="nt">&lt;/code&gt;</span> should be wrapped as inline.</code>
    </pre>
</div>
<div class="highlight">
    <pre>
        <code class="language-html" data-lang="html">
            &lt;p&gt;
                <mark>Highlight</mark>
                text with HTML &lt;mark&gt; tag
            &lt;p&gt;
        </code>
    </pre>
    <pre>
        <code class="language-html" data-lang="html">
            &lt;ul class="list-unstyled f_social_icon"&gt;
                &lt;li&gt;&lt;a href="#"&gt;&lt;i class="social_facebook"&gt;&lt;i&gt;&lt;a&gt;&lt;li&gt;
                &lt;li&gt;&lt;a href="#"&gt;&lt;i class="social_twitter"&gt;&lt;i&gt;&lt;a&gt;&lt;li&gt;
                &lt;li&gt;&lt;a href="#"&gt;&lt;i class="social_vimeo"&gt;&lt;i&gt;&lt;a&gt;&lt;li&gt;
                &lt;li&gt;&lt;a href="#"&gt;&lt;i class="social_linkedin"&gt;&lt;i&gt;&lt;a&gt;&lt;li&gt;
            &lt;ul&gt;
        </code>
    </pre>
</div>

<h4 class="c_head load-order-2">CSS Source Code</h4>
<div class="highlight">
    <pre>
        <code class="language-javascript" data-lang="javascript">
            html {
              height: 100%;
            }
            a {
              text-decoration: none;
              transition: all 0.3s ease-in-out;
            }
            a:hover, a:focus {
              text-decoration: none;
              outline: none;
              color: #10b3d6;
            }
            body {
              line-height: 24px;
              font-size: 16px;
              height: 100%;
              font-family: "Roboto", sans-serif;
              font-weight: 400;
              color: #6b707f;
            }
        </code>
    </pre>
</div>

<h4 class="c_head load-order-2">JavaScript Code</h4>
<div class="highlight">
    <pre>
        <code class="language-javascript" data-lang="javascript">
            $(".img_popup").each(function () {
                 $(".img_popup").magnificPopup({
                     type: 'image',
                     closeOnContentClick: true,
                     closeBtnInside: false,
                     fixedContentPos: true,
                     removalDelay: 300,
                     mainClass: 'mfp-no-margins mfp-with-zoom',
                     image: {
                         enabled: true,
                         navigateByImgClick: true,
                         preload: [0, 1]
                     }
                 });
             })
        </code>
    </pre>
</div>

<h4 id="php-code" class="c_head load-order-2">PHP Source Code</h4>
<div class="highlight">
    <pre>
        <code class="language-php" data-lang="php">
            function docy_setup() {
                load_theme_textdomain( 'docy', get_template_directory() . '/languages' );

                // Add default posts and comments RSS feed links to head.
                add_theme_support( 'automatic-feed-links' );

                // Enable excerpt support for page
                add_post_type_support( 'page', 'excerpt' );

                // Enable WooCommerce Support
                add_theme_support( 'woocommerce' );

                add_theme_support( 'title-tag' );

                /*
                 * Enable support for Post Thumbnails on posts and pages.
                 *
                 * @link https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
                 */
                add_theme_support( 'post-thumbnails' );
                add_theme_support( 'post-formats', array( 'audio', 'video', 'quote', 'link' ) );

                // This theme uses wp_nav_menu() in one location.
                register_nav_menus( array(
                    'main_menu'   => esc_html__( 'Main menu', 'docy' ),
                    'overlay_menu'   => esc_html__( 'Overlay menu', 'docy' ),
                ));
            }
            add_action( 'after_setup_theme', 'docy_setup' );
        </code>
    </pre>
</div>