<footer class="forum_footer_area">
    <div class="container">
        <div class="forum_footer_inner">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <aside class="f_widget ab_wd">
                        <a href="#"><img src="/assets/docy/img/forum/forum-footer-logo.png" alt="">SpiderThemes © 2021</a>
                        <select class="nice_select">
                            <option value="1">English</option>
                            <option value="2">Bengali</option>
                            <option value="3">Euro</option>
                            <option value="4">Ind</option>
                        </select>
                    </aside>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <aside class="f_widget f_link_wd">
                        <ul class="navbar-nav">
                            <li><a href="#">About </a></li>
                            <li><a href="#">Privacy and Policy</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <aside class="f_widget f_link_wd">
                        <ul class="navbar-nav">
                            <li><a href="#">AdChoices </a></li>
                            <li><a href="#">Create ad</a></li>
                            <li><a href="#">Create page</a></li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <aside class="f_widget f_link_wd">
                        <ul class="navbar-nav">
                            <li><a href="#">Tram and Conditions </a></li>
                            <li><a href="#">Cookies</a></li>
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</footer>