<section class="doc_documentation_area" id="sticky_doc">
    <div class="overlay_bg"></div>
    <div class="container-fluid pl-60 pr-60">
        <div class="row">

            <div class="col-lg-2 col-md-2 doc_mobile_menu display_none">
                <?php echo $this->partial( 'docleftmenu.phtml' ); ?>
            </div>

            <div class="col-lg-8 col-md-8 doc-middle-content">

                <div id="post" class="shortcode_info documentation_info">

                    <article class="shortcode_text">

                        <?php echo $this->partial( 'docarticle.phtml' ); ?>

                        <footer>
                            <?php if ( isset( $this->showFeedback) ): ?>
                            <div class="border_bottom"></div>
                            <div class="row feedback_link">
                                <div class="col-lg-6">
                                    <h6><i class="icon_mail_alt"></i>Still stuck? <a href="#" data-toggle="modal" data-target="#exampleModal3">How can we help?</a></h6>
                                </div>
                                <div class="col-lg-6">
                                    <p>Was this page helpful? <a href="#" class="h_btn">Yes</a><a href="#" class="h_btn red">No</a></p>
                                </div>
                            </div>
                            <?php endif; ?>
                        </footer>

                    </article>

                </div><!-- #post -->

                <?php if ( isset( $this->showTopics) ): ?>
                <div class="row topic_item_tabs inner_tab_list">
                    <div class="col-lg-6">
                        <div class="topic_list_item">
                            <h4>Related articles</h4>
                            <ul class="navbar-nav">
                                <li><a href="#"><i class="icon_document_alt"></i>Accordions Widget</a></li>
                                <li><a href="#"><i class="icon_document_alt"></i>Notice / Message Widget</a>
                                </li>
                                <li><a href="#"><i class="icon_document_alt"></i>Cheatsheet</a></li>
                                <li><a href="#"><i class="icon_document_alt"></i>Image Hotspots Widget</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="topic_list_item">
                            <h4>Recently viewed articles</h4>
                            <ul class="navbar-nav">
                                <li><a href="#"><i class="icon_document_alt"></i>Tabs Widget</a></li>
                                <li><a href="#"><i class="icon_document_alt"></i>Notice / Message Widget</a>
                                </li>
                                <li><a href="#"><i class="icon_document_alt"></i>Cheatsheet</a></li>
                                <li><a href="#"><i class="icon_document_alt"></i>Image Hotspots Widget</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <?php if ( isset( $this->showComments) ): ?>
                <div class="comment_inner">
                    <h2 class="c_head">3 Comment</h2>
                    <ul class="comment_box list-unstyled">
                        <li class="post_comment">
                            <div class="media comment_author">
                                <img class="img_rounded" src="/assets/docy/img/blog-single/comment_01.jpg" alt="">
                                <div class="media-body">
                                    <div class="comment_info">
                                        <h3>Issac Wise</h3>
                                        <div class="comment_date">July 3, 2020 at 2:14 pm</div>
                                    </div>
                                    <p>Wouldn’t it be better practice to use get_the_title(..) in this case?
                                        directly accessing the post object’s data member would bypass
                                        applying filters and enforcing protected and private settings,
                                        unless that’s explicitly desired.</p>
                                    <a href="#" class="comment_reply">Reply <i class="arrow_right"></i></a>
                                </div>
                            </div>
                            <ul class="list-unstyled reply_comment">
                                <li>
                                    <div class="media comment_author">
                                        <img class="img_rounded" src="/assets/docy/img/blog-single/comment_02.jpg"
                                             alt="">
                                        <div class="media-body">
                                            <div class="comment_info">
                                                <h3>Hans Down</h3>
                                                <div class="comment_date">44 mins ago</div>
                                            </div>
                                            <p>Thenks Demo User for Wouldn’t it be better practice to use
                                                get_the_title.</p>
                                            <a href="#" class="comment_reply">Reply <i
                                                    class="arrow_right"></i></a>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="media comment_author">
                                        <img class="img_rounded" src="/assets/docy/img/blog-single/comment_03.jpg"
                                             alt="">
                                        <div class="media-body">
                                            <div class="comment_info">
                                                <h3>Hans Down</h3>
                                                <div class="comment_date">44 mins ago</div>
                                            </div>
                                            <p>Dropped a clanger up the kyver easy peasy vagabond victoria
                                                sponge Charles tinkety tonk old fruit argy.!</p>
                                            <a href="#" class="comment_reply">Reply <i
                                                    class="arrow_right"></i></a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="post_comment">
                            <div class="media comment_author">
                                <img class="img_rounded" src="/assets/docy/img/blog-single/comment_01.jpg" alt="">
                                <div class="media-body">
                                    <div class="comment_info">
                                        <h3>Chauffina Carr</h3>
                                        <div class="comment_date">04 mins ago</div>
                                    </div>
                                    <p>Wouldn’t it be better practice to use get_the_title(..) in this case?
                                        directly accessing the post object’s data member would bypass
                                        applying filters and enforcing protected and private settings,
                                        unless that’s explicitly desired.</p>
                                    <a href="#" class="comment_reply">Reply <i class="arrow_right"></i></a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <?php endif; ?>

                <?php if ( isset( $this->showCommentForm) ): ?>
                <div class="blog_comment_box topic_comment">
                    <h2 class="c_head">Leave a Reply</h2>
                    <p>Your email address will not be published. Required fields are marked *</p>
                    <form class="get_quote_form row" action="#" method="post">
                        <div class="col-md-6 form-group">
                            <input type="text" class="form-control" id="name" required>
                            <label class="floating-label">Full Name *</label>
                        </div>
                        <div class="col-md-6 form-group">
                            <input type="email" class="form-control" id="email" required>
                            <label class="floating-label">Email *</label>
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="web" required>
                            <label class="floating-label">Website (Optional)</label>
                        </div>
                        <div class="col-md-12 form-group">
                            <textarea class="form-control message" required></textarea>
                            <label class="floating-label">Comment type...</label>
                        </div>
                        <div class="col-md-12 form-group check_input">
                            <input type="checkbox" id="fruit1" name="fruit-1" value="Apple">
                            <label for="fruit1">Save my name, email, and website in this browser for the
                                next time I comment.</label>
                        </div>
                        <div class="col-md-12 form-group"><button class="btn action_btn thm_btn"
                                                                  type="submit">Post
                                Comment</button></div>
                    </form>
                </div>
                <?php endif; ?>

            </div><!-- .doc-middle-content -->

            <div class="col-lg-2 col-md-2 doc_right_mobile_menu">
                <div class="open_icon" id="right">
                    <i class="arrow_carrot-left"></i>
                    <i class="arrow_carrot-right"></i>
                </div>
                <div class="doc_rightsidebar scroll">
                    <div class="pageSideSection">
                        <!-- select id="mySelect" name="os">
                            <option value="windows" data-content="<i class='fab fa-windows'></i> Windows">Windows</option>
                            <option value="ios" data-content="<i class='fab fa-apple'></i> Ios">Ios</option>
                            <option value="linux" data-content="<i class='fab fa-linux'></i> Linux">Linux</option>
                        </select -->
                        <div id="font-switcher" class="d-flex justify-content-between align-items-center">
                            <div id="rvfs-controllers" class="fontsize-controllers group"></div>
                            <a href="javascript:window.print()" class="print"><i class="icon_printer"></i></a>
                        </div>
                        <div class="table-of-content">
                            <h6><i class="icon_ul"></i> CONTENTS</h6>
                            <nav class="list-unstyled doc_menu" id="navbar-example3">
                            </nav>
                        </div>
                    </div>
                </div>
            </div><!-- .doc_right_mobile_menu -->

        </div><!-- .row -->
    </div>
</section>