<?php echo $this->partial('admin/hero.phtml', [ 'template' => $this->template ]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>

    <!-- Content Management -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.CONTENT_PAGES'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-page" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#pagesDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#pagesDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="pagesDT-container">
                    <div class="block-content block-content-full">
                        <table id="pagesDT" style="width: 100%;" class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Content Management -->

    <!-- Content Management -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.DEFAULT_PAGE'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-page" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#pagesDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#route-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="route-container">
                    <div class="block-content block-content-full">
                        <?php echo $this->partial('admin/route_form.phtml', [ 'routeForm' => $this->routeForm ] ) ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Content Management -->

</div>

<!-- END Page Content -->

<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-pages-form" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modal-pages-form" aria-hidden="true">
    <div class="modal-dialog" role="document" style="min-width:80%;">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-page-header" class="block-title"><?php echo $this->translate('FORM.ADD_PAGE'); ?></h3>
                    <h3 id="edit-page-header" class="block-title hide"><?php echo $this->translate('FORM.EDIT_PAGE'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('admin/page_form.phtml', [ 'pageForm' => $this->pageForm ] ) ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE'); ?>
                    </button>
                    <div class="custom-control custom-switch save-version">
                        <input type="checkbox" name="save-version" id="save-version" value="1" class="custom-control-input">
                        <label class="custom-control-label font-w400" for="save-version"><?php echo $this->translate('FORM.SAVE_VERSION'); ?></label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
