<!-- Resource Form -->
<form id="<?php echo $this->pageForm->getId(); ?>" name="<?php echo $this->pageForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->pageForm->page_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div id="cms-tabs" class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-page-content"><?php echo $this->translate('TAB.CONTENT'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-scripts"><?php echo $this->translate('TAB.SCRIPTS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-settings"><?php echo $this->translate('TAB.SETTINGS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-meta"><?php echo $this->translate('TAB.META'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-links"><?php echo $this->translate('TAB.LINKS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">

            <div class="tab-pane fade show active" id="btabs-animated-fade-page-content" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.PAGE'); ?></h4>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name"><?php echo $this->pageForm->name->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->name->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->name; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="key"><?php echo $this->pageForm->key->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->key->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->key; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="content"><?php echo $this->pageForm->content->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->content->getDescription(); ?>"></i>
                            <hr />
                            <?php echo $this->pageForm->content; ?>
                            <hr />
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="category"><?php echo $this->pageForm->category->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->category->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->category; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="type"><?php echo $this->pageForm->type->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->type->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->type; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-scripts" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SCRIPTS'); ?></h4>

                <div class="form-group">
                    <label for="css"><?php echo $this->pageForm->css->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->css->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->css; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="javascript"><?php echo $this->pageForm->javascript->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->javascript->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->javascript; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="styles"><?php echo $this->pageForm->styles->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->styles->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->styles; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="scripts"><?php echo $this->pageForm->scripts->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->scripts->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->scripts; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-settings" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <label for="title"><?php echo $this->pageForm->title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->title->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->title; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-meta" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.META'); ?></h4>


            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-links" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.LINKS'); ?></h4>


            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->pageForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_page"><?php echo $this->pageForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->pageForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->pageForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_page"><?php echo $this->pageForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->pageForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>

        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Resource Form -->
