<!-- Page Form -->
<form id="<?php echo $this->pageForm->getId(); ?>" name="<?php echo $this->pageForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div id="cms-tabs" class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-page-content"><?php echo $this->translate('TAB.CONTENT'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-options"><?php echo $this->translate('TAB.OPTIONS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-head-links"><?php echo $this->translate('TAB.HEAD_LINKS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-head-scripts"><?php echo $this->translate('TAB.HEAD_SCRIPTS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-inline-scripts"><?php echo $this->translate('TAB.INLINE_SCRIPTS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-css-js"><?php echo $this->translate('TAB.PAGE_CSS_JS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-meta"><?php echo $this->translate('TAB.META'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">

            <div class="tab-pane fade show active" id="btabs-animated-fade-page-content" role="tabpanel">
                <?php echo $this->pageForm->page_id; ?>
                <h4><?php echo $this->translate('TITLE.PAGE'); ?></h4>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="name"><?php echo $this->pageForm->name->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->name->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->name; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="key"><?php echo $this->pageForm->key->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->key->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->key; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="theme"><?php echo $this->pageForm->theme->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->theme->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->theme; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="layout"><?php echo $this->pageForm->layout->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->layout->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->layout; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="locale"><?php echo $this->pageForm->locale->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->locale->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->locale; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="type"><?php echo $this->pageForm->type->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->type->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->type; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="category"><?php echo $this->pageForm->category->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->category->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->category; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="templates"><?php echo $this->pageForm->templates->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                               title="<?php echo $this->pageForm->templates->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->templates; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="form-group">
                            <label for="templates">&nbsp;</label>
                            <button id="insert-text" type="button" class="btn btn-alt-light"><i class="fas fa-file-import"></i></button>
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">


                        <div id="cms-tabs-editors" class="block">
                            <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
                                <li class="nav-item">
                                    <a id="codeview" class="nav-link active" href="#btabs-animated-fade-codeview"><?php echo $this->translate('TAB.CODEVIEW'); ?></a>
                                </li>
                                <li class="nav-item">
                                    <a id="editview" class="nav-link" href="#btabs-animated-fade-editview"><?php echo $this->translate('TAB.EDITVIEW'); ?></a>
                                </li>
                            </ul>
                            <div class="block-content tab-content overflow-hidden">
                                <div class="tab-pane fade show active" id="btabs-animated-fade-codeview" role="tabpanel">
                                    <div class="form-group" style="position: relative;">
                                        <div id="ace-content" style=""></div>
                                        <hr />
                                        <div class="message-container"></div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="btabs-animated-fade-editview" role="tabpanel">
                                    <div class="form-group" style="position: relative;">
                                        <textarea id="ck-content" name="ck-content" class="form-control" style="width:100%; min-height:800px;"></textarea>
                                        <hr />
                                        <div class="message-container"></div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-options" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.OPTIONS'); ?></h4>
                <div id="options-container" class="row"></div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-head-links" role="tabpanel">
                <h4>
                    <?php echo $this->translate('TITLE.HEAD_LINKS'); ?>
                    <span id="create-link" data-target="#head-links-container">
                        <i class="si si-plus" title="<?php echo $this->translate('INFO.CREATE_LINK'); ?>"
                           data-toggle="tooltip" data-placement="left" data-animation="true"></i>
                    </span>
                </h4>
                <div id="head-links-container"></div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-head-scripts" role="tabpanel">
                <h4>
                    <?php echo $this->translate('TITLE.HEAD_SCRIPTS'); ?>
                    <span id="create-head-script" data-target="#head-scripts-container">
                        <i class="si si-plus" title="<?php echo $this->translate('INFO.CREATE_SCRIPT'); ?>"
                           data-toggle="tooltip" data-placement="left" data-animation="true"></i>
                    </span>
                </h4>
                <div id="head-scripts-container"></div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-inline-scripts" role="tabpanel">
                <h4>
                    <?php echo $this->translate('TITLE.INLINE_SCRIPTS'); ?>
                    <span id="create-inline-script" data-target="#inline-scripts-container">
                        <i class="si si-plus" title="<?php echo $this->translate('INFO.CREATE_SCRIPT'); ?>"
                           data-toggle="tooltip" data-placement="left" data-animation="true"></i>
                    </span>
                </h4>
                <div id="inline-scripts-container"></div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-css-js" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SCRIPTS'); ?></h4>

                <div class="form-group">
                    <label for="styles"><?php echo $this->pageForm->styles->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->styles->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->styles; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="scripts"><?php echo $this->pageForm->scripts->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->scripts->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->scripts; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-meta" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.META_CHARSET'); ?></h4>
                <div id="meta-charset-container" class="row meta-container" data-type="charset"></div>
                <hr />

                <h4><?php echo $this->translate('TITLE.META_NAME'); ?></h4>
                <div id="meta-name-container" class="row meta-container" data-type="name"></div>
                <hr />

                <h4><?php echo $this->translate('TITLE.META_OPENGRAPH'); ?></h4>
                <div id="meta-opengraph-container" class="row meta-container" data-type="opengraph"></div>
            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->pageForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_page"><?php echo $this->pageForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                           title="<?php echo $this->pageForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->pageForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_page"><?php echo $this->pageForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                           title="<?php echo $this->pageForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>

        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Page Form -->
