<!-- Resource Form -->
<form id="<?php echo $this->pageForm->getId(); ?>" name="<?php echo $this->pageForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->pageForm->page_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-page-content"><?php echo $this->translate('TAB.CONTENT'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-scripts"><?php echo $this->translate('TAB.SCRIPTS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-meta"><?php echo $this->translate('TAB.META'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-page-og"><?php echo $this->translate('TAB.OG_PAGE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-og-image"><?php echo $this->translate('TAB.OG_IMAGE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-og-video"><?php echo $this->translate('TAB.OG_VIDEO'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-page"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-page">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-page-content" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.PAGE'); ?></h4>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name"><?php echo $this->pageForm->name->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->name->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->name; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="key"><?php echo $this->pageForm->key->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->key->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->key; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="content"><?php echo $this->pageForm->content->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->content->getDescription(); ?>"></i>
                            <hr />
                            <?php echo $this->pageForm->content; ?>
                            <hr />
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="category"><?php echo $this->pageForm->category->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->category->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->category; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="type"><?php echo $this->pageForm->type->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                               title="<?php echo $this->pageForm->type->getDescription(); ?>"></i>
                            <?php echo $this->pageForm->type; ?>
                            <div class="message-container"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-pane fade" id="btabs-animated-fade-page-scripts" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SCRIPTS'); ?></h4>

                <div class="form-group">
                    <label for="css"><?php echo $this->pageForm->css->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->css->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->css; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="javascript"><?php echo $this->pageForm->javascript->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->javascript->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->javascript; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="styles"><?php echo $this->pageForm->styles->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->styles->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->styles; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="scripts"><?php echo $this->pageForm->scripts->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->scripts->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->scripts; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-meta" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.META'); ?></h4>

                <div class="form-group">
                    <label for="meta_title"><?php echo $this->pageForm->meta_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->meta_title->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->meta_title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="meta_description"><?php echo $this->pageForm->meta_description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->meta_description->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->meta_description; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-page-og" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.OPEN_GRAPH'); ?></h4>

                <div class="form-group">
                    <label for="og_title"><?php echo $this->pageForm->og_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_title->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_description"><?php echo $this->pageForm->og_description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_description->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_description; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_url"><?php echo $this->pageForm->og_url->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_url->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_url; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_type"><?php echo $this->pageForm->og_type->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_type->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_type; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_locale"><?php echo $this->pageForm->og_locale->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_locale->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_locale; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-og-image" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.OPEN_GRAPH_IMAGE'); ?></h4>

                <div class="form-group">
                    <label for="og_image"><?php echo $this->pageForm->og_image->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_image->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_image; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_image_alt"><?php echo $this->pageForm->og_image_alt->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_image_alt->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_image_alt; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_url"><?php echo $this->pageForm->og_url->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_url->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_url; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_image_type"><?php echo $this->pageForm->og_image_type->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_image_type->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_image_type; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_image_height"><?php echo $this->pageForm->og_image_height->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_image_height->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_image_height; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_image_width"><?php echo $this->pageForm->og_image_width->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_image_width->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_image_width; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-og-video" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.OPEN_GRAPH_VIDEO'); ?></h4>

                <div class="form-group">
                    <label for="og_video"><?php echo $this->pageForm->og_video->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_video->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_video; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_video_type"><?php echo $this->pageForm->og_video_type->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_video_type->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_video_type; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_video_height"><?php echo $this->pageForm->og_video_height->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_video_height->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_video_height; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="og_video_width"><?php echo $this->pageForm->og_video_width->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->pageForm->og_video_width->getDescription(); ?>"></i>
                    <?php echo $this->pageForm->og_video_width; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-page" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-page" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->pageForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_page"><?php echo $this->pageForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->pageForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->pageForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_page"><?php echo $this->pageForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->pageForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Resource Form -->
