<!-- Page Form -->
<form id="<?php echo $this->routeForm->getId(); ?>" name="<?php echo $this->routeForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="route_page_id"><?php echo $this->routeForm->route_page_id->getLabel(); ?></label>
                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left" data-animation="true"
                   title="<?php echo $this->routeForm->route_page_id->getDescription(); ?>"></i>
                <?php echo $this->routeForm->route_page_id; ?>
                <div class="message-container"></div>
            </div>
        </div>
    </div>

</form>
<!-- END Page Form -->
