<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top quick-nav">
    <div class="container">
        <a href="/manual"><img class="img-logo" src="/assets/manual/img/ZF1-Future-logo-small-white.png" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="#!"><i class="fas fa-arrow-circle-down"></i>About</a></li>
                <li class="nav-item"><a class="nav-link" href="#!"><i class="fas fa-arrow-circle-up"></i>Install</a></li>
                <li class="nav-item active"><a class="nav-link" href="#!"><i class="fas fa-arrow-circle-left"></i>Documentation</a></li>
                <li class="nav-item"><a class="nav-link" href="#!"><i class="fas fa-arrow-circle-right"></i>Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="#!"><i class="fas fa-arrow-circle-left"></i>Participate</a></li>
            </ul>
        </div>
    </div>
</nav>
<header class="section gradient-sage-to-forest">
    <div class="container">
        <h1>Documentation</h1>
    </div>
</header>
<!-- Page content-->

<div class="row">

    <nav class="col-md-2">
        <div class="container">
            <?php echo $this->mainNav(); ?>
        </div>
    </nav>

    <article class="col-md-7">
        <div class="container">
            <?php echo $this->article(); ?>
        </div>
    </article>

    <nav class="col-md-3">
        <div class="container">
            <?php echo $this->subNav(); ?>
        </div>
    </nav>

</div>

<!-- Footer content-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img class="img-logo" src="/assets/manual/img/ZF1-Future-logo-small-white.png" />
            </div>
            <div class="col-md-2">
                <ul class="footer-menu">
                    <li><strong>About</strong></li>
                    <li><a href="">Lorem</a></li>
                    <li><a href="">Ipsum</a></li>
                    <li><a href="">Dolor</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <ul class="footer-menu">
                    <li><strong>Install</strong></li>
                    <li><a href="">Ipsum</a></li>
                    <li><a href="">Dolor</a></li>
                    <li><a href="">Sit</a></li>
                    <li><a href="">Amet</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <ul class="footer-menu">
                    <li><strong>Documentation</strong></li>
                    <li><a href="">Lorem</a></li>
                    <li><a href="">Ipsum</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <ul class="footer-menu">
                    <li><strong>Participate</strong></li>
                    <li><a href="">Lorem</a></li>
                    <li><a href="">Ipsum</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>