<!-- Page Content -->
<div class="bg-image" style="background-image: url('<?php echo $this->one->assets_folder; ?>/media/photos/photo34@2x.jpg');">
    <div class="hero-static bg-black-50">
        <div class="content">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-4">
                    <!-- Unlock Block -->
                    <div class="block block-themed mb-0">
                        <div class="block-header bg-danger">
                            <h3 class="block-title">Account Locked</h3>
                            <div class="block-options">
                                <a class="btn-block-option js-tooltip-enabled" href="op_auth_signin.php" data-toggle="tooltip" data-placement="left" title="" data-original-title="Sign In with another account">
                                    <i class="fa fa-sign-in-alt"></i>
                                </a>
                            </div>
                        </div>
                        <div class="block-content">
                            <div class="p-sm-3 px-lg-4 py-lg-5 text-center">
                                <img class="img-avatar img-avatar96" src="assets/media/avatars/avatar10.jpg" alt="">
                                <p class="font-w600 my-2">
                                    user@example.com
                                </p>
                                <!-- Unlock Form -->
                                <form class="js-validation-lock" action="be_pages_auth_all.php" method="POST" novalidate="novalidate">
                                    <div class="form-group py-3">
                                        <input type="password" class="form-control form-control-lg form-control-alt" id="lock-password" name="lock-password" placeholder="Password..">
                                    </div>
                                    <div class="form-group row justify-content-center">
                                        <div class="col-md-6 col-xl-5">
                                            <button type="submit" class="btn btn-block btn-light">
                                                <i class="fa fa-fw fa-lock-open mr-1"></i> Unlock
                                            </button>
                                        </div>
                                    </div>
                                </form>
                                <!-- END Unlock Form -->
                            </div>
                        </div>
                    </div>
                    <!-- END Unlock Block -->
                </div>
            </div>
        </div>
        <div class="content content-full font-size-sm text-white text-center">
            <strong><?php echo $this->one->name . ' ' . $this->one->version; ?></strong> &copy; <span data-toggle="year-copy"></span>
        </div>
    </div>
</div>
<!-- END Page Content -->

