<!-- User Form -->
<form id="address-form" name="<?php echo $this->addressForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->addressForm->entity; ?>
        <?php echo $this->addressForm->entity_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <div class="form-group py3">
        <label for="address_id"><?php echo $this->addressForm->address_id->getLabel(); ?></label>
        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
           title="<?php echo $this->addressForm->address_id->getDescription(); ?>"></i>
        <?php echo $this->addressForm->address_id; ?>
        <div class="message-container"></div>
    </div>

    <div class="overlay-container">

        <!-- Block Tabs Animated Fade -->
        <div class="block">
            <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" href="#btabs-animated-fade-address"><?php echo $this->translate('TAB.ADDRESS'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#btabs-animated-fade-geo-spatial-address"><?php echo $this->translate('TAB.GEO_SPATIAL'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#btabs-animated-fade-system-address"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="#btabs-animated-fade-settings-address">
                        <i class="si si-settings"></i>
                    </a>
                </li>
            </ul>
            <div class="block-content tab-content overflow-hidden">
                <div class="tab-pane fade show active" id="btabs-animated-fade-address" role="tabpanel">

                    <h4><?php echo $this->translate('TITLE.ADDRESS'); ?></h4>

                    <div class="row">
                        <div class="col-md-8">

                            <div class="form-group">
                                <label for="type_address"><?php echo $this->addressForm->type_address->getLabel(); ?></label>
                                <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                   title="<?php echo $this->addressForm->type_address->getDescription(); ?>"></i>
                                <?php echo $this->addressForm->type_address; ?>
                                <div class="message-container"></div>
                            </div>

                        </div>
                        <div class="col-md-4">

                            <div class="form-group">
                                <div class="custom-control custom-switch">
                                    <?php echo $this->addressForm->primary->setAttrib('id','primary_address'); ?>
                                    <?php echo $this->addressForm->primary; ?>
                                    <label class="custom-control-label font-w400 primary-address" for="primary_address"><?php echo $this->addressForm->primary->getLabel(); ?></label>
                                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                                       title="<?php echo $this->addressForm->primary->getDescription(); ?>"></i>
                                </div>
                                <div class="message-container"></div>
                            </div>

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="address"><?php echo $this->addressForm->address->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->address->getDescription(); ?>"></i>
                        <div class="overflow-auto">
                            <?php echo $this->addressForm->address; ?>
                            <i class="fa fa-fw fa-circle-notch fa-spin mr-1 address-lookup-spinner hide"></i>
                        </div>
                        <div class="message-container"></div>
                        <div id="select-address-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="address2"><?php echo $this->addressForm->address2->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->address2->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->address2; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="city"><?php echo $this->addressForm->city->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->city->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->city; ?>
                        <div class="message-container"></div>
                    </div>
                    <!-- Un-hide if you need county info -->
                    <div class="form-group hide">
                        <label for="county"><?php echo $this->addressForm->county->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->county->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->county; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="state"><?php echo $this->addressForm->state->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->state->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->state; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="postal_code"><?php echo $this->addressForm->postal_code->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->postal_code->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->postal_code; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="country"><?php echo $this->addressForm->country->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->country->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->country; ?>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-geo-spatial-address" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.GEO_SPATIAL'); ?></h4>

                    <div class="form-group">
                        <label for="lat"><?php echo $this->addressForm->lat->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->lat->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->lat; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="lng"><?php echo $this->addressForm->lng->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->lng->getDescription(); ?>"></i>
                        <?php echo $this->addressForm->lng; ?>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-system-address" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                    <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                    <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                    <hr />
                    <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                    <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-settings-address" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->addressForm->active; ?>
                            <label class="custom-control-label font-w400" for="active_address"><?php echo $this->addressForm->active->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->addressForm->active->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->addressForm->deleted; ?>
                            <label class="custom-control-label font-w400" for="deleted_address"><?php echo $this->addressForm->deleted->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->addressForm->deleted->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>

                </div>
            </div>
        </div>
        <!-- END Block Tabs Animated Fade -->

        <!-- Overlay allows us to shut off the form until an address is selected. -->
        <div class="overlay"></div>

    </div>
</form>
<!-- END User Form -->
