<!-- User Form -->
<form id="address-form" name="<?php echo $this->addressForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-address">Address</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-geo-spatial">Geo Spatial</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system">System</a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-address" role="tabpanel">
                <h4>Address Info</h4>

                <div class="form-group form-ids">
                    <label for="address_id"><?php echo $this->addressForm->address_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->address_id->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->address_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_address"><?php echo $this->addressForm->type_address->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->type_address->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->type_address; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="address"><?php echo $this->addressForm->address->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->address->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->address; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="address2"><?php echo $this->addressForm->address2->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->address2->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->address2; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="city"><?php echo $this->addressForm->city->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->city->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->city; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="county"><?php echo $this->addressForm->county->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->county->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->county; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="state"><?php echo $this->addressForm->state->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->state->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->state; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="postal_code"><?php echo $this->addressForm->postal_code->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->postal_code->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->postal_code; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="country"><?php echo $this->addressForm->country->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->country->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->country; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-geo-spatial" role="tabpanel">
                <h4>Geo Spatial</h4>

                <div class="form-group">
                    <label for="lat"><?php echo $this->addressForm->lat->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->lat->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->lat; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="lng"><?php echo $this->addressForm->lng->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->addressForm->lng->getDescription(); ?>"></i>
                    <?php echo $this->addressForm->lng; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system" role="tabpanel">
                <h4>System</h4>

                <p><strong>Update Date: </strong><span class="update_date"></span></p>
                <p><strong>Last Updated By: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong>Create Date: </strong><span class="create_date"></span></p>
                <p><strong>Created By: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings" role="tabpanel">
                <h4>Settings</h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->addressForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_address"><?php echo $this->addressForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->addressForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_address"><?php echo $this->addressForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->addressForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END User Form -->
