<!-- User Form -->
<form id="contact-form" name="<?php echo $this->contactForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->contactForm->entity; ?>
        <?php echo $this->contactForm->entity_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <div class="form-group py3">
        <label for="contact_id"><?php echo $this->contactForm->contact_id->getLabel(); ?></label>
        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
           title="<?php echo $this->contactForm->contact_id->getDescription(); ?>"></i>
        <?php echo $this->contactForm->contact_id; ?>
        <div class="message-container"></div>
    </div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-contact-contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-contact">System</a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-contact">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-contact-contact" role="tabpanel">
                <h4>Contact</h4>
                <div class="form-group">
                    <label for="type_contact"><?php echo $this->contactForm->type_contact->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->contactForm->type_contact->getDescription(); ?>"></i>
                    <?php echo $this->contactForm->type_contact; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="contact_value"><?php echo $this->contactForm->contact_value->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->contactForm->contact_value->getDescription(); ?>"></i>
                    <?php echo $this->contactForm->contact_value; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->contactForm->primary; ?>
                        <label class="custom-control-label font-w400" for="primary"><?php echo $this->contactForm->primary->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->contactForm->primary->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-contact" role="tabpanel">
                <h4>System</h4>

                <p><strong>Update Date: </strong><span class="update_date"></span></p>
                <p><strong>Last Updated By: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong>Create Date: </strong><span class="create_date"></span></p>
                <p><strong>Created By: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-contact" role="tabpanel">
                <h4>Settings</h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->contactForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_contact"><?php echo $this->contactForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->contactForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->contactForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_contact"><?php echo $this->contactForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->contactForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END User Form -->
