<!-- User Form -->
<form id="contact-form" name="<?php echo $this->contactForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->contactForm->entity; ?>
        <?php echo $this->contactForm->entity_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <div class="form-group py3">
        <label for="contact_id"><?php echo $this->contactForm->contact_id->getLabel(); ?></label>
        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
           title="<?php echo $this->contactForm->contact_id->getDescription(); ?>"></i>
        <?php echo $this->contactForm->contact_id; ?>
        <div class="message-container"></div>
    </div>

    <div class="overlay-container">

        <!-- Block Tabs Animated Fade -->
        <div class="block">
            <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" href="#btabs-animated-fade-contact-contact"><?php echo $this->translate('TAB.CONTACT'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#btabs-animated-fade-system-contact"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="#btabs-animated-fade-settings-contact">
                        <i class="si si-settings"></i>
                    </a>
                </li>
            </ul>
            <div class="block-content tab-content overflow-hidden">
                <div class="tab-pane fade show active" id="btabs-animated-fade-contact-contact" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.CONTACT'); ?></h4>
                    <div class="form-group">
                        <label for="type_contact"><?php echo $this->contactForm->type_contact->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->contactForm->type_contact->getDescription(); ?>"></i>
                        <?php echo $this->contactForm->type_contact; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <label for="contact_value"><?php echo $this->contactForm->contact_value->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->contactForm->contact_value->getDescription(); ?>"></i>
                        <?php echo $this->contactForm->contact_value; ?>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->contactForm->primary->setAttrib('id','primary_contact'); ?>
                            <?php echo $this->contactForm->primary; ?>
                            <label class="custom-control-label font-w400" for="primary_contact"><?php echo $this->contactForm->primary->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->contactForm->primary->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-system-contact" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                    <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                    <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                    <hr />
                    <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                    <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-settings-contact" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->contactForm->active; ?>
                            <label class="custom-control-label font-w400" for="active_contact"><?php echo $this->contactForm->active->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->contactForm->active->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->contactForm->deleted; ?>
                            <label class="custom-control-label font-w400" for="deleted_contact"><?php echo $this->contactForm->deleted->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->contactForm->deleted->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>

                </div>
            </div>
        </div>
        <!-- END Block Tabs Animated Fade -->

        <!-- Overlay allows us to shut off the form until an contact is selected. -->
        <div class="overlay"></div>

    </div>

</form>
<!-- END User Form -->
