<!-- User Form -->
<form id="org-user-form" name="<?php echo $this->orgUserForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->orgUserForm->entity; ?>
        <?php echo $this->orgUserForm->entity_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <div class="row">
        <div class="col-md-12">
            <div id="instructions-container" class="hide">
                <?php echo $this->translate('INSTRUCTIONS.ORGUSERS'); ?>
            </div>
        </div>
    </div>

    <div class="form-group py3">
        <label for="org_user_id"><?php echo $this->orgUserForm->org_user_id->getLabel(); ?></label>
        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
           title="<?php echo $this->orgUserForm->org_user_id->getDescription(); ?>"></i>
        <?php echo $this->orgUserForm->org_user_id; ?>
        <?php echo $this->orgUserForm->user_id; ?>
        <div class="message-container"></div>
    </div>

    <div class="overlay-container">

        <!-- Block Tabs Animated Fade -->
        <div class="block">
            <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" href="#btabs-animated-fade-contact-contact"><?php echo $this->translate('TAB.ORGS'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#btabs-animated-fade-system-contact"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="#btabs-animated-fade-settings-contact">
                        <i class="si si-settings"></i>
                    </a>
                </li>
            </ul>
            <div class="block-content tab-content overflow-hidden">
                <div class="tab-pane fade show active" id="btabs-animated-fade-contact-contact" role="tabpanel">

                    <h4><?php echo $this->translate('TITLE.ORGS'); ?></h4>

                    <div class="form-group">
                        <label for="org_id"><?php echo $this->orgUserForm->org_id->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->orgUserForm->org_id->getDescription(); ?>"></i>
                        <?php echo $this->orgUserForm->org_id; ?>
                        <div class="message-container"></div>
                    </div>

                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->orgUserForm->primary; ?>
                            <label class="custom-control-label font-w400" for="primary_org"><?php echo $this->orgUserForm->primary->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->orgUserForm->primary->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>

                    <div class="form-group">
                        <label for="type_user_role"><?php echo $this->orgUserForm->type_user_role->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->orgUserForm->type_user_role->getDescription(); ?>"></i>
                        <?php echo $this->orgUserForm->type_user_role; ?>
                        <div class="message-container"></div>
                    </div>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-system-contact" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                    <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                    <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                    <hr />
                    <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                    <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

                </div>
                <div class="tab-pane fade" id="btabs-animated-fade-settings-contact" role="tabpanel">
                    <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->orgUserForm->active; ?>
                            <label class="custom-control-label font-w400" for="active_orguser"><?php echo $this->orgUserForm->active->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->orgUserForm->active->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-switch">
                            <?php echo $this->orgUserForm->deleted; ?>
                            <label class="custom-control-label font-w400" for="deleted_orguser"><?php echo $this->orgUserForm->deleted->getLabel(); ?></label>
                            <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                               title="<?php echo $this->orgUserForm->deleted->getDescription(); ?>"></i>
                        </div>
                        <div class="message-container"></div>
                    </div>

                </div>
            </div>
        </div>
        <!-- END Block Tabs Animated Fade -->

        <!-- Overlay allows us to shut off the form until an contact is selected. -->
        <div class="overlay"></div>

    </div>

</form>
<!-- END User Form -->
