<!-- Org Form -->
<form id="org-form" name="<?php echo $this->orgForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-data"><?php echo $this->translate('TAB.ORG_INFO'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-profile"><?php echo $this->translate('TAB.PROFILE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-referrals"><?php echo $this->translate('TAB.REFERRAL'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-data" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.ORG_INFO'); ?></h4>

                <div class="form-group form-ids">
                    <label for="org_id"><?php echo $this->orgForm->org_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->org_id->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->org_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="parent_org_id"><?php echo $this->orgForm->parent_org_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->parent_org_id->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->parent_org_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="orgname"><?php echo $this->orgForm->orgname->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->orgname->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->orgname; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="org_display_name"><?php echo $this->orgForm->org_display_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->org_display_name->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->org_display_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="org_description"><?php echo $this->orgForm->org_description->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->org_description->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->org_description; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-profile" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.PROFILE'); ?></h4>

                <div class="form-group">
                    <label for="company_name"><?php echo $this->orgForm->company_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->company_name->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->company_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="domain"><?php echo $this->orgForm->domain->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->domain->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->domain; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_org"><?php echo $this->orgForm->type_org->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->type_org->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->type_org; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_business"><?php echo $this->orgForm->type_business->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->type_business->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->type_business; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-referrals" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.REFERRALS'); ?></h4>

                <div class="form-group">
                    <label for="referral_code"><?php echo $this->orgForm->referral_code->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->referral_code->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->referral_code; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_hearabout"><?php echo $this->orgForm->type_hearabout->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->type_hearabout->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->type_hearabout; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="referral_org_id"><?php echo $this->orgForm->referral_org_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->referral_org_id->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->referral_org_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="referral_user_id"><?php echo $this->orgForm->referral_user_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->orgForm->referral_user_id->getDescription(); ?>"></i>
                    <?php echo $this->orgForm->referral_user_id; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATE_IP'); ?>: </strong><span class="update_ip"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATE_IP'); ?>: </strong><span class="create_ip"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->orgForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_org"><?php echo $this->orgForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->orgForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->orgForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_org"><?php echo $this->orgForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->orgForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Org Form -->
