<!-- User Form -->
<form id="user-form" name="<?php echo $this->userForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-data">User</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-profile">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-referrals">Referrals</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system">System</a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-data" role="tabpanel">
                <h4>User Info</h4>

                <div class="form-group form-ids">
                    <label for="user_id"><?php echo $this->userForm->user_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->user_id->getDescription(); ?>"></i>
                    <?php echo $this->userForm->user_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="username"><?php echo $this->userForm->username->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->username->getDescription(); ?>"></i>
                    <?php echo $this->userForm->username; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="email"><?php echo $this->userForm->email->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->email->getDescription(); ?>"></i>
                    <?php echo $this->userForm->email; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="role"><?php echo $this->userForm->role->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->role->getDescription(); ?>"></i>
                    <?php echo $this->userForm->role; ?>
                    <div class="message-container"></div>
                </div>
                <hr />
                <h4>Reset Password</h4>
                <div class="form-group">
                    <label for="password"><?php echo $this->userForm->password->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->password->getDescription(); ?>"></i>
                    <?php echo $this->userForm->password; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-profile" role="tabpanel">
                <h4>User Profile</h4>

                <div class="form-group">
                    <label for="user_display_name"><?php echo $this->userForm->user_display_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->user_display_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->user_display_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_title"><?php echo $this->userForm->type_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->type_title->getDescription(); ?>"></i>
                    <?php echo $this->userForm->type_title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="first_name"><?php echo $this->userForm->first_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->first_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->first_name; ?>
                    <div class="message-container"></div>
                </div>
                <!-- div class="form-group">
                    <label for="middle_name"><?php # echo $this->userForm->middle_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php # echo $this->userForm->middle_name->getDescription(); ?>"></i>
                    <?php # echo $this->userForm->middle_name; ?>
                    <div class="message-container"></div>
                </div -->
                <div class="form-group">
                    <label for="last_name"><?php echo $this->userForm->last_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->last_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->last_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_suffix"><?php echo $this->userForm->type_suffix->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->type_suffix->getDescription(); ?>"></i>
                    <?php echo $this->userForm->type_suffix; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="company_title"><?php echo $this->userForm->company_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->company_title->getDescription(); ?>"></i>
                    <?php echo $this->userForm->company_title; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-referrals" role="tabpanel">
                <h4>Referrals</h4>

                <div class="form-group">
                    <label for="referral_org_id"><?php echo $this->userForm->referral_org_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->referral_org_id->getDescription(); ?>"></i>
                    <?php echo $this->userForm->referral_org_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="referral_user_id"><?php echo $this->userForm->referral_user_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->referral_user_id->getDescription(); ?>"></i>
                    <?php echo $this->userForm->referral_user_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_hearabout"><?php echo $this->userForm->type_hearabout->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->type_hearabout->getDescription(); ?>"></i>
                    <?php echo $this->userForm->type_hearabout; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system" role="tabpanel">
                <h4>System</h4>

                <p><strong>Password Reset Key: </strong><span class="password_reset_key"></span></p>
                <p><strong>Email Verify Key: </strong><span class="email_verify_key"></span></p>
                <hr />
                <p><strong>Last Login Date: </strong><span class="last_login_date"></span></p>
                <p><strong>Last Login IP: </strong><span class="last_login_ip"></span></p>
                <hr />
                <p><strong>Update Date: </strong><span class="update_date"></span></p>
                <p><strong>Last Updated By: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong>Create Date: </strong><span class="create_date"></span></p>
                <p><strong>Created By: </strong><span class="create_user_id"></span></p>
                <p><strong>Create IP: </strong><span class="create_ip"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings" role="tabpanel">
                <h4>Settings</h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->userForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_user"><?php echo $this->userForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->userForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->userForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_user"><?php echo $this->userForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->userForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END User Form -->
