<?php echo $this->partial('admin/hero.phtml', ['template' => $this->template]); ?>

<!-- Page Content -->
<div class="content content-narrow">

    <!-- Users -->
    <div class="row row-deck">
        <div class="col-lg-12">
            <div id="page-messages"></div>
        </div>
    </div>
    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">

                <div class="block-header block-header-default">
                    <h3 class="block-title"><?php echo $this->translate('TITLE.USERS'); ?></h3>
                    <!-- Block Options -->
                    <div class="block-options">
                        <button id="add-user" type="button" class="btn-block-option">
                            <i class="si si-plus"></i>
                        </button>
                        <button type="button" class="btn-block-option" data-tiger-reload-table="#usersDT">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option"
                                data-tiger-control="#usersDT-container"
                                data-tiger-class-open="si-arrow-up"
                                data-tiger-class-close="si-arrow-down">
                            <i class="si si-arrow-up"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                    <!-- END Block Options -->
                </div>

                <div id="usersDT-container">
                    <div class="block-content block-content-full">
                        <table id="usersDT" data-entity="user" style="width: 100%;"
                               class="table table-striped table-hover table-borderless table-vcenter font-size-sm mb-0"></table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Users -->

</div>
<!-- END Page Content -->

<!-- User add/edit form -->
<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-users-form" tabindex="-1" data-backdrop="static"
     role="dialog" aria-labelledby="modal-users-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-user-header" class="block-title"><?php echo $this->translate('FORM.ADD_USER'); ?></h3>
                    <h3 id="edit-user-header" class="block-title hide"><?php echo $this->translate('FORM.EDIT_USER'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('admin/user_form.phtml', [ 'userForm' => $this->userForm ] ); ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-user-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
<!-- END User add/edit form -->

<!-- User Contact form -->
<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-contact-form" tabindex="-1" data-backdrop="static"
     role="dialog" aria-labelledby="modal-contact-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="add-user-header" class="block-title"><?php echo $this->translate('FORM.CONTACTS'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('admin/contact_form.phtml', [ 'contactForm' => $this->contactForm ] ); ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-contact-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
<!-- END User Contact form -->

<!-- User Address form -->
<!-- Fade In Block Modal -->
<div class="modal fade" id="modal-address-form" tabindex="-1" data-backdrop="static"
     role="dialog" aria-labelledby="modal-address-form" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 id="" class="block-title"><?php echo $this->translate('FORM.ADDRESSES'); ?></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">
                    <?php echo $this->partial('admin/address_form.phtml', [ 'addressForm' => $this->addressForm ] ); ?>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-secondary float-left" data-dismiss="modal">
                        <i class="fa fa-times mr-1 icon"></i>
                        <?php echo $this->translate('FORM.CLOSE'); ?>
                    </button>
                    <button type="button" class="btn btn-sm btn-success" id="save-address-button">
                        <i class="fa fa-fw fa-circle-notch fa-spin mr-1 ajax hide"></i>
                        <i class="fa fa-check mr-1 icon"></i> <?php echo $this->translate('FORM.SAVE'); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Fade In Block Modal -->
<!-- END User Address form -->
