<!-- User Form -->
<form id="user-form" name="<?php echo $this->userForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-user"><?php echo $this->translate('TAB.USER'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-profile-user"><?php echo $this->translate('TAB.PROFILE'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-referrals-user"><?php echo $this->translate('TAB.REFERRALS'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-user"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-user">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-user" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.USER'); ?></h4>

                <div class="form-group form-ids">
                    <label for="user_id"><?php echo $this->userForm->user_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->user_id->getDescription(); ?>"></i>
                    <?php echo $this->userForm->user_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="username"><?php echo $this->userForm->username->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->username->getDescription(); ?>"></i>
                    <?php echo $this->userForm->username; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="email"><?php echo $this->userForm->email->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->email->getDescription(); ?>"></i>
                    <?php echo $this->userForm->email; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="role"><?php echo $this->userForm->role->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->role->getDescription(); ?>"></i>
                    <?php echo $this->userForm->role; ?>
                    <div class="message-container"></div>
                </div>
                <hr />
                <h4>Reset Password</h4>
                <div class="form-group">
                    <label for="password"><?php echo $this->userForm->password->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->translate('DESCRIPTION.USER_ADMIN_PASSWORD'); ?>"></i>
                    <?php echo $this->userForm->password; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-profile-user" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.PROFILE'); ?></h4>

                <div class="form-group">
                    <label for="user_display_name"><?php echo $this->userForm->user_display_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->user_display_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->user_display_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_title"><?php echo $this->userForm->type_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->type_title->getDescription(); ?>"></i>
                    <?php echo $this->userForm->type_title; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="first_name"><?php echo $this->userForm->first_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->first_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->first_name; ?>
                    <div class="message-container"></div>
                </div>
                <!-- Unhide if you need to collect a middle name. -->
                <div class="form-group hide">
                    <label for="middle_name"><?php echo $this->userForm->middle_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->middle_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->middle_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="last_name"><?php echo $this->userForm->last_name->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->last_name->getDescription(); ?>"></i>
                    <?php echo $this->userForm->last_name; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_suffix"><?php echo $this->userForm->type_suffix->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->type_suffix->getDescription(); ?>"></i>
                    <?php echo $this->userForm->type_suffix; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="company_title"><?php echo $this->userForm->company_title->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->company_title->getDescription(); ?>"></i>
                    <?php echo $this->userForm->company_title; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-referrals-user" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.REFERRALS'); ?></h4>

                <div class="form-group">
                    <label for="referral_org_id"><?php echo $this->userForm->referral_org_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->referral_org_id->getDescription(); ?>"></i>
                    <?php echo $this->userForm->referral_org_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="referral_user_id"><?php echo $this->userForm->referral_user_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->referral_user_id->getDescription(); ?>"></i>
                    <?php echo $this->userForm->referral_user_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="type_hearabout"><?php echo $this->userForm->type_hearabout->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                       title="<?php echo $this->userForm->type_hearabout->getDescription(); ?>"></i>
                    <?php echo $this->userForm->type_hearabout; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-user" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.PASSWORD_RESET_KEY'); ?>: </strong><span class="password_reset_key"></span></p>
                <p><strong><?php echo $this->translate('LABEL.EMAIL_VERIFY_KEY'); ?>: </strong><span class="email_verify_key"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.LAST_LOGIN_DATE'); ?>: </strong><span class="last_login_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.LAST_LOGIN_IP'); ?>: </strong><span class="last_login_ip"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATE_IP'); ?>: </strong><span class="update_ip"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATE_IP'); ?>: </strong><span class="create_ip"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-user" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->userForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_user"><?php echo $this->userForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->userForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->userForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_user"><?php echo $this->userForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-animation="true" data-placement="left"
                           title="<?php echo $this->userForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END User Form -->
