<!-- Translation Form -->
<form id="translation-form" name="<?php echo $this->translationForm->getName(); ?>" class="" novalidate="novalidate">

    <div class="hide">
        <?php echo $this->translationForm->translation_id; ?>
    </div>

    <div class="row"><div class="col-md-12 form-message"></div></div>

    <!-- Block Tabs Animated Fade -->
    <div class="block">
        <ul class="nav nav-tabs nav-tabs-alt" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-animated-fade-translation"><?php echo $this->translate('TAB.TRANSLATION'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-animated-fade-system-translation"><?php echo $this->translate('TAB.SYSTEM'); ?></a>
            </li>
            <li class="nav-item ml-auto">
                <a class="nav-link" href="#btabs-animated-fade-settings-translation">
                    <i class="si si-settings"></i>
                </a>
            </li>
        </ul>
        <div class="block-content tab-content overflow-hidden">
            <div class="tab-pane fade show active" id="btabs-animated-fade-translation" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.TRANSLATION'); ?></h4>

                <div class="form-group">
                    <label for="message_id"><?php echo $this->translationForm->message_id->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->translationForm->message_id->getDescription(); ?>"></i>
                    <?php echo $this->translationForm->message_id; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="message_text"><?php echo $this->translationForm->message_text->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->translationForm->message_text->getDescription(); ?>"></i>
                    <?php echo $this->translationForm->message_text; ?>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <label for="locale"><?php echo $this->translationForm->locale->getLabel(); ?></label>
                    <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                       title="<?php echo $this->translationForm->locale->getDescription(); ?>"></i>
                    <?php echo $this->translationForm->locale; ?>
                    <div class="message-container"></div>
                </div>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-system-translation" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SYSTEM'); ?></h4>

                <p><strong><?php echo $this->translate('LABEL.UPDATE_DATE'); ?>: </strong><span class="update_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.UPDATED_BY'); ?>: </strong><span class="update_user_id"></span></p>
                <hr />
                <p><strong><?php echo $this->translate('LABEL.CREATE_DATE'); ?>: </strong><span class="create_date"></span></p>
                <p><strong><?php echo $this->translate('LABEL.CREATED_BY'); ?>: </strong><span class="create_user_id"></span></p>

            </div>
            <div class="tab-pane fade" id="btabs-animated-fade-settings-translation" role="tabpanel">
                <h4><?php echo $this->translate('TITLE.SETTINGS'); ?></h4>

                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->translationForm->active; ?>
                        <label class="custom-control-label font-w400" for="active_translation"><?php echo $this->translationForm->active->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->translationForm->active->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <?php echo $this->translationForm->deleted; ?>
                        <label class="custom-control-label font-w400" for="deleted_translation"><?php echo $this->translationForm->deleted->getLabel(); ?></label>
                        <i class="desc-info fa fa-info-circle" data-toggle="tooltip" data-placement="left"
                           title="<?php echo $this->translationForm->deleted->getDescription(); ?>"></i>
                    </div>
                    <div class="message-container"></div>
                </div>

            </div>
        </div>
    </div>
    <!-- END Block Tabs Animated Fade -->

</form>
<!-- END Translation Form -->
