<?php


class Core_Service_Template extends Oneui_Service_Template
{

    public function build_nav($nav_array = false, $nav_horizontal = false, $print = true)
    {


        $menu =
                '<li class="nav-main-item">
                    <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="false" href="#">
                        <i class="nav-main-link-icon si si-layers"></i>
                        <span class="nav-main-link-name">Page Packs</span>
                    </a>
                    <ul class="nav-main-submenu">
                        <li class="nav-main-item">
                            <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="false" href="#">
                                <i class="nav-main-link-icon si si-bag"></i>
                                <span class="nav-main-link-name">e-Commerce</span>
                            </a>
                            <ul class="nav-main-submenu">
                                <li class="nav-main-item">
                                    <a class="nav-main-link" href="be_pages_ecom_dashboard.php">
                                        <span class="nav-main-link-name">Dashboard</span>
                                    </a>
                                </li>
                                <li class="nav-main-item">
                                    <a class="nav-main-link" href="be_pages_ecom_orders.php">
                                        <span class="nav-main-link-name">Orders</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-main-item">
                            <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="false" href="#">
                                <i class="nav-main-link-icon si si-handbag"></i>
                                <span class="nav-main-link-name">e-Commerce Store</span>
                            </a>
                            <ul class="nav-main-submenu">
                                <li class="nav-main-item">
                                    <a class="nav-main-link" href="be_pages_ecom_store_home.php">
                                        <span class="nav-main-link-name">Home</span>
                                    </a>
                                </li>
                                <li class="nav-main-item">
                                    <a class="nav-main-link" href="be_pages_ecom_store_search.php">
                                        <span class="nav-main-link-name">Search Results</span>
                                    </a>
                                </li>
                                <li class="nav-main-item">
                                    <a class="nav-main-link" href="be_pages_ecom_store_products.php">
                                        <span class="nav-main-link-name">Products List</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>';

        echo $menu;

        // return parent::build_nav($nav_array, $nav_horizontal, $print); // TODO: Change the autogenerated stub
    }

}