<!doctype html>
<html dir="ltr" lang="<?php echo LANG; ?>">
    <head>

        <!-- Head Meta -->
        <?php echo $this->headMeta(); ?>

        <!-- Stylesheets -->
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <!-- Document Title -->
        <title><?php echo $this->title; ?></title>

    </head>
    <body>

        <?php echo $this->layout()->content; ?>

        <!-- Footer JavaScripts -->
        <?php echo $this->inlineScript(); ?>

    </body>
</html>
